import { ProfessionalSelect } from '../../../components/forms/ProfessionalSelect';
import { DateControl } from '../../../components/forms/DateControl';
import { useEffect, useState, type FormEvent } from 'react';
import { Button } from '../../../components/common/Button';
import { Modal } from '../../../components/common/Modal';
import { useToast } from '../../../components/common/Toast';
import { getApiErrorMessage } from '../../../services/apiClient';
import { useCollectionsLocalization } from '../localization/collectionsTranslations';
import { collectionsService } from '../services/collectionsService';
import type { BankPortfolioCollector, BankVisitAccess, BankVisitCaseLookup, BankVisitDetails } from '../types/collections';

interface Props { bankId: string; access?: BankVisitAccess; open: boolean; initialCaseId?: string; initialSearch?: string; onClose: () => void; onSaved: (visit: BankVisitDetails) => void }

export function CreateVisitModal({ bankId, access, open, initialCaseId, initialSearch, onClose, onSaved }: Props) {
  const { ct } = useCollectionsLocalization(); const toast = useToast();
  const [cases,setCases]=useState<BankVisitCaseLookup[]>([]),[collectors,setCollectors]=useState<BankPortfolioCollector[]>([]),[search,setSearch]=useState(initialSearch??''),[caseId,setCaseId]=useState(initialCaseId??''),[collectorId,setCollectorId]=useState(''),[scheduledAt,setScheduledAt]=useState(''),[address,setAddress]=useState(''),[purpose,setPurpose]=useState(''),[notes,setNotes]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{if(!open)return;const id=setTimeout(()=>void collectionsService.bankVisitCases(bankId,search).then(setCases).catch(e=>toast.error(getApiErrorMessage(e,ct('visitLoadError')))),250);return()=>clearTimeout(id);},[bankId,ct,open,search,toast]);
  useEffect(()=>{if(open&&access?.isManager)void collectionsService.bankVisitCollectors(bankId).then(setCollectors).catch(e=>toast.error(getApiErrorMessage(e,ct('visitLoadError'))));},[access?.isManager,bankId,ct,open,toast]);
  useEffect(()=>{if(open){setSearch(initialSearch??'');setCaseId(initialCaseId??'');setCollectorId('');setScheduledAt('');setAddress('');setPurpose('');setNotes('');}},[initialCaseId,initialSearch,open]);
  const chosen=cases.find(x=>x.id===caseId);
  useEffect(()=>{if(chosen){setAddress(chosen.address??'');setCollectorId(chosen.assignedCollectorId??'');}},[chosen]);
  async function submit(e:FormEvent){e.preventDefault();if(!caseId||!scheduledAt||saving)return;setSaving(true);try{const created=await collectionsService.createBankVisit(bankId,{caseId,assignedCollectorId:access?.isManager?collectorId||undefined:undefined,scheduledAt:new Date(scheduledAt).toISOString(),address:access?.isManager?address.trim()||undefined:undefined,purpose:purpose.trim()||undefined,notes:notes.trim()||undefined});onSaved(created);}catch(err){toast.error(getApiErrorMessage(err,ct('visitSaveError')));}finally{setSaving(false);}}
  return <Modal open={open} onClose={()=>!saving&&onClose()} size="lg" title={ct('createVisit')} footer={<><Button disabled={saving} fullWidth={false} onClick={onClose} variant="outline">{ct('cancel')}</Button><Button disabled={!caseId||!scheduledAt||(access?.isManager&&!collectorId)} form="create-bank-visit" fullWidth={false} isLoading={saving} type="submit">{ct('createVisit')}</Button></>}><form className="space-y-4" id="create-bank-visit" onSubmit={submit}><label className="block text-sm font-semibold">{ct('searchPortfolioCases')}<input className="field mt-2" placeholder={ct('searchVisits')} value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="block text-sm font-semibold">{ct('caseId')}<ProfessionalSelect className="field mt-2" required value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">{ct('selectCase')}</option>{cases.map(x=><option key={x.id} value={x.id}>{x.caseNumber} — {x.customerName}</option>)}</ProfessionalSelect></label>{chosen&&<div className="grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><Info label={ct('customerName')} value={chosen.customerName}/><Info label={ct('mobile')} value={chosen.mobile}/><Info label={ct('address')} value={chosen.address}/><Info label={ct('assignedCollector')} value={chosen.assignedCollectorName}/></div>}<div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">{ct('visitDateTime')}<DateControl className="field mt-2" required mode="datetime" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></label>{access?.isManager?<label className="block text-sm font-semibold">{ct('assignedCollector')}<ProfessionalSelect className="field mt-2" required value={collectorId} onChange={e=>setCollectorId(e.target.value)}><option value="">{ct('selectCollector')}</option>{collectors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></label>:null}</div>{access?.isManager?<label className="block text-sm font-semibold">{ct('visitAddress')}<textarea className="field mt-2" maxLength={600} rows={2} value={address} onChange={e=>setAddress(e.target.value)}/></label>:null}<label className="block text-sm font-semibold">{ct('visitPurpose')}<input className="field mt-2" maxLength={500} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label className="block text-sm font-semibold">{ct('notes')}<textarea className="field mt-2" maxLength={3000} rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></form></Modal>;
}

function Info({label,value}:{label:string;value?:string}){return <div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 break-words font-semibold text-mis-navy">{value||'—'}</p></div>}
