import { ProfessionalSelect } from '../../../components/forms/ProfessionalSelect';
import { DateControl } from '../../../components/forms/DateControl';
import { useEffect,useMemo,useState,type FormEvent } from 'react';
import { Button } from '../../../components/common/Button';
import { Modal } from '../../../components/common/Modal';
import { useToast } from '../../../components/common/Toast';
import { getApiErrorMessage } from '../../../services/apiClient';
import { useCollectionsLocalization } from '../localization/collectionsTranslations';
import { collectionsService } from '../services/collectionsService';
import type { BankComplaintAccess,BankComplaintCase,BankComplaintDetails,BankComplaintEmployee } from '../types/collections';

const types=['PAYMENT_ISSUE','COLLECTOR_CONDUCT','INCORRECT_INFORMATION','COMMUNICATION_ISSUE','VISIT_COMPLAINT','ACCOUNT_DISPUTE','SERVICE_COMPLAINT','OTHER'];
export function CreateComplaintModal({bankId,access,open,initialCaseId,initialSearch,onClose,onSaved}:{bankId:string;access?:BankComplaintAccess;open:boolean;initialCaseId?:string;initialSearch?:string;onClose:()=>void;onSaved:(x:BankComplaintDetails)=>void}){const{ct}=useCollectionsLocalization();const toast=useToast();const[cases,setCases]=useState<BankComplaintCase[]>([]),[employees,setEmployees]=useState<BankComplaintEmployee[]>([]),[search,setSearch]=useState(initialSearch??initialCaseId??''),[caseId,setCaseId]=useState(initialCaseId??''),[saving,setSaving]=useState(false);const selected=useMemo(()=>cases.find(x=>x.id===caseId),[caseId,cases]);
useEffect(()=>{if(!open)return;const timer=setTimeout(()=>void collectionsService.bankComplaintCases(bankId,search).then(setCases).catch(e=>toast.error(getApiErrorMessage(e,ct('complaintLoadError')))),250);return()=>clearTimeout(timer);},[bankId,ct,open,search,toast]);useEffect(()=>{if(open&&access?.isManager)void collectionsService.bankComplaintEmployees(bankId).then(setEmployees).catch(e=>toast.error(getApiErrorMessage(e,ct('complaintLoadError'))));},[access?.isManager,bankId,ct,open,toast]);useEffect(()=>{if(open){setCaseId(initialCaseId??'');setSearch(initialSearch??initialCaseId??'');}},[initialCaseId,initialSearch,open]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(saving)return;const f=new FormData(e.currentTarget);setSaving(true);try{const due=String(f.get('dueAt')||'');const x=await collectionsService.createBankComplaint(bankId,{caseId:String(f.get('caseId')),type:String(f.get('type')),priority:String(f.get('priority')),description:String(f.get('description')),dueAt:due?new Date(due).toISOString():undefined,assignedToId:String(f.get('assignedToId')||'')||undefined,note:String(f.get('note')||'')||undefined});onSaved(x);}catch(err){toast.error(getApiErrorMessage(err,ct('complaintSaveError')));}finally{setSaving(false);}}
return <Modal open={open} onClose={()=>!saving&&onClose()} size="lg" title={ct('createComplaint')} footer={<><Button disabled={saving} fullWidth={false} onClick={onClose} variant="outline">{ct('cancel')}</Button><Button form="create-complaint-form" fullWidth={false} isLoading={saving} type="submit">{ct('createComplaint')}</Button></>}><form className="grid gap-4 sm:grid-cols-2" id="create-complaint-form" onSubmit={submit}><label className="sm:col-span-2 text-sm font-semibold">{ct('case')}<input className="field mt-2" disabled={Boolean(initialCaseId)} placeholder={ct('searchCases')} value={search} onChange={e=>setSearch(e.target.value)}/><ProfessionalSelect className="field mt-2" disabled={Boolean(initialCaseId)} name="caseId" required value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">{ct('selectCase')}</option>{cases.map(x=><option key={x.id} value={x.id}>{x.caseNumber} — {x.customerName}</option>)}</ProfessionalSelect>{initialCaseId&&<input name="caseId" type="hidden" value={caseId}/>}</label><Info label={ct('customer')} value={selected?.customerName}/><Info label={ct('mobile')} value={selected?.mobile}/><Field label={ct('complaintType')}><ProfessionalSelect className="field" name="type" required>{types.map(x=><option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></Field><Field label={ct('priority')}><ProfessionalSelect className="field" name="priority" required defaultValue="MEDIUM">{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></Field><Field label={ct('dueDate')}><DateControl className="field" name="dueAt" mode="datetime"/></Field>{access?.isManager?<Field label={ct('assignedTo')}><ProfessionalSelect className="field" name="assignedToId"><option value="">{ct('unassigned')}</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></Field>:null}<label className="sm:col-span-2 text-sm font-semibold">{ct('description')}<textarea className="field mt-2" maxLength={4000} name="description" required rows={4}/></label><label className="sm:col-span-2 text-sm font-semibold">{ct('internalNotes')}<textarea className="field mt-2" maxLength={3000} name="note" rows={2}/></label></form></Modal>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-semibold">{label}<div className="mt-2">{children}</div></label>}function Info({label,value}:{label:string;value?:string}){return <div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 font-semibold text-mis-navy">{value||'—'}</p></div>}
