export interface DepartmentOption { id: string; name: string; code: string; }
export type EmployeeListStatus = 'Active' | 'Inactive' | 'OnLeave' | 'Suspended' | 'Terminated';
export type EmployeeOperationalRole = 'COLLECTOR' | 'ADMIN' | 'SUPERVISOR' | 'OFFICE';
export interface EmployeeOrganizationAssignment { id: string; code: string; nameArabic: string; nameEnglish: string; organizationType: string; }
export interface EmployeeListItem { id: string; employeeNumber: string; fullName: string; fullNameArabic?: string | null; fullNameEnglish?: string | null; departmentId: string; departmentName: string; departmentCode: string; positionId?: string | null; positionName?: string | null; operationalRole?: EmployeeOperationalRole | null; isActive: boolean; status?: EmployeeListStatus; isArchived?: boolean; organizations?: EmployeeOrganizationAssignment[]; nationalId?: string | null; mobileNumber?: string | null; workStartDate?: string | null; }
export interface EmployeeDetails extends EmployeeListItem { fullNameArabic: string | null; fullNameEnglish: string | null; nationalId: string | null; mobileNumber: string | null; workStartDate: string | null; fingerprintEnrollmentDate: string | null; dateOfBirth: string | null; address: string | null; workEndDate: string | null; createdAt: string; updatedAt: string | null; archivedAt: string | null; archiveReason: string | null; basicSalary?: number | null; allowances?: number | null; workNumber?: string | null; packageType?: string | null; }
export interface PagedEmployees { items: EmployeeListItem[]; totalCount: number; page: number; pageSize: number; totalPages: number; }
export interface SaveEmployeeRequest { employeeNumber: string; fullName: string; fullNameArabic: string | null; fullNameEnglish: string | null; nationalId: string; mobileNumber: string | null; departmentId: string; organizationIds: string[]; positionId: string; operationalRole: EmployeeOperationalRole | ''; workStartDate: string; fingerprintEnrollmentDate: string | null; dateOfBirth: string | null; address: string | null; workEndDate: string | null; isActive: boolean; gender?: 'Male' | 'Female' | null; basicSalary?: number | null; allowances?: number | null; workNumber?: string | null; packageType?: string | null; }
export interface EmployeeIdentityAvailability { employeeNumberTaken: boolean; nationalIdTaken: boolean; }
