export interface FinanceDashboard { grossCollectionsToday: number; grossCollectionsMonthToDate: number; clientMoneyLiability: number; revenueMonthToDate: number; expensesMonthToDate: number; netOperatingResult: number; pendingJournals: number; failedEvents: number; openPeriods: number; baseCurrencyCode: string }
export interface FinanceAccount { id: string; code: string; nameArabic: string; nameEnglish: string; accountType: string; normalBalance: string; postingAllowed: boolean; controlAccountType?: string; balance: number }
export interface AccountingPeriod { id: string; year: number; periodNumber: number; name: string; startDate: string; endDate: string; status: string; closedAt?: string; closeReason?: string }
export interface JournalListItem { id: string; journalNumber?: string; entryType: string; postingDate: string; description: string; totalDebit: number; totalCredit: number; status: string; createdAt: string }
export interface JournalLine { id: string; lineNumber: number; accountId: string; accountCode: string; accountNameArabic: string; accountNameEnglish: string; debit: number; credit: number; baseDebit: number; baseCredit: number; exchangeRate: number; description: string; clientId?: string; collectorId?: string; branchId?: string }
export interface Journal extends JournalListItem { transactionDate: string; currencyCode: string; createdBy: string; approvedBy?: string; approvedAt?: string; postedBy?: string; postedAt?: string; reversalOfJournalId?: string; lines: JournalLine[] }
export interface FinancePagedResult<T> { items: T[]; page: number; pageSize: number; totalCount: number; totalPages: number }
export interface ManualJournalLineInput { accountId: string; debit: number; credit: number; description: string; clientId?: string; collectorId?: string; branchId?: string }
export interface CreateManualJournalInput { transactionDate: string; postingDate: string; currencyCode: string; description: string; lines: ManualJournalLineInput[] }
export interface TrialBalanceRow { accountId: string; accountCode: string; accountNameArabic: string; accountNameEnglish: string; accountType: string; debitMovement: number; creditMovement: number; balance: number }
export interface TrialBalance { asOf: string; currencyCode: string; totalDebit: number; totalCredit: number; rows: TrialBalanceRow[] }
export interface CollectionAllocation { id: string; caseId: string; caseNumber: string; lineNumber: number; amount: number; outstandingBefore: number; overdueBefore: number }
export interface CollectionFinanceListItem { paymentId: string; receiptId: string; referenceNumber: string; paymentDate: string; clientCode: string; clientNameArabic: string; clientNameEnglish: string; grossAmount: number; currencyCode: string; channel: string; status: string; collectorName: string; journalNumber: string; clearingJournalNumber?: string }
export interface CollectionFinance extends CollectionFinanceListItem { clientId: string; baseAmount: number; exchangeRate: number; destinationType: string; destinationReference?: string; collectorId?: string; journalEntryId: string; clearingJournalEntryId?: string; reversalJournalEntryId?: string; reversalJournalNumber?: string; postedAt: string; clearedAt?: string; reversedAt?: string; allocations: CollectionAllocation[] }
export interface CustodySummary { accountId: string; collectorId: string; collectorName: string; currencyCode: string; balance: number; softLimit: number; hardLimit: number; softLimitExceeded: boolean; hardLimitExceeded: boolean; oldestOutstandingDate?: string; status: string }
export interface CustodyTransaction { id: string; transactionDate: string; transactionType: string; debit: number; credit: number; runningBalance: number; sourceId: string; paymentId?: string; paymentReference?: string; journalEntryId: string; journalNumber: string }
export interface CustodyDetails { summary: CustodySummary; transactions: CustodyTransaction[] }
