using System.Globalization;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using MIS.Application.Common;
using MIS.Application.DTOs.Collections;
using MIS.Application.Interfaces;
using MIS.Domain.Constants;
using MIS.Domain.Entities;
using MIS.Infrastructure.Persistence;

namespace MIS.Infrastructure.Services;

public sealed class BankVisitService(ApplicationDbContext db, ICurrentUserContext user, ICollectionsClassificationContext classification) : IBankVisitService
{
    private static readonly string[] ActiveStatuses = [CollectionsValues.VisitStatuses.Scheduled, CollectionsValues.VisitStatuses.Assigned, CollectionsValues.VisitStatuses.Planned, CollectionsValues.VisitStatuses.InProgress, CollectionsValues.VisitStatuses.Rescheduled];
    private static readonly HashSet<string> Results = new(StringComparer.OrdinalIgnoreCase) { CollectionsValues.VisitResults.CustomerMet, CollectionsValues.VisitResults.CustomerNotAvailable, CollectionsValues.VisitResults.AddressNotFound, CollectionsValues.VisitResults.WrongAddress, CollectionsValues.VisitResults.RefusedContact, CollectionsValues.VisitResults.PromiseToPayDiscussed, CollectionsValues.VisitResults.FollowUpRequired, CollectionsValues.VisitResults.Other };
    private bool Has(string role) => user.Roles.Contains(role, StringComparer.OrdinalIgnoreCase);
    private bool Global => Has(SystemRoleNames.Admin) || Has(SystemRoleNames.CollectionsOperationsManager);
    private bool Manager => Global || Has(SystemRoleNames.CollectionsSupervisor);
    private bool Collector => Has(SystemRoleNames.CollectionsCollector);
    private BankVisitAccessDto Access() => new(Manager, Manager || Collector, Manager);

    public async Task<BankVisitSummaryDto> SummaryAsync(Guid bankId, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); var q = ScopedVisits(bankId).AsNoTracking(); var (start, end) = CairoDayRange(CairoToday());
        return new(await q.CountAsync(x => x.ScheduledAt >= start && x.ScheduledAt < end && ActiveStatuses.Contains(x.Status), token),
            await q.CountAsync(x => x.ScheduledAt >= end && ActiveStatuses.Contains(x.Status), token),
            await q.CountAsync(x => x.ScheduledAt < start && (x.Status == CollectionsValues.VisitStatuses.Scheduled || x.Status == CollectionsValues.VisitStatuses.Assigned || x.Status == CollectionsValues.VisitStatuses.Planned || x.Status == CollectionsValues.VisitStatuses.Rescheduled || x.Status == CollectionsValues.VisitStatuses.InProgress), token),
            await q.CountAsync(x => x.Status == CollectionsValues.VisitStatuses.Completed && x.CheckedOutAt >= start && x.CheckedOutAt < end, token));
    }

    public async Task<BankVisitPageDto> GetAsync(Guid bankId, BankVisitQuery request, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); ValidatePage(request.Page, request.PageSize); var q = Filter(ScopedVisits(bankId).AsNoTracking(), request); var total = await q.CountAsync(token); q = Sort(q, request.SortBy, request.SortDirection); var ar = ApiTextLocalizer.IsArabic;
        var rows = await q.Skip((request.Page - 1) * request.PageSize).Take(request.PageSize).Select(x => new BankVisitItemDto(x.Id, x.CaseId, x.Case.CaseNumber, ar ? x.Case.Customer.FullNameArabic ?? x.Case.Customer.FullNameEnglish! : x.Case.Customer.FullNameEnglish ?? x.Case.Customer.FullNameArabic!, x.ScheduledAt, x.CollectorId, x.Collector.FullName, DisplayStatus(x.Status), x.Result, x.UpdatedAt)).ToArrayAsync(token);
        return new(rows, total, request.Page, request.PageSize, total == 0 ? 0 : (int)Math.Ceiling(total / (double)request.PageSize), Access());
    }

    public async Task<BankVisitDetailsDto> GetDetailsAsync(Guid bankId, Guid visitId, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); var ar = ApiTextLocalizer.IsArabic;
        var x = await ScopedVisits(bankId).AsNoTracking().Where(v => v.Id == visitId).Select(v => new { v.Id, v.CaseId, v.Case.CaseNumber, Customer = ar ? v.Case.Customer.FullNameArabic ?? v.Case.Customer.FullNameEnglish! : v.Case.Customer.FullNameEnglish ?? v.Case.Customer.FullNameArabic!, v.Case.Customer.PrimaryPhone, Bank = ar ? v.Case.Portfolio.Organization.NameArabic : v.Case.Portfolio.Organization.NameEnglish, v.Address, v.ScheduledAt, v.CollectorId, Collector = v.Collector.FullName, v.Status, v.Result, v.Purpose, v.Notes, Creator = v.CreatedBy.FullName, v.CreatedAt, v.UpdatedAt, v.CheckedOutAt }).SingleOrDefaultAsync(token) ?? throw new HrNotFoundException("Visit was not found for this bank or user scope.");
        return new(x.Id, x.CaseId, x.CaseNumber, x.Customer, x.PrimaryPhone, x.Bank, x.Address, x.ScheduledAt, x.CollectorId, x.Collector, DisplayStatus(x.Status), x.Result, x.Purpose, x.Notes, x.Creator, x.CreatedAt, x.UpdatedAt, x.CheckedOutAt, Access());
    }

    public async Task<IReadOnlyCollection<BankVisitCaseLookupDto>> CasesAsync(Guid bankId, string? search, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); var q = ScopedCases(bankId).AsNoTracking();
        if (!string.IsNullOrWhiteSpace(search)) { if (search.Length > 160) throw new HrValidationException("Search cannot exceed 160 characters."); var t = search.Trim().ToLower(); q = q.Where(x => x.CaseNumber.ToLower().Contains(t) || (x.Customer.FullNameArabic != null && x.Customer.FullNameArabic.ToLower().Contains(t)) || (x.Customer.FullNameEnglish != null && x.Customer.FullNameEnglish.ToLower().Contains(t)) || (x.Customer.PrimaryPhone != null && x.Customer.PrimaryPhone.Contains(t))); }
        var ar = ApiTextLocalizer.IsArabic; return await q.OrderBy(x => x.CaseNumber).Take(30).Select(x => new BankVisitCaseLookupDto(x.Id, x.CaseNumber, ar ? x.Customer.FullNameArabic ?? x.Customer.FullNameEnglish! : x.Customer.FullNameEnglish ?? x.Customer.FullNameArabic!, x.Customer.PrimaryPhone, ar ? x.Customer.AddressArabic ?? x.Customer.AddressEnglish : x.Customer.AddressEnglish ?? x.Customer.AddressArabic, x.Customer.Governorate, x.Customer.Area, x.AssignedCollectorId, x.AssignedCollector == null ? null : x.AssignedCollector.FullName)).ToArrayAsync(token);
    }

    public async Task<IReadOnlyCollection<BankPortfolioCollectorDto>> CollectorsAsync(Guid bankId, CancellationToken token)
    { await RequireBankAsync(bankId, token); if (!Manager) return []; return await AuthorizedCollectors(bankId).AsNoTracking().OrderBy(x => x.FullName).Select(x => new BankPortfolioCollectorDto(x.Id, x.FullName)).ToArrayAsync(token); }

    public async Task<BankVisitDetailsDto> CreateAsync(Guid bankId, CreateBankVisitRequest request, CancellationToken token)
    {
        if (!Manager && !Collector) throw new HrForbiddenException("You do not have permission to create visits."); await RequireBankAsync(bankId, token); ValidateSchedule(request.ScheduledAt); ValidateLengths(request.Purpose, request.Notes);
        var item = await ScopedCases(bankId).SingleOrDefaultAsync(x => x.Id == request.CaseId, token) ?? throw new HrNotFoundException("Portfolio case was not found for this bank or user scope.");
        Guid collectorId;
        if (Manager) { collectorId = request.AssignedCollectorId ?? item.AssignedCollectorId ?? throw new HrConflictException("Select an authorized collector for this visit."); if (!await AuthorizedCollectors(bankId).AnyAsync(x => x.Id == collectorId, token)) throw new HrForbiddenException("The selected collector is outside your authorized scope."); }
        else { if (request.AssignedCollectorId.HasValue && request.AssignedCollectorId != user.UserId) throw new HrForbiddenException("Collectors can only create visits for themselves."); if (item.AssignedCollectorId != user.UserId) throw new HrForbiddenException("The case is not assigned to the authenticated collector."); collectorId = user.UserId; }
        var caseAddress = ApiTextLocalizer.IsArabic ? item.Customer.AddressArabic ?? item.Customer.AddressEnglish : item.Customer.AddressEnglish ?? item.Customer.AddressArabic; if (!Manager && Clean(request.Address) is not null && !string.Equals(Clean(request.Address), Clean(caseAddress), StringComparison.Ordinal)) throw new HrForbiddenException("Collectors cannot correct the case address while creating a visit."); var address = Manager ? Clean(request.Address) ?? Clean(caseAddress) : Clean(caseAddress); if (string.IsNullOrWhiteSpace(address)) throw new HrValidationException("The selected case has no visit address.");
        var now = DateTimeOffset.UtcNow; var visit = new FieldVisit(item.Id, collectorId, request.ScheduledAt, address, item.Customer.Governorate, item.Customer.Area, user.UserId, now, request.Purpose, request.Notes); db.CollectionFieldVisits.Add(visit);
        AddActivity(visit, "SCHEDULED", $"Field visit scheduled for {FormatSchedule(visit.ScheduledAt)}. Visit ID: {visit.Id}.", now, null); AddAudit("VisitCreated", visit, null, new { visit.CaseId, visit.CollectorId, visit.ScheduledAt, visit.Status }); await db.SaveChangesAsync(token); return await GetDetailsAsync(bankId, visit.Id, token);
    }

    public async Task<BankVisitDetailsDto> CompleteAsync(Guid bankId, Guid visitId, CompleteBankVisitRequest request, CancellationToken token)
    {
        if (!Manager && !Collector) throw new HrForbiddenException("You do not have permission to complete visits."); await RequireBankAsync(bankId, token); var result = NormalizeResult(request.Result); ValidateLengths(null, request.Notes); if (request.NextFollowUpAt.HasValue && request.NextFollowUpAt.Value <= DateTimeOffset.UtcNow) throw new HrValidationException("Next follow-up must be in the future.");
        var visit = await ScopedVisits(bankId).Include(x => x.Case).SingleOrDefaultAsync(x => x.Id == visitId, token) ?? throw new HrNotFoundException("Visit was not found for this bank or user scope."); var before = new { visit.Status, visit.Result, visit.Notes }; var now = DateTimeOffset.UtcNow;
        Try(() => visit.Complete(result, request.Notes, now)); if (request.NextFollowUpAt.HasValue) visit.Case.ScheduleNextFollowUp(request.NextFollowUpAt, now);
        AddActivity(visit, "COMPLETED", $"Visit completed. Result: {result.Replace('_', ' ')}.{NoteSuffix(request.Notes)} Visit ID: {visit.Id}.", now, request.NextFollowUpAt); AddAudit("VisitCompleted", visit, before, new { visit.Status, visit.Result, visit.Notes, request.NextFollowUpAt }); await db.SaveChangesAsync(token); return await GetDetailsAsync(bankId, visit.Id, token);
    }

    public async Task<BankVisitDetailsDto> RescheduleAsync(Guid bankId, Guid visitId, RescheduleBankVisitRequest request, CancellationToken token)
    {
        RequireManager(); await RequireBankAsync(bankId, token); ValidateSchedule(request.ScheduledAt); var visit = await ScopedVisits(bankId).SingleOrDefaultAsync(x => x.Id == visitId, token) ?? throw new HrNotFoundException("Visit was not found for this bank or user scope."); var old = visit.ScheduledAt; var now = DateTimeOffset.UtcNow; Try(() => visit.Reschedule(request.ScheduledAt, now)); AddActivity(visit, "RESCHEDULED", $"Visit rescheduled from {FormatSchedule(old)} to {FormatSchedule(request.ScheduledAt)}. Visit ID: {visit.Id}.", now, null); AddAudit("VisitRescheduled", visit, new { ScheduledAt = old }, new { visit.ScheduledAt }); await db.SaveChangesAsync(token); return await GetDetailsAsync(bankId, visit.Id, token);
    }

    public async Task<BankVisitDetailsDto> ReassignAsync(Guid bankId, Guid visitId, ReassignBankVisitRequest request, CancellationToken token)
    {
        RequireManager(); await RequireBankAsync(bankId, token); if (!await AuthorizedCollectors(bankId).AnyAsync(x => x.Id == request.CollectorId, token)) throw new HrForbiddenException("The selected collector is outside your authorized scope."); var visit = await ScopedVisits(bankId).Include(x => x.Collector).SingleOrDefaultAsync(x => x.Id == visitId, token) ?? throw new HrNotFoundException("Visit was not found for this bank or user scope."); var oldId = visit.CollectorId; var oldName = visit.Collector.FullName; var target = await db.Users.Where(x => x.Id == request.CollectorId).Select(x => x.FullName).SingleAsync(token); var now = DateTimeOffset.UtcNow; Try(() => visit.Reassign(request.CollectorId, now)); AddActivity(visit, "REASSIGNED", $"Visit reassigned from {oldName} to {target}. Visit ID: {visit.Id}.", now, null); AddAudit("VisitReassigned", visit, new { CollectorId = oldId }, new { visit.CollectorId }); await db.SaveChangesAsync(token); return await GetDetailsAsync(bankId, visit.Id, token);
    }

    public async Task<BankVisitDetailsDto> CancelAsync(Guid bankId, Guid visitId, CancelBankVisitRequest request, CancellationToken token)
    { RequireManager(); await RequireBankAsync(bankId, token); ValidateLengths(null, request.Notes); var visit = await ScopedVisits(bankId).SingleOrDefaultAsync(x => x.Id == visitId, token) ?? throw new HrNotFoundException("Visit was not found for this bank or user scope."); var before = visit.Status; var now = DateTimeOffset.UtcNow; Try(() => visit.Cancel(request.Notes, now)); AddActivity(visit, "CANCELLED", $"Visit cancelled.{NoteSuffix(request.Notes)} Visit ID: {visit.Id}.", now, null); AddAudit("VisitCancelled", visit, new { Status = before }, new { visit.Status, visit.Notes }); await db.SaveChangesAsync(token); return await GetDetailsAsync(bankId, visit.Id, token); }

    public async Task<BankVisitDetailsDto> ChangeStatusAsync(Guid bankId, Guid visitId, ChangeBankVisitStatusRequest request, CancellationToken token)
    {
        if (!Manager && !Collector) throw new HrForbiddenException("You do not have permission to update visits."); await RequireBankAsync(bankId, token); var status = request.Status.Trim().ToUpperInvariant(); if (status is not (CollectionsValues.VisitStatuses.InProgress or CollectionsValues.VisitStatuses.Missed)) throw new HrValidationException("Visit status can only be changed to In Progress or Missed here."); if (status == CollectionsValues.VisitStatuses.Missed && !Manager) throw new HrForbiddenException("Only a team leader or manager can mark a visit missed."); var visit = await ScopedVisits(bankId).SingleOrDefaultAsync(x => x.Id == visitId, token) ?? throw new HrNotFoundException("Visit was not found for this bank or user scope."); var before = visit.Status; var now = DateTimeOffset.UtcNow; Try(() => { if (status == CollectionsValues.VisitStatuses.InProgress) visit.Start(now); else visit.MarkMissed(request.Notes, now); }); if (status == CollectionsValues.VisitStatuses.Missed) AddActivity(visit, "MISSED", $"Visit marked missed.{NoteSuffix(request.Notes)} Visit ID: {visit.Id}.", now, null); AddAudit(status == CollectionsValues.VisitStatuses.Missed ? "VisitMissed" : "VisitStarted", visit, new { Status = before }, new { visit.Status, visit.Notes }); await db.SaveChangesAsync(token); return await GetDetailsAsync(bankId, visit.Id, token);
    }

    private IQueryable<CollectionCase> ScopedCases(Guid bankId) => ScopedCasesCore(bankId).Apply(classification);
    private IQueryable<CollectionCase> ScopedCasesCore(Guid bankId) { var q = db.CollectionCases.Where(x => x.Portfolio.OrganizationId == bankId && !x.IsArchived); if (Global) return q; if (Manager) return q.Where(x => (x.AssignedTeam != null && x.AssignedTeam.SupervisorId == user.UserId) || (x.AssignedTeamId == null && db.CollectionUserAccess.Any(a => a.UserId == user.UserId && a.OrganizationId == bankId && (a.PortfolioId == null || a.PortfolioId == x.PortfolioId)))); if (Collector) return q.Where(x => x.AssignedCollectorId == user.UserId); return q.Where(_ => false); }
    private IQueryable<FieldVisit> ScopedVisits(Guid bankId) { if (Collector && !Manager) return db.CollectionFieldVisits.Where(x => x.Case.Portfolio.OrganizationId == bankId && x.CollectorId == user.UserId); var cases = ScopedCases(bankId); return db.CollectionFieldVisits.Where(x => cases.Any(c => c.Id == x.CaseId)); }
    private IQueryable<User> AuthorizedCollectors(Guid bankId) => db.Users.EligibleCollectors().ForSupervisorScope(db, user.UserId, Global);
    private async Task RequireBankAsync(Guid bankId, CancellationToken token) { var exists = await db.CollectionClientOrganizations.AsNoTracking().AnyAsync(x => x.Id == bankId && x.IsActive && (x.OrganizationType == CollectionsValues.OrganizationTypes.Bank || x.OrganizationType == CollectionsValues.OrganizationTypes.ConsumerFinance), token); var hasVisit = Collector && !Manager && await db.CollectionFieldVisits.AnyAsync(x => x.Case.Portfolio.OrganizationId == bankId && x.CollectorId == user.UserId, token); if (!exists || (!Global && !await db.CollectionUserAccess.AnyAsync(x => x.UserId == user.UserId && x.OrganizationId == bankId, token) && !await ScopedCases(bankId).AnyAsync(token) && !hasVisit)) throw new HrNotFoundException("Organization was not found or is outside your authorized scope."); }
    private static IQueryable<FieldVisit> Filter(IQueryable<FieldVisit> q, BankVisitQuery r) { var today = CairoToday(); var (start, end) = CairoDayRange(today); var view = string.IsNullOrWhiteSpace(r.View) ? "TODAY" : r.View.Trim().ToUpperInvariant(); q = view switch { "TODAY" => q.Where(x => x.ScheduledAt >= start && x.ScheduledAt < end && ActiveStatuses.Contains(x.Status)), "UPCOMING" => q.Where(x => x.ScheduledAt >= end && ActiveStatuses.Contains(x.Status)), "OVERDUE" => q.Where(x => x.ScheduledAt < start && (x.Status == CollectionsValues.VisitStatuses.Scheduled || x.Status == CollectionsValues.VisitStatuses.Assigned || x.Status == CollectionsValues.VisitStatuses.Planned || x.Status == CollectionsValues.VisitStatuses.Rescheduled || x.Status == CollectionsValues.VisitStatuses.InProgress)), "COMPLETED" => q.Where(x => x.Status == CollectionsValues.VisitStatuses.Completed), "ALL" => q, _ => throw new HrValidationException("Visit view is invalid.") }; if (!string.IsNullOrWhiteSpace(r.Search)) { if (r.Search.Length > 160) throw new HrValidationException("Search cannot exceed 160 characters."); var t = r.Search.Trim().ToLower(); q = q.Where(x => x.Case.CaseNumber.ToLower().Contains(t) || (x.Case.Customer.FullNameArabic != null && x.Case.Customer.FullNameArabic.ToLower().Contains(t)) || (x.Case.Customer.FullNameEnglish != null && x.Case.Customer.FullNameEnglish.ToLower().Contains(t)) || (x.Case.Customer.PrimaryPhone != null && x.Case.Customer.PrimaryPhone.Contains(t)) || x.Address.ToLower().Contains(t)); } if (!string.IsNullOrWhiteSpace(r.Status)) { var s = NormalizeStatus(r.Status); q = s == CollectionsValues.VisitStatuses.Scheduled ? q.Where(x => x.Status == s || x.Status == CollectionsValues.VisitStatuses.Assigned || x.Status == CollectionsValues.VisitStatuses.Planned || x.Status == CollectionsValues.VisitStatuses.Rescheduled) : q.Where(x => x.Status == s); } if (r.VisitDate.HasValue) { var (s, e) = CairoDayRange(r.VisitDate.Value); q = q.Where(x => x.ScheduledAt >= s && x.ScheduledAt < e); } if (!string.IsNullOrWhiteSpace(r.Result)) { var result = NormalizeResult(r.Result); q = q.Where(x => x.Result == result); } if (r.CollectorId.HasValue) q = q.Where(x => x.CollectorId == r.CollectorId); return q; }
    private static IQueryable<FieldVisit> Sort(IQueryable<FieldVisit> q, string? field, string? direction) { var d = direction?.Equals("desc", StringComparison.OrdinalIgnoreCase) == true; return field?.Trim().ToLowerInvariant() switch { "customer" => d ? q.OrderByDescending(x => x.Case.Customer.FullNameEnglish ?? x.Case.Customer.FullNameArabic) : q.OrderBy(x => x.Case.Customer.FullNameEnglish ?? x.Case.Customer.FullNameArabic), "status" => d ? q.OrderByDescending(x => x.Status) : q.OrderBy(x => x.Status), "updated" => d ? q.OrderByDescending(x => x.UpdatedAt) : q.OrderBy(x => x.UpdatedAt), "date" or null or "" => d ? q.OrderByDescending(x => x.ScheduledAt) : q.OrderBy(x => x.ScheduledAt), _ => throw new HrValidationException("Visit sort field is invalid.") }; }
    private void AddActivity(FieldVisit visit, string outcome, string notes, DateTimeOffset now, DateTimeOffset? next) => db.CollectionActivities.Add(new CollectionActivity(visit.CaseId, CollectionsValues.ActivityTypes.Visit, outcome, notes, "FIELD", user.UserId, now, next));
    private void AddAudit(string action, FieldVisit visit, object? before, object after) => db.CollectionAuditLogs.Add(new CollectionAuditLog(user.UserId, action, nameof(FieldVisit), visit.Id, visit.CaseId, before == null ? null : JsonSerializer.Serialize(before), JsonSerializer.Serialize(after), "BANK_WORKSPACE", DateTimeOffset.UtcNow));
    private void RequireManager() { if (!Manager) throw new HrForbiddenException("Only an authorized team leader or manager can perform this visit action."); }
    private static void ValidatePage(int page, int size) { if (page < 1 || size is not (20 or 50 or 100)) throw new HrValidationException("Page size must be 20, 50, or 100."); }
    private static void ValidateSchedule(DateTimeOffset value) { if (value == default) throw new HrValidationException("Visit date and time are required."); }
    private static void ValidateLengths(string? purpose, string? notes) { if (purpose?.Length > 500) throw new HrValidationException("Purpose cannot exceed 500 characters."); if (notes?.Length > 3000) throw new HrValidationException("Notes cannot exceed 3000 characters."); }
    private static string NormalizeResult(string value) { var result = value.Trim().ToUpperInvariant(); if (!Results.Contains(result)) throw new HrValidationException("Visit result is invalid."); return result; }
    private static string NormalizeStatus(string value) => value.Trim().ToUpperInvariant() switch { "SCHEDULED" or "ASSIGNED" or "PLANNED" or "RESCHEDULED" => CollectionsValues.VisitStatuses.Scheduled, "IN_PROGRESS" => CollectionsValues.VisitStatuses.InProgress, "COMPLETED" => CollectionsValues.VisitStatuses.Completed, "CANCELLED" => CollectionsValues.VisitStatuses.Cancelled, "MISSED" or "FAILED" => CollectionsValues.VisitStatuses.Missed, _ => throw new HrValidationException("Visit status is invalid.") };
    private static string DisplayStatus(string value) => value switch { CollectionsValues.VisitStatuses.Assigned or CollectionsValues.VisitStatuses.Planned or CollectionsValues.VisitStatuses.Rescheduled => CollectionsValues.VisitStatuses.Scheduled, CollectionsValues.VisitStatuses.Failed => CollectionsValues.VisitStatuses.Missed, _ => value };
    private static string FormatSchedule(DateTimeOffset value) => value.ToString("dd/MM/yyyy 'at' hh:mm tt", CultureInfo.InvariantCulture);
    private static string NoteSuffix(string? notes) => string.IsNullOrWhiteSpace(notes) ? string.Empty : $" Notes: {notes.Trim()}.";
    private static string? Clean(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim();
    private static void Try(Action action) { try { action(); } catch (InvalidOperationException ex) { throw new HrConflictException(ex.Message); } catch (ArgumentException ex) { throw new HrValidationException(ex.Message); } }
    private static DateOnly CairoToday() { var zone = TimeZoneInfo.FindSystemTimeZoneById("Africa/Cairo"); return DateOnly.FromDateTime(TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow, zone).DateTime); }
    private static (DateTimeOffset Start, DateTimeOffset End) CairoDayRange(DateOnly date) { var zone = TimeZoneInfo.FindSystemTimeZoneById("Africa/Cairo"); var start = new DateTime(date.Year, date.Month, date.Day, 0, 0, 0, DateTimeKind.Unspecified); return (new DateTimeOffset(TimeZoneInfo.ConvertTimeToUtc(start, zone)), new DateTimeOffset(TimeZoneInfo.ConvertTimeToUtc(start.AddDays(1), zone))); }
}
