using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using MIS.Application.Common;
using MIS.Application.DTOs.Collections;
using MIS.Application.Interfaces;
using MIS.Domain.Constants;
using MIS.Domain.Entities;
using MIS.Infrastructure.Persistence;

namespace MIS.Infrastructure.Services;

public sealed class BankComplaintService(ApplicationDbContext db, ICurrentUserContext user, IHrFileStorage files, ICollectionsClassificationContext classification) : IBankComplaintService
{
    private const long MaximumAttachmentBytes = 10 * 1024 * 1024;
    private static readonly string[] FinalStatuses = [CollectionsValues.ComplaintStatuses.Resolved, CollectionsValues.ComplaintStatuses.Closed, CollectionsValues.ComplaintStatuses.Rejected];
    private static readonly string[] Types = ["PAYMENT_ISSUE", "COLLECTOR_CONDUCT", "INCORRECT_INFORMATION", "COMMUNICATION_ISSUE", "VISIT_COMPLAINT", "ACCOUNT_DISPUTE", "SERVICE_COMPLAINT", "OTHER"];
    private bool Has(string role) => user.Roles.Contains(role, StringComparer.OrdinalIgnoreCase);
    private bool Global => Has(SystemRoleNames.Admin) || Has(SystemRoleNames.CollectionsOperationsManager);
    private bool Manager => Global || Has(SystemRoleNames.CollectionsSupervisor);
    private bool Collector => Has(SystemRoleNames.CollectionsCollector);
    private BankComplaintAccessDto Access() => new(Manager, Manager || Collector, Manager, Manager, Manager || Collector, Manager || Collector);

    public async Task<BankComplaintPageDto> GetAsync(Guid bankId, BankComplaintQuery request, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); ValidatePage(request.Page, request.PageSize); var now = DateTimeOffset.UtcNow; var zone = await BusinessZoneAsync(token); var q = Filter(ScopedComplaints(bankId).AsNoTracking(), request, now, zone); var total = await q.CountAsync(token); q = Sort(q, request.SortBy, request.SortDirection); var ar = ApiTextLocalizer.IsArabic;
        var rows = await q.Skip((request.Page - 1) * request.PageSize).Take(request.PageSize).Select(x => new BankComplaintItemDto(x.Id, x.Reference, x.CaseId, x.Case.CaseNumber, ar ? x.Case.Customer.FullNameArabic ?? x.Case.Customer.FullNameEnglish! : x.Case.Customer.FullNameEnglish ?? x.Case.Customer.FullNameArabic!, x.Category, x.Severity, DisplayStatus(x.Status), x.OwnerId, x.Owner == null ? null : x.Owner.FullName, x.ReceivedAt, x.SlaDueAt, x.UpdatedAt, x.SlaDueAt != null && x.SlaDueAt < now && !FinalStatuses.Contains(x.Status))).ToArrayAsync(token);
        return new(rows, total, request.Page, request.PageSize, total == 0 ? 0 : (int)Math.Ceiling(total / (double)request.PageSize), Access());
    }

    public async Task<BankComplaintSummaryDto> SummaryAsync(Guid bankId, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); var q = ScopedComplaints(bankId).AsNoTracking(); var now = DateTimeOffset.UtcNow; var (start, end) = await TodayRangeAsync(token);
        return new(await q.CountAsync(x => x.Status == CollectionsValues.ComplaintStatuses.Open || x.Status == CollectionsValues.ComplaintStatuses.New, token), await q.CountAsync(x => x.Status == CollectionsValues.ComplaintStatuses.InProgress, token), await q.CountAsync(x => !FinalStatuses.Contains(x.Status) && (x.Severity == CollectionsValues.ComplaintPriorities.High || x.Severity == CollectionsValues.ComplaintPriorities.Critical), token), await q.CountAsync(x => x.SlaDueAt != null && x.SlaDueAt < now && !FinalStatuses.Contains(x.Status), token), await q.CountAsync(x => x.ResolvedAt >= start && x.ResolvedAt < end, token));
    }

    public async Task<BankComplaintDetailsDto> DetailsAsync(Guid bankId, Guid complaintId, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); var ar = ApiTextLocalizer.IsArabic; var now = DateTimeOffset.UtcNow;
        var x = await ScopedComplaints(bankId).AsNoTracking().Where(c => c.Id == complaintId).Select(c => new { c.Id, c.Reference, c.CaseId, c.Case.CaseNumber, Customer = ar ? c.Case.Customer.FullNameArabic ?? c.Case.Customer.FullNameEnglish! : c.Case.Customer.FullNameEnglish ?? c.Case.Customer.FullNameArabic!, c.Case.Customer.PrimaryPhone, Bank = ar ? c.Case.Portfolio.Organization.NameArabic : c.Case.Portfolio.Organization.NameEnglish, c.Category, c.Severity, c.Status, c.Description, c.OwnerId, Owner = c.Owner == null ? null : c.Owner.FullName, c.CreatedById, Creator = c.CreatedBy.FullName, c.ReceivedAt, c.SlaDueAt, c.UpdatedAt, c.Resolution, c.ResolvedById, Resolver = c.ResolvedBy == null ? null : c.ResolvedBy.FullName, c.ResolvedAt, c.ClosedAt, c.RejectionReason }).SingleOrDefaultAsync(token) ?? throw new HrNotFoundException("Complaint was not found for this bank or user scope.");
        var notes = await db.CollectionComplaintNotes.AsNoTracking().Where(n => n.ComplaintId == complaintId).OrderByDescending(n => n.CreatedAt).Select(n => new BankComplaintNoteDto(n.Id, n.Text, n.CreatedById, n.CreatedBy.FullName, n.CreatedAt)).ToArrayAsync(token);
        var attachments = await db.CollectionAttachments.AsNoTracking().Where(a => a.ComplaintId == complaintId).OrderByDescending(a => a.UploadedAt).Select(a => new BankComplaintAttachmentDto(a.Id, a.OriginalFileName, a.ContentType, a.FileSize, a.UploadedById, a.UploadedBy.FullName, a.UploadedAt)).ToArrayAsync(token);
        var history = await db.CollectionAuditLogs.AsNoTracking().Where(a => a.EntityType == nameof(CollectionComplaint) && a.EntityId == complaintId).OrderByDescending(a => a.OccurredAt).Select(a => new BankComplaintHistoryDto(a.Id, a.Action, a.BeforeJson, a.AfterJson, a.UserId, a.User == null ? "System" : a.User.FullName, a.OccurredAt)).ToArrayAsync(token);
        return new(x.Id, x.Reference, x.CaseId, x.CaseNumber, x.Customer, x.PrimaryPhone, x.Bank, x.Category, x.Severity, DisplayStatus(x.Status), x.Description, x.OwnerId, x.Owner, x.CreatedById, x.Creator, x.ReceivedAt, x.SlaDueAt, x.UpdatedAt, x.Resolution, x.ResolvedById, x.Resolver, x.ResolvedAt, x.ClosedAt, x.RejectionReason, x.SlaDueAt != null && x.SlaDueAt < now && !FinalStatuses.Contains(x.Status), notes, attachments, history, Access());
    }

    public async Task<IReadOnlyCollection<BankComplaintCaseDto>> CasesAsync(Guid bankId, string? search, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); var q = ScopedCases(bankId).AsNoTracking(); if (!string.IsNullOrWhiteSpace(search)) { if (search.Length > 160) throw new HrValidationException("Search cannot exceed 160 characters."); var t = search.Trim().ToLower(); var hasId=Guid.TryParse(t,out var requestedId); q = q.Where(x => (hasId && x.Id == requestedId) || x.CaseNumber.ToLower().Contains(t) || (x.Customer.FullNameArabic != null && x.Customer.FullNameArabic.ToLower().Contains(t)) || (x.Customer.FullNameEnglish != null && x.Customer.FullNameEnglish.ToLower().Contains(t)) || (x.Customer.PrimaryPhone != null && x.Customer.PrimaryPhone.Contains(t))); }
        var ar = ApiTextLocalizer.IsArabic; return await q.OrderBy(x => x.CaseNumber).Take(30).Select(x => new BankComplaintCaseDto(x.Id, x.CaseNumber, ar ? x.Customer.FullNameArabic ?? x.Customer.FullNameEnglish! : x.Customer.FullNameEnglish ?? x.Customer.FullNameArabic!, x.Customer.PrimaryPhone)).ToArrayAsync(token);
    }

    public async Task<IReadOnlyCollection<BankComplaintEmployeeDto>> EmployeesAsync(Guid bankId, CancellationToken token) { await RequireManagerAsync(bankId, token); return await AuthorizedEmployees(bankId).AsNoTracking().OrderBy(x => x.FullName).Select(x => new BankComplaintEmployeeDto(x.Id, x.FullName)).ToArrayAsync(token); }

    public async Task<BankComplaintDetailsDto> CreateAsync(Guid bankId, CreateBankComplaintRequest request, CancellationToken token)
    {
        if (!Manager && !Collector) throw new HrForbiddenException("You do not have permission to create complaints."); await RequireBankAsync(bankId, token); var item = await ScopedCases(bankId).SingleOrDefaultAsync(x => x.Id == request.CaseId, token) ?? throw new HrNotFoundException("Case was not found for this bank or user scope."); var type = NormalizeType(request.Type); var priority = NormalizePriority(request.Priority); ValidateDescription(request.Description); if (request.DueAt.HasValue && request.DueAt <= DateTimeOffset.UtcNow) throw new HrValidationException("Due date must be in the future.");
        Guid? ownerId = null; if (Collector && !Manager) { if (item.AssignedCollectorId != user.UserId) throw new HrForbiddenException("Collectors can create complaints only for their assigned cases."); ownerId = user.UserId; } else if (request.AssignedToId.HasValue) { await EnsureAuthorizedEmployee(bankId, request.AssignedToId.Value, token); ownerId = request.AssignedToId; }
        var now = DateTimeOffset.UtcNow; var id = Guid.NewGuid(); var reference = $"CMP-{now.Year}-{id:N}"[..17].ToUpperInvariant(); var complaint = new CollectionComplaint(item.Id, reference, "BANK_WORKSPACE", type, priority, request.Description, now, request.DueAt, ownerId, user.UserId, now, id); db.CollectionComplaints.Add(complaint); if (!string.IsNullOrWhiteSpace(request.Note)) db.CollectionComplaintNotes.Add(new CollectionComplaintNote(complaint.Id, request.Note, user.UserId, now)); AddActivity(complaint, "CREATED", $"Complaint {reference} created — {type.Replace('_', ' ')}.", now); AddAudit("ComplaintCreated", complaint, null, new { complaint.Reference, complaint.Category, complaint.Severity, complaint.Status, complaint.OwnerId, complaint.SlaDueAt }); await db.SaveChangesAsync(token); return await DetailsAsync(bankId, complaint.Id, token);
    }

    public async Task<BankComplaintDetailsDto> AssignAsync(Guid bankId, Guid complaintId, AssignBankComplaintRequest request, CancellationToken token)
    {
        await RequireManagerAsync(bankId, token); await EnsureAuthorizedEmployee(bankId, request.AssignedToId, token); var complaint = await TrackedAsync(bankId, complaintId, token); EnsureCurrent(complaint, request.ExpectedUpdatedAt); var oldId = complaint.OwnerId; var oldName = oldId.HasValue ? await db.Users.Where(x => x.Id == oldId).Select(x => x.FullName).SingleAsync(token) : "Unassigned"; var target = await db.Users.Where(x => x.Id == request.AssignedToId).Select(x => x.FullName).SingleAsync(token); var now = DateTimeOffset.UtcNow; Try(() => complaint.Assign(request.AssignedToId, now)); AddActivity(complaint, oldId.HasValue ? "REASSIGNED" : "ASSIGNED", $"Complaint {complaint.Reference} assigned from {oldName} to {target}.", now); AddAudit(oldId.HasValue ? "ComplaintReassigned" : "ComplaintAssigned", complaint, new { OwnerId = oldId, Owner = oldName }, new { complaint.OwnerId, Owner = target, request.Reason }); await db.SaveChangesAsync(token); return await DetailsAsync(bankId, complaint.Id, token);
    }

    public async Task<BankComplaintDetailsDto> ChangePriorityAsync(Guid bankId, Guid complaintId, ChangeBankComplaintPriorityRequest request, CancellationToken token) { await RequireManagerAsync(bankId, token); var complaint = await TrackedAsync(bankId, complaintId, token); EnsureCurrent(complaint, request.ExpectedUpdatedAt); var before = complaint.Severity; var now = DateTimeOffset.UtcNow; Try(() => complaint.ChangePriority(NormalizePriority(request.Priority), now)); AddAudit("ComplaintPriorityChanged", complaint, new { Priority = before }, new { Priority = complaint.Severity }); await db.SaveChangesAsync(token); return await DetailsAsync(bankId, complaint.Id, token); }
    public async Task<BankComplaintDetailsDto> StartAsync(Guid bankId, Guid complaintId, ComplaintTransitionRequest request, CancellationToken token) { var complaint = await TrackedAsync(bankId, complaintId, token); EnsureOwnerOrManager(complaint); EnsureCurrent(complaint, request.ExpectedUpdatedAt); var before = complaint.Status; var now = DateTimeOffset.UtcNow; Try(() => complaint.Start(now)); AddAudit("ComplaintStarted", complaint, new { Status = before }, new { complaint.Status }); await db.SaveChangesAsync(token); return await DetailsAsync(bankId, complaint.Id, token); }
    public async Task<BankComplaintDetailsDto> AddNoteAsync(Guid bankId, Guid complaintId, AddBankComplaintNoteRequest request, CancellationToken token) { if (string.IsNullOrWhiteSpace(request.Text)) throw new HrValidationException("Note text is required."); var complaint = await TrackedAsync(bankId, complaintId, token); EnsureOwnerOrManager(complaint, allowUnassignedCollector: true); var now = DateTimeOffset.UtcNow; var note = new CollectionComplaintNote(complaint.Id, request.Text, user.UserId, now); db.CollectionComplaintNotes.Add(note); AddAudit("ComplaintNoteAdded", complaint, null, new { NoteId = note.Id }); await db.SaveChangesAsync(token); return await DetailsAsync(bankId, complaint.Id, token); }
    public async Task<BankComplaintDetailsDto> ResolveAsync(Guid bankId, Guid complaintId, ResolveBankComplaintRequest request, CancellationToken token) { var complaint = await TrackedAsync(bankId, complaintId, token); EnsureOwnerOrManager(complaint); EnsureCurrent(complaint, request.ExpectedUpdatedAt); var now = DateTimeOffset.UtcNow; Try(() => complaint.Resolve(request.Resolution, user.UserId, now)); if (!string.IsNullOrWhiteSpace(request.Notes)) db.CollectionComplaintNotes.Add(new CollectionComplaintNote(complaint.Id, request.Notes, user.UserId, now)); AddActivity(complaint, "RESOLVED", $"Complaint {complaint.Reference} resolved. Resolution: {SafeContext(request.Resolution)}", now); AddAudit("ComplaintResolved", complaint, null, new { complaint.Status, complaint.ResolvedById, complaint.ResolvedAt, complaint.Resolution }); await db.SaveChangesAsync(token); return await DetailsAsync(bankId, complaint.Id, token); }
    public async Task<BankComplaintDetailsDto> CloseAsync(Guid bankId, Guid complaintId, ComplaintTransitionRequest request, CancellationToken token) { await RequireManagerAsync(bankId, token); var complaint = await TrackedAsync(bankId, complaintId, token); EnsureCurrent(complaint, request.ExpectedUpdatedAt); var now = DateTimeOffset.UtcNow; Try(() => complaint.Close(now)); AddActivity(complaint, "CLOSED", $"Complaint {complaint.Reference} closed.", now); AddAudit("ComplaintClosed", complaint, null, new { complaint.Status, complaint.ClosedAt }); await db.SaveChangesAsync(token); return await DetailsAsync(bankId, complaint.Id, token); }
    public async Task<BankComplaintDetailsDto> ReopenAsync(Guid bankId, Guid complaintId, ComplaintReasonRequest request, CancellationToken token) { await RequireManagerAsync(bankId, token); var complaint = await TrackedAsync(bankId, complaintId, token); EnsureCurrent(complaint, request.ExpectedUpdatedAt); var before = complaint.Status; var now = DateTimeOffset.UtcNow; Try(() => complaint.Reopen(request.Reason, now)); db.CollectionComplaintNotes.Add(new CollectionComplaintNote(complaint.Id, $"Reopen reason: {request.Reason}", user.UserId, now)); AddActivity(complaint, "REOPENED", $"Complaint {complaint.Reference} reopened. Reason: {SafeContext(request.Reason)}", now); AddAudit("ComplaintReopened", complaint, new { Status = before }, new { complaint.Status, request.Reason }); await db.SaveChangesAsync(token); return await DetailsAsync(bankId, complaint.Id, token); }
    public async Task<BankComplaintDetailsDto> RejectAsync(Guid bankId, Guid complaintId, ComplaintReasonRequest request, CancellationToken token) { await RequireManagerAsync(bankId, token); var complaint = await TrackedAsync(bankId, complaintId, token); EnsureCurrent(complaint, request.ExpectedUpdatedAt); var now = DateTimeOffset.UtcNow; Try(() => complaint.Reject(request.Reason, now)); AddActivity(complaint, "REJECTED", $"Complaint {complaint.Reference} rejected. Reason: {SafeContext(request.Reason)}", now); AddAudit("ComplaintRejected", complaint, null, new { complaint.Status, complaint.RejectionReason }); await db.SaveChangesAsync(token); return await DetailsAsync(bankId, complaint.Id, token); }

    public async Task<BankComplaintDetailsDto> UploadAttachmentAsync(Guid bankId, Guid complaintId, string fileName, string contentType, long length, Stream content, CancellationToken token)
    {
        var complaint = await TrackedAsync(bankId, complaintId, token); EnsureOwnerOrManager(complaint, allowUnassignedCollector: true); if (length <= 0 || length > MaximumAttachmentBytes) throw new HrValidationException("Attachments must be between 1 byte and 10 MB."); var extension = Path.GetExtension(fileName).ToLowerInvariant(); var detectedType = await ValidateContentAsync(content, extension, token); var stored = await files.SaveAsync("complaint-attachments", fileName, detectedType, content, MaximumAttachmentBytes, token); var attachment = new CollectionAttachment(complaint.CaseId, null, "COMPLAINT_DOCUMENT", stored.OriginalFileName, detectedType, stored.Length, stored.Sha256Hash, stored.StorageKey, user.UserId, DateTimeOffset.UtcNow); attachment.LinkComplaint(complaint.Id); db.CollectionAttachments.Add(attachment); AddAudit("ComplaintAttachmentAdded", complaint, null, new { AttachmentId = attachment.Id, attachment.OriginalFileName, attachment.ContentType, attachment.FileSize }); try { await db.SaveChangesAsync(token); } catch { await files.DeleteAsync(stored.StorageKey, CancellationToken.None); throw; } return await DetailsAsync(bankId, complaint.Id, token);
    }
    public async Task<BankComplaintAttachmentDownloadDto> DownloadAttachmentAsync(Guid bankId, Guid complaintId, Guid attachmentId, CancellationToken token) { await DetailsAsync(bankId, complaintId, token); var a = await db.CollectionAttachments.AsNoTracking().SingleOrDefaultAsync(x => x.Id == attachmentId && x.ComplaintId == complaintId, token) ?? throw new HrNotFoundException("Complaint attachment was not found."); return new(await files.OpenReadAsync(a.StorageKey, token), a.ContentType, a.OriginalFileName); }
    public async Task RemoveAttachmentAsync(Guid bankId, Guid complaintId, Guid attachmentId, CancellationToken token) { var complaint = await TrackedAsync(bankId, complaintId, token); var a = await db.CollectionAttachments.SingleOrDefaultAsync(x => x.Id == attachmentId && x.ComplaintId == complaintId, token) ?? throw new HrNotFoundException("Complaint attachment was not found."); if (!Manager && a.UploadedById != user.UserId) throw new HrForbiddenException("You cannot remove this attachment."); await using var transaction = await db.Database.BeginTransactionAsync(token); db.CollectionAttachments.Remove(a); AddAudit("ComplaintAttachmentRemoved", complaint, new { AttachmentId = a.Id, a.OriginalFileName }, new { Removed = true }); await db.SaveChangesAsync(token); await files.DeleteAsync(a.StorageKey, token); await transaction.CommitAsync(token); }

    private IQueryable<CollectionCase> ScopedCases(Guid bankId) => ScopedCasesCore(bankId).Apply(classification);
    private IQueryable<CollectionCase> ScopedCasesCore(Guid bankId) { var q = db.CollectionCases.Where(x => x.Portfolio.OrganizationId == bankId && !x.IsArchived); if (Global) return q; if (Manager) return q.Where(x => (x.AssignedTeam != null && x.AssignedTeam.SupervisorId == user.UserId) || (x.AssignedTeamId == null && db.CollectionUserAccess.Any(a => a.UserId == user.UserId && a.OrganizationId == bankId && (a.PortfolioId == null || a.PortfolioId == x.PortfolioId)))); if (Collector) return q.Where(x => x.AssignedCollectorId == user.UserId); return q.Where(_ => false); }
    private IQueryable<CollectionComplaint> ScopedComplaints(Guid bankId) { var cases = ScopedCases(bankId); return db.CollectionComplaints.Where(x => cases.Any(c => c.Id == x.CaseId)); }
    private IQueryable<User> AuthorizedEmployees(Guid bankId) { var q = db.Users.Where(x => x.IsActive && x.UserRoles.Any(r => r.Role.Name == SystemRoleNames.CollectionsCollector)); if (Global) return q.Where(x => db.CollectionUserAccess.Any(a => a.UserId == x.Id && a.OrganizationId == bankId) || db.CollectionCases.Any(c => c.AssignedCollectorId == x.Id && c.Portfolio.OrganizationId == bankId)); return q.Where(x => db.CollectionTeamMembers.Any(m => m.UserId == x.Id && m.IsActive && m.Team.IsActive && m.Team.SupervisorId == user.UserId) && (db.CollectionUserAccess.Any(a => a.UserId == x.Id && a.OrganizationId == bankId) || db.CollectionCases.Any(c => c.AssignedCollectorId == x.Id && c.Portfolio.OrganizationId == bankId))); }
    private async Task<CollectionComplaint> TrackedAsync(Guid bankId, Guid id, CancellationToken token) => await ScopedComplaints(bankId).SingleOrDefaultAsync(x => x.Id == id, token) ?? throw new HrNotFoundException("Complaint was not found for this bank or user scope.");
    private async Task RequireBankAsync(Guid bankId, CancellationToken token) { if (!Manager && !Collector) throw new HrForbiddenException("You do not have permission to access complaints."); var exists = await db.CollectionClientOrganizations.AsNoTracking().AnyAsync(x => x.Id == bankId && x.IsActive && (x.OrganizationType == CollectionsValues.OrganizationTypes.Bank || x.OrganizationType == CollectionsValues.OrganizationTypes.ConsumerFinance), token); if (!exists || (!Global && !await db.CollectionUserAccess.AnyAsync(x => x.UserId == user.UserId && x.OrganizationId == bankId, token) && !await ScopedCases(bankId).AnyAsync(token))) throw new HrNotFoundException("Organization was not found or is outside your authorized scope."); }
    private async Task RequireManagerAsync(Guid bankId, CancellationToken token) { if (!Manager) throw new HrForbiddenException("Only an authorized team leader or manager can perform this complaint action."); await RequireBankAsync(bankId, token); }
    private async Task EnsureAuthorizedEmployee(Guid bankId, Guid id, CancellationToken token) { if (!await AuthorizedEmployees(bankId).AnyAsync(x => x.Id == id, token)) throw new HrForbiddenException("The selected employee is outside your authorized scope."); }
    private void EnsureOwnerOrManager(CollectionComplaint complaint, bool allowUnassignedCollector = false) { if (Manager) return; if (!Collector || (!allowUnassignedCollector && complaint.OwnerId != user.UserId)) throw new HrForbiddenException("This complaint is not assigned to the authenticated collector."); }
    private static void EnsureCurrent(CollectionComplaint complaint, DateTimeOffset expected) { if (expected == default || complaint.UpdatedAt != expected) throw new HrConflictException("This complaint was updated by another user. Refresh and try again."); }
    private static IQueryable<CollectionComplaint> Filter(IQueryable<CollectionComplaint> q, BankComplaintQuery r, DateTimeOffset now, TimeZoneInfo zone) { var view = (r.View ?? "OPEN").Trim().ToUpperInvariant(); q = view switch { "OPEN" => q.Where(x => x.Status == CollectionsValues.ComplaintStatuses.Open || x.Status == CollectionsValues.ComplaintStatuses.New), "IN_PROGRESS" => q.Where(x => x.Status == CollectionsValues.ComplaintStatuses.InProgress), "OVERDUE" => q.Where(x => x.SlaDueAt != null && x.SlaDueAt < now && !FinalStatuses.Contains(x.Status)), "RESOLVED" => q.Where(x => x.Status == CollectionsValues.ComplaintStatuses.Resolved), "CLOSED" => q.Where(x => x.Status == CollectionsValues.ComplaintStatuses.Closed), "ALL" => q, _ => throw new HrValidationException("Complaint view is invalid.") }; if (!string.IsNullOrWhiteSpace(r.Search)) { if (r.Search.Length > 160) throw new HrValidationException("Search cannot exceed 160 characters."); var t = r.Search.Trim().ToLower(); q = q.Where(x => x.Reference.ToLower().Contains(t) || x.Case.CaseNumber.ToLower().Contains(t) || (x.Case.Customer.FullNameArabic != null && x.Case.Customer.FullNameArabic.ToLower().Contains(t)) || (x.Case.Customer.FullNameEnglish != null && x.Case.Customer.FullNameEnglish.ToLower().Contains(t)) || (x.Case.Customer.PrimaryPhone != null && x.Case.Customer.PrimaryPhone.Contains(t)) || x.Description.ToLower().Contains(t)); } if (!string.IsNullOrWhiteSpace(r.Status)) { var s = NormalizeStatus(r.Status); q = q.Where(x => x.Status == s || (s == CollectionsValues.ComplaintStatuses.Open && x.Status == CollectionsValues.ComplaintStatuses.New)); } if (!string.IsNullOrWhiteSpace(r.Priority)) q = q.Where(x => x.Severity == NormalizePriority(r.Priority)); if (!string.IsNullOrWhiteSpace(r.Type)) q = q.Where(x => x.Category == NormalizeType(r.Type)); if (r.AssignedToId.HasValue) q = q.Where(x => x.OwnerId == r.AssignedToId); if (r.CreatedDate.HasValue) { var (start,end)=DayRange(r.CreatedDate.Value,zone); q = q.Where(x => x.ReceivedAt >= start && x.ReceivedAt < end); } if (r.DueDate.HasValue) { var (start,end)=DayRange(r.DueDate.Value,zone); q = q.Where(x => x.SlaDueAt >= start && x.SlaDueAt < end); } return q; }
    private static IQueryable<CollectionComplaint> Sort(IQueryable<CollectionComplaint> q, string? by, string? direction) { var desc = !string.Equals(direction, "asc", StringComparison.OrdinalIgnoreCase); return by?.Trim().ToLowerInvariant() switch { "due" => desc ? q.OrderByDescending(x => x.SlaDueAt) : q.OrderBy(x => x.SlaDueAt), "priority" => desc ? q.OrderByDescending(x => x.Severity == "CRITICAL" ? 4 : x.Severity == "HIGH" ? 3 : x.Severity == "MEDIUM" ? 2 : 1) : q.OrderBy(x => x.Severity == "CRITICAL" ? 4 : x.Severity == "HIGH" ? 3 : x.Severity == "MEDIUM" ? 2 : 1), "status" => desc ? q.OrderByDescending(x => x.Status) : q.OrderBy(x => x.Status), "customer" => desc ? q.OrderByDescending(x => x.Case.Customer.FullNameEnglish ?? x.Case.Customer.FullNameArabic) : q.OrderBy(x => x.Case.Customer.FullNameEnglish ?? x.Case.Customer.FullNameArabic), "updated" => desc ? q.OrderByDescending(x => x.UpdatedAt) : q.OrderBy(x => x.UpdatedAt), "created" or null or "" => desc ? q.OrderByDescending(x => x.ReceivedAt) : q.OrderBy(x => x.ReceivedAt), _ => throw new HrValidationException("Complaint sort field is invalid.") }; }
    private void AddActivity(CollectionComplaint c, string outcome, string notes, DateTimeOffset now) => db.CollectionActivities.Add(new CollectionActivity(c.CaseId, CollectionsValues.ActivityTypes.Complaint, outcome, $"{notes} Complaint ID: {c.Id}.", "COMPLAINT", user.UserId, now, null));
    private void AddAudit(string action, CollectionComplaint c, object? before, object after) => db.CollectionAuditLogs.Add(new CollectionAuditLog(user.UserId, action, nameof(CollectionComplaint), c.Id, c.CaseId, before == null ? null : JsonSerializer.Serialize(before), JsonSerializer.Serialize(after), "BANK_WORKSPACE", DateTimeOffset.UtcNow));
    private static string DisplayStatus(string status) => status == CollectionsValues.ComplaintStatuses.New ? CollectionsValues.ComplaintStatuses.Open : status;
    private static string NormalizeStatus(string value) => value.Trim().ToUpperInvariant() switch { "OPEN" or "NEW" => CollectionsValues.ComplaintStatuses.Open, "IN_PROGRESS" => CollectionsValues.ComplaintStatuses.InProgress, "RESOLVED" => CollectionsValues.ComplaintStatuses.Resolved, "CLOSED" => CollectionsValues.ComplaintStatuses.Closed, "REJECTED" => CollectionsValues.ComplaintStatuses.Rejected, _ => throw new HrValidationException("Complaint status is invalid.") };
    private static string NormalizePriority(string value) { var p = value.Trim().ToUpperInvariant(); if (p is not ("LOW" or "MEDIUM" or "HIGH" or "CRITICAL")) throw new HrValidationException("Complaint priority is invalid."); return p; }
    private static string NormalizeType(string value) { var t = value.Trim().ToUpperInvariant(); if (!Types.Contains(t)) throw new HrValidationException("Complaint type is invalid."); return t; }
    private static void ValidateDescription(string value) { if (string.IsNullOrWhiteSpace(value) || value.Trim().Length > 4000) throw new HrValidationException("Complaint description is required and cannot exceed 4000 characters."); }
    private static void ValidatePage(int page, int size) { if (page < 1 || size is not (20 or 50 or 100)) throw new HrValidationException("Page size must be 20, 50, or 100."); }
    private static string SafeContext(string value) { var text = value.Trim().Replace('\r', ' ').Replace('\n', ' '); return text.Length <= 240 ? text : text[..240] + "…"; }
    private static void Try(Action action) { try { action(); } catch (InvalidOperationException ex) { throw new HrConflictException(ex.Message); } catch (ArgumentException ex) { throw new HrValidationException(ex.Message); } }
    private async Task<(DateTimeOffset Start, DateTimeOffset End)> TodayRangeAsync(CancellationToken token) { var zone=await BusinessZoneAsync(token); var local=DateOnly.FromDateTime(TimeZoneInfo.ConvertTime(DateTimeOffset.UtcNow,zone).DateTime); return DayRange(local,zone); }
    private async Task<TimeZoneInfo> BusinessZoneAsync(CancellationToken token) { var id=await db.WorkingCalendars.AsNoTracking().OrderByDescending(x=>x.UpdatedAt??x.CreatedAt).Select(x=>x.TimeZoneId).FirstOrDefaultAsync(token)??"Africa/Cairo"; try{return TimeZoneInfo.FindSystemTimeZoneById(id);}catch{throw new HrConflictException("The configured business time zone is invalid.");} }
    private static (DateTimeOffset Start,DateTimeOffset End) DayRange(DateOnly date,TimeZoneInfo zone){var local=date.ToDateTime(TimeOnly.MinValue,DateTimeKind.Unspecified);return(new DateTimeOffset(TimeZoneInfo.ConvertTimeToUtc(local,zone)),new DateTimeOffset(TimeZoneInfo.ConvertTimeToUtc(local.AddDays(1),zone)));}
    private static async Task<string> ValidateContentAsync(Stream stream, string extension, CancellationToken token) { if (!stream.CanSeek) throw new HrValidationException("Attachment stream must be seekable."); var header = new byte[8]; var read = await stream.ReadAsync(header, token); stream.Position = 0; var pdf = read >= 5 && header.AsSpan(0, 5).SequenceEqual("%PDF-"u8); var jpeg = read >= 3 && header[0] == 0xFF && header[1] == 0xD8 && header[2] == 0xFF; var png = read >= 8 && header.AsSpan(0, 8).SequenceEqual(new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A }); return extension switch { ".pdf" when pdf => "application/pdf", ".jpg" or ".jpeg" when jpeg => "image/jpeg", ".png" when png => "image/png", _ => throw new HrValidationException("Only content-validated PDF, JPEG, and PNG attachments are accepted.") }; }
}
