using System.Data;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using MIS.Application.Common;
using MIS.Application.DTOs.Collections;
using MIS.Application.Interfaces;
using MIS.Domain.Constants;
using MIS.Domain.Entities;
using MIS.Infrastructure.Persistence;

namespace MIS.Infrastructure.Services;

public sealed class BankArchiveService(ApplicationDbContext db, ICurrentUserContext user, ICollectionsClassificationContext classification) : IBankArchiveService
{
    private static readonly string[] Reasons = ["CASE_CLOSED", "DEBT_SETTLED", "RETURNED_TO_BANK", "DUPLICATE_INVALID_CASE", "PORTFOLIO_ENDED", "OTHER"];
    private bool Has(string role) => user.Roles.Contains(role, StringComparer.OrdinalIgnoreCase);
    private bool Global => Has(SystemRoleNames.Admin) || Has(SystemRoleNames.CollectionsOperationsManager);
    private bool Manager => Global || Has(SystemRoleNames.CollectionsSupervisor);
    private bool Collector => Has(SystemRoleNames.CollectionsCollector);

    public async Task<ArchiveSummaryDto> SummaryAsync(Guid bankId, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); var cases = ScopedCases(bankId).AsNoTracking(); var imports = ScopedImports(bankId).AsNoTracking();
        var now = DateTimeOffset.UtcNow; var month = new DateTimeOffset(now.Year, now.Month, 1, 0, 0, 0, TimeSpan.Zero);
        var ids = cases.Select(x => x.Id); var importIds = imports.Select(x => x.Id); var archived = await db.CollectionAuditLogs.CountAsync(x => x.OccurredAt >= month && ((ids.Contains(x.EntityId) && x.Action == "CaseArchived") || (importIds.Contains(x.EntityId) && x.Action == "PortfolioArchived")), token);
        var restored = await db.CollectionAuditLogs.CountAsync(x => x.OccurredAt >= month && ((ids.Contains(x.EntityId) && x.Action == "CaseRestored") || (importIds.Contains(x.EntityId) && x.Action == "PortfolioRestored")), token);
        return new(await cases.CountAsync(x => x.IsArchived, token), await imports.CountAsync(x => x.IsArchived, token), archived, restored, Manager);
    }

    public async Task<ArchiveCasePageDto> CasesAsync(Guid bankId, ArchiveCaseQuery request, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); ValidatePage(request.Page, request.PageSize); var q = ScopedCases(bankId).AsNoTracking().Where(x => x.IsArchived);
        if (!string.IsNullOrWhiteSpace(request.Search)) { var t = Text(request.Search, 160, "Search").ToLower(); q = q.Where(x => x.CaseNumber.ToLower().Contains(t) || x.Customer.CustomerCode.ToLower().Contains(t) || (x.Customer.FullNameArabic != null && x.Customer.FullNameArabic.ToLower().Contains(t)) || (x.Customer.FullNameEnglish != null && x.Customer.FullNameEnglish.ToLower().Contains(t)) || (x.Customer.PrimaryPhone != null && x.Customer.PrimaryPhone.Contains(t)) || (x.Customer.NationalId != null && x.Customer.NationalId.Contains(t))); }
        if (request.ArchivedFrom.HasValue) q = q.Where(x => x.ArchivedAt >= request.ArchivedFrom.Value.ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc));
        if (request.ArchivedTo.HasValue) q = q.Where(x => x.ArchivedAt < request.ArchivedTo.Value.AddDays(1).ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc));
        if (request.ArchivedById.HasValue) q = q.Where(x => x.ArchivedById == request.ArchivedById); if (request.PreviousCollectorId.HasValue) q = q.Where(x => x.AssignedCollectorId == request.PreviousCollectorId); if (request.ImportId.HasValue) q = q.Where(x => x.SourceImportId == request.ImportId);
        if (!string.IsNullOrWhiteSpace(request.Reason)) { var reason = NormalizeReason(request.Reason); q = q.Where(x => x.ArchiveReason == reason); }
        var total = await q.CountAsync(token); var desc = request.SortDirection?.Equals("asc", StringComparison.OrdinalIgnoreCase) != true;
        q = request.SortBy?.ToLowerInvariant() switch { "customer" => desc ? q.OrderByDescending(x => x.Customer.FullNameEnglish ?? x.Customer.FullNameArabic) : q.OrderBy(x => x.Customer.FullNameEnglish ?? x.Customer.FullNameArabic), "outstanding" => desc ? q.OrderByDescending(x => x.OutstandingBalance) : q.OrderBy(x => x.OutstandingBalance), "updated" => desc ? q.OrderByDescending(x => x.UpdatedAt) : q.OrderBy(x => x.UpdatedAt), _ => desc ? q.OrderByDescending(x => x.ArchivedAt) : q.OrderBy(x => x.ArchivedAt) };
        var ar = ApiTextLocalizer.IsArabic; var items = await q.Skip((request.Page - 1) * request.PageSize).Take(request.PageSize).Select(x => new ArchiveCaseItemDto(x.Id, x.CaseNumber, ar ? x.Customer.FullNameArabic ?? x.Customer.FullNameEnglish! : x.Customer.FullNameEnglish ?? x.Customer.FullNameArabic!, x.Customer.PrimaryPhone, x.OutstandingBalance, x.AssignedCollectorId, x.AssignedCollector == null ? null : x.AssignedCollector.FullName, x.ArchiveReason!, x.ArchivedBy!.FullName, x.ArchivedAt!.Value, x.UpdatedAt)).ToArrayAsync(token);
        return new(items, total, request.Page, request.PageSize, total == 0 ? 0 : (int)Math.Ceiling(total / (double)request.PageSize), Manager);
    }

    public async Task<ArchiveCaseDetailsDto> CaseAsync(Guid bankId, Guid caseId, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); var x = await ScopedCases(bankId).AsNoTracking().Include(c => c.Customer).Include(c => c.Portfolio).ThenInclude(p => p.Organization).Include(c => c.AssignedCollector).Include(c => c.ArchivedBy).SingleOrDefaultAsync(c => c.Id == caseId && c.IsArchived, token) ?? throw new HrNotFoundException("Archived case was not found or is outside your scope.");
        var audits = await db.CollectionAuditLogs.AsNoTracking().Where(a => a.CaseId == caseId && (a.Action == "CaseArchived" || a.Action == "CaseRestored")).Include(a => a.User).OrderByDescending(a => a.OccurredAt).ToArrayAsync(token);
        var activities = await db.CollectionActivities.AsNoTracking().Where(a => a.CaseId == caseId).OrderByDescending(a => a.CreatedAt).Take(100).Select(a => new ArchiveRelatedItemDto(a.Id, a.ActivityType, a.Result ?? "", a.Result, a.Notes, a.CreatedAt)).ToArrayAsync(token);
        var ptps = await db.CollectionPromisesToPay.AsNoTracking().Where(a => a.CaseId == caseId).OrderByDescending(a => a.CreatedAt).Select(a => new ArchiveRelatedItemDto(a.Id, "PTP", a.Status, a.PromisedAmount.ToString(), a.Notes, a.CreatedAt)).ToArrayAsync(token);
        var visits = await db.CollectionFieldVisits.AsNoTracking().Where(a => a.CaseId == caseId).OrderByDescending(a => a.CreatedAt).Select(a => new ArchiveRelatedItemDto(a.Id, "VISIT", a.Status, a.Result, a.Notes, a.CreatedAt)).ToArrayAsync(token);
        var complaints = await db.CollectionComplaints.AsNoTracking().Where(a => a.CaseId == caseId).OrderByDescending(a => a.ReceivedAt).Select(a => new ArchiveRelatedItemDto(a.Id, "COMPLAINT", a.Status, a.Category, a.Description, a.ReceivedAt)).ToArrayAsync(token);
        var complaintNotes = await db.CollectionComplaintNotes.AsNoTracking().Where(a => a.Complaint.CaseId == caseId).OrderByDescending(a => a.CreatedAt).Select(a => new ArchiveRelatedItemDto(a.Id, "COMPLAINT_NOTE", "HISTORICAL", null, a.Text, a.CreatedAt)).ToArrayAsync(token);
        var attachments = await db.CollectionAttachments.AsNoTracking().Where(a => a.CaseId == caseId).OrderByDescending(a => a.UploadedAt).Select(a => new ArchiveRelatedItemDto(a.Id, "ATTACHMENT", a.Category, a.OriginalFileName, null, a.UploadedAt)).ToArrayAsync(token);
        var lifecycle = audits.Select(a => new ArchiveHistoryItemDto(a.Action, JsonValue(a.AfterJson, "Reason"), JsonValue(a.AfterJson, "Notes"), a.User?.FullName, a.OccurredAt)).ToArray(); var ar = ApiTextLocalizer.IsArabic;
        return new(x.Id, x.CaseNumber, ar ? x.Customer.FullNameArabic ?? x.Customer.FullNameEnglish! : x.Customer.FullNameEnglish ?? x.Customer.FullNameArabic!, x.Customer.CustomerCode, x.Customer.PrimaryPhone, x.Customer.NationalId, ar ? x.Customer.AddressArabic ?? x.Customer.AddressEnglish : x.Customer.AddressEnglish ?? x.Customer.AddressArabic, ar ? x.Portfolio.Organization.NameArabic : x.Portfolio.Organization.NameEnglish, ar ? x.Portfolio.NameArabic : x.Portfolio.NameEnglish, x.OriginalAmount, x.OutstandingBalance, x.Status, x.ArchiveReason!, x.ArchiveNotes, x.ArchivedBy!.FullName, x.ArchivedAt!.Value, x.AssignedCollector?.FullName, lifecycle, activities, ptps, visits, complaints.Concat(complaintNotes).OrderByDescending(i => i.OccurredAt).ToArray(), attachments, Manager, x.UpdatedAt);
    }

    public async Task ArchiveCaseAsync(Guid bankId, Guid caseId, ArchiveMutationRequest request, CancellationToken token)
    {
        RequireManager(); var reason = NormalizeReason(request.Reason); ValidateNotes(request.Notes); RequireOtherNotes(reason, request.Notes); await RequireBankAsync(bankId, token);
        await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, token); var item = await ScopedCases(bankId).SingleOrDefaultAsync(x => x.Id == caseId, token) ?? throw new HrNotFoundException("Case was not found or is outside your scope.");
        EnsureCurrent(item.UpdatedAt, request.ExpectedUpdatedAt); if (item.IsArchived) throw new HrConflictException("The case is already archived.");
        if (await db.CollectionPromisesToPay.AnyAsync(x => x.CaseId == caseId && (x.Status == CollectionsValues.PromiseStatuses.Active || x.Status == CollectionsValues.PromiseStatuses.DueToday || x.Status == CollectionsValues.PromiseStatuses.Upcoming || x.Status == CollectionsValues.PromiseStatuses.UnderReview), token)) throw new HrConflictException("Active PTPs must be resolved before this case can be archived.");
        if (await db.CollectionFieldVisits.AnyAsync(x => x.CaseId == caseId && (x.Status == CollectionsValues.VisitStatuses.Scheduled || x.Status == CollectionsValues.VisitStatuses.Planned || x.Status == CollectionsValues.VisitStatuses.Assigned || x.Status == CollectionsValues.VisitStatuses.InProgress || x.Status == CollectionsValues.VisitStatuses.Rescheduled), token)) throw new HrConflictException("Active visits must be completed or cancelled before archiving.");
        if (await db.CollectionComplaints.AnyAsync(x => x.CaseId == caseId && x.Status != CollectionsValues.ComplaintStatuses.Resolved && x.Status != CollectionsValues.ComplaintStatuses.Closed && x.Status != CollectionsValues.ComplaintStatuses.Rejected, token)) throw new HrConflictException("Open complaints must be resolved before archiving.");
        var now = DateTimeOffset.UtcNow; var before = new { item.IsArchived, item.AssignedCollectorId }; item.Archive(reason, request.Notes, user.UserId, now); db.CollectionActivities.Add(new(caseId, CollectionsValues.ActivityTypes.StatusChange, "CASE_ARCHIVED", $"Case archived. Reason: {reason}. {request.Notes}".Trim(), "ARCHIVE", user.UserId, now, null)); Audit("CaseArchived", item.Id, item.Id, before, new { item.IsArchived, Reason = reason, Notes = request.Notes }, now); await db.SaveChangesAsync(token); await tx.CommitAsync(token);
    }

    public async Task RestoreCaseAsync(Guid bankId, Guid caseId, RestoreMutationRequest request, CancellationToken token)
    {
        RequireManager(); var reason = Text(request.Reason, 500, "Restore reason"); await RequireBankAsync(bankId, token); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, token); var item = await ScopedCases(bankId).SingleOrDefaultAsync(x => x.Id == caseId && x.IsArchived, token) ?? throw new HrNotFoundException("Archived case was not found or is outside your scope."); EnsureCurrent(item.UpdatedAt, request.ExpectedUpdatedAt); var previous = item.AssignedCollectorId; var now = DateTimeOffset.UtcNow; item.Restore(reason, user.UserId, now); db.CollectionAssignmentHistory.Add(new(item.Id, previous, null, user.UserId, null, reason, "ARCHIVE_RESTORE", null, now)); db.CollectionActivities.Add(new(item.Id, CollectionsValues.ActivityTypes.StatusChange, "CASE_RESTORED", $"Case restored to the unassigned queue. Reason: {reason}", "ARCHIVE", user.UserId, now, null)); Audit("CaseRestored", item.Id, item.Id, new { IsArchived = true, AssignedCollectorId = previous }, new { item.IsArchived, Reason = reason, AssignedCollectorId = (Guid?)null }, now); await db.SaveChangesAsync(token); await tx.CommitAsync(token);
    }

    public async Task<ArchivePortfolioPageDto> PortfoliosAsync(Guid bankId, ArchivePortfolioQuery request, CancellationToken token)
    {
        await RequireBankAsync(bankId, token); ValidatePage(request.Page, request.PageSize); var q = ScopedImports(bankId).AsNoTracking().Where(x => x.IsArchived); if (!string.IsNullOrWhiteSpace(request.Search)) { var t = Text(request.Search, 160, "Search").ToLower(); q = q.Where(x => x.PortfolioName.ToLower().Contains(t) || x.OriginalFileName.ToLower().Contains(t)); } if (request.ArchivedById.HasValue) q = q.Where(x => x.ArchivedById == request.ArchivedById); if (request.ArchivedFrom.HasValue) q = q.Where(x => x.ArchivedAt >= request.ArchivedFrom.Value.ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc)); if (request.ArchivedTo.HasValue) q = q.Where(x => x.ArchivedAt < request.ArchivedTo.Value.AddDays(1).ToDateTime(TimeOnly.MinValue, DateTimeKind.Utc)); var total = await q.CountAsync(token); var items = await q.OrderByDescending(x => x.ArchivedAt).Skip((request.Page - 1) * request.PageSize).Take(request.PageSize).Select(x => new ArchivePortfolioItemDto(x.Id, x.PortfolioName, x.OriginalFileName, x.RowCount, x.UploadedAt, x.ArchiveReason!, x.ArchivedBy!.FullName, x.ArchivedAt!.Value)).ToArrayAsync(token); return new(items, total, request.Page, request.PageSize, total == 0 ? 0 : (int)Math.Ceiling(total / (double)request.PageSize), Global);
    }

    public async Task ArchivePortfolioAsync(Guid bankId, Guid portfolioId, ArchiveMutationRequest request, CancellationToken token) { if (!Global) throw new HrForbiddenException("Portfolio archive is available only to Operations Managers."); var reason = NormalizeReason(request.Reason); await RequireBankAsync(bankId, token); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, token); var item = await db.BankPortfolioImports.SingleOrDefaultAsync(x => x.Id == portfolioId && x.BankId == bankId, token) ?? throw new HrNotFoundException("Portfolio import was not found."); if (await db.CollectionCases.AnyAsync(x => x.SourceImportId == portfolioId && !x.IsArchived, token)) throw new HrConflictException("Archive all active linked cases before archiving this portfolio."); var now = DateTimeOffset.UtcNow; item.Archive(reason, request.Notes, user.UserId, now); Audit("PortfolioArchived", item.Id, null, new { IsArchived = false }, new { IsArchived = true, Reason = reason, Notes = request.Notes }, now); await db.SaveChangesAsync(token); await tx.CommitAsync(token); }
    public async Task RestorePortfolioAsync(Guid bankId, Guid portfolioId, RestoreMutationRequest request, CancellationToken token) { if (!Global) throw new HrForbiddenException("Portfolio restore is available only to Operations Managers."); var reason = Text(request.Reason, 500, "Restore reason"); await RequireBankAsync(bankId, token); await using var tx = await db.Database.BeginTransactionAsync(token); var item = await db.BankPortfolioImports.SingleOrDefaultAsync(x => x.Id == portfolioId && x.BankId == bankId && x.IsArchived, token) ?? throw new HrNotFoundException("Archived portfolio was not found."); item.Restore(reason, user.UserId, DateTimeOffset.UtcNow); Audit("PortfolioRestored", item.Id, null, new { IsArchived = true }, new { IsArchived = false, Reason = reason }, DateTimeOffset.UtcNow); await db.SaveChangesAsync(token); await tx.CommitAsync(token); }
    public async Task<IReadOnlyCollection<ArchiveFilterOptionDto>> UsersAsync(Guid bankId, CancellationToken token) { await RequireBankAsync(bankId, token); var ids = ScopedCases(bankId).Where(x => x.IsArchived && x.ArchivedById != null).Select(x => x.ArchivedById!.Value); return await db.Users.AsNoTracking().Where(x => ids.Contains(x.Id)).OrderBy(x => x.FullName).Select(x => new ArchiveFilterOptionDto(x.Id, x.FullName)).ToArrayAsync(token); }

    private IQueryable<CollectionCase> ScopedCases(Guid bankId) => ScopedCasesCore(bankId).Apply(classification);
    private IQueryable<CollectionCase> ScopedCasesCore(Guid bankId) { var q = db.CollectionCases.Where(x => x.Portfolio.OrganizationId == bankId); if (Global) return q; if (Collector) return q.Where(x => x.AssignedCollectorId == user.UserId || db.CollectionAssignmentHistory.Any(h => h.CaseId == x.Id && h.AssignedToId == user.UserId)); if (Manager) return q.Where(x => (x.AssignedTeam != null && x.AssignedTeam.SupervisorId == user.UserId) || db.CollectionAssignmentHistory.Any(h => h.CaseId == x.Id && h.Team != null && h.Team.SupervisorId == user.UserId) || (x.AssignedTeamId == null && db.CollectionUserAccess.Any(a => a.UserId == user.UserId && a.OrganizationId == bankId && (a.PortfolioId == null || a.PortfolioId == x.PortfolioId)))); return q.Where(_ => false); }
    private IQueryable<BankPortfolioImport> ScopedImports(Guid bankId) { var q = db.BankPortfolioImports.Where(x => x.BankId == bankId); if (Global) return q; var ids = ScopedCases(bankId).Where(x => x.SourceImportId != null).Select(x => x.SourceImportId!.Value); return q.Where(x => ids.Contains(x.Id)); }
    private async Task RequireBankAsync(Guid id, CancellationToken token) { if (!await db.CollectionClientOrganizations.AsNoTracking().AnyAsync(x => x.Id == id && x.IsActive && (x.OrganizationType == CollectionsValues.OrganizationTypes.Bank || x.OrganizationType == CollectionsValues.OrganizationTypes.ConsumerFinance), token) || (!Global && !await db.CollectionUserAccess.AnyAsync(x => x.UserId == user.UserId && x.OrganizationId == id, token) && !await ScopedCases(id).AnyAsync(token))) throw new HrNotFoundException("Organization was not found or is outside your authorized scope."); }
    private void RequireManager() { if (!Manager) throw new HrForbiddenException("Only an authorized Collections manager can archive or restore cases."); }
    private void Audit(string action, Guid entityId, Guid? caseId, object before, object after, DateTimeOffset now) => db.CollectionAuditLogs.Add(new(user.UserId, action, caseId.HasValue ? nameof(CollectionCase) : nameof(BankPortfolioImport), entityId, caseId, JsonSerializer.Serialize(before), JsonSerializer.Serialize(after), "ARCHIVE", now));
    private static string NormalizeReason(string value) { var v = Text(value, 80, "Archive reason").Trim().ToUpperInvariant().Replace(' ', '_').Replace('/', '_'); if (!Reasons.Contains(v)) throw new HrValidationException("Archive reason is invalid."); return v; }
    private static string Text(string? value, int max, string label) { if (string.IsNullOrWhiteSpace(value)) throw new HrValidationException($"{label} is required."); var v = value.Trim(); if (v.Length > max) throw new HrValidationException($"{label} cannot exceed {max} characters."); return v; }
    private static void ValidateNotes(string? value) { if (value?.Length > 1000) throw new HrValidationException("Archive notes cannot exceed 1000 characters."); }
    private static void RequireOtherNotes(string reason, string? notes) { if (reason == "OTHER" && string.IsNullOrWhiteSpace(notes)) throw new HrValidationException("Archive notes are required when the reason is Other."); }
    private static void ValidatePage(int page, int size) { if (page < 1 || size is not (20 or 50 or 100)) throw new HrValidationException("Page size must be 20, 50, or 100."); }
    private static void EnsureCurrent(DateTimeOffset current, DateTimeOffset? expected) { if (expected.HasValue && current != expected.Value) throw new HrConflictException("This case changed after it was opened. Refresh and try again."); }
    private static string? JsonValue(string? json, string key) { if (string.IsNullOrWhiteSpace(json)) return null; try { using var d = JsonDocument.Parse(json); return d.RootElement.TryGetProperty(key, out var value) ? value.GetString() : null; } catch { return null; } }
}
