import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { Download, Eye, FileArchive, FilePenLine, FilePlus2, RefreshCw, Search, Trash2, Upload } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Button } from '../../components/common/Button';
import { Card } from '../../components/common/Card';
import { EmptyState } from '../../components/common/EmptyState';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { StatusBadge, type StatusTone } from '../../components/common/StatusBadge';
import { useToast } from '../../components/common/Toast';
import { DateInput } from '../../components/forms/DateInput';
import { FileInput } from '../../components/forms/FileInput';
import { SelectInput } from '../../components/forms/SelectInput';
import { TextAreaInput } from '../../components/forms/TextAreaInput';
import { useLocalization } from '../../context/LocalizationContext';
import { EmployeeSearchSelect } from '../../features/hr/components/EmployeeSearchSelect';
import { hrEmployeeDocumentService } from '../../features/hr/services/hrEmployeeDocumentService';
import { hrEmployeeService } from '../../features/hr/services/hrEmployeeService';
import { hrMasterDataService } from '../../features/hr/services/hrMasterDataService';
import type { EmployeeListItem } from '../../features/hr/types/employee';
import type { DocumentExpiryStatus, EmployeeDocumentDetails, EmployeeDocumentListItem, EmployeeDocumentQuery, PagedEmployeeDocuments, SaveEmployeeDocumentMetadata } from '../../features/hr/types/document';
import type { MasterDataItem, MasterDataLookup } from '../../features/hr/types/masterData';
import { getApiErrorMessage } from '../../services/apiClient';

const emptyPage: PagedEmployeeDocuments = { items: [], page: 1, pageSize: 20, totalCount: 0, totalPages: 0 };
const copy = {
  en: { title: 'Employee Documents', subtitle: 'Upload, validate, and track employee files and expiry dates', add: 'Upload Document', summary: 'Expiry overview', expired: 'Expired', seven: 'Within 7 days', fifteen: 'Within 15 days', thirty: 'Within 30 days', search: 'Search employee, ID, file, or document type', employee: 'Employee', department: 'Department', documentType: 'Document Type', expiry: 'Expiry Status', all: 'All', expiring: 'Expiring Soon', valid: 'Valid', noExpiry: 'No Expiry', file: 'File', issueDate: 'Issue Date', expiryDate: 'Expiry Date', uploaded: 'Uploaded', actions: 'Actions', noRows: 'No employee documents', noRowsHelp: 'Upload the first document or adjust the active filters.', loadError: 'Unable to load employee documents.', detailsError: 'Unable to load document details.', saveError: 'Unable to save the document.', replaceError: 'Unable to replace the document file.', deleteError: 'Unable to delete the document.', previewError: 'Unable to preview this file.', downloadError: 'Unable to download this file.', created: 'Document uploaded.', updated: 'Document details updated.', replaced: 'Document file replaced.', deleted: 'Document deleted.', edit: 'Edit Details', replace: 'Replace File', details: 'Document Details', download: 'Download', preview: 'Preview', remove: 'Delete', close: 'Close', cancel: 'Cancel', save: 'Save', upload: 'Upload', reason: 'Deletion reason (optional)', deleteTitle: 'Delete Document', deleteMessage: 'Delete {file}? Its HR metadata will remain in audit history. Documents attached to leave history cannot be deleted.', required: 'Employee, document type, and file are required.', dateError: 'Expiry date cannot be before issue date.', fileHelp: 'PDF, JPEG, PNG, or DOCX. Maximum 10 MB. File content is validated by the server.', meta: 'Metadata', uploadedBy: 'Uploaded by', uploadedAt: 'Uploaded at', size: 'File size', notes: 'Notes', hash: 'SHA-256', refresh: 'Refresh', editFile: 'Choose replacement file', invalidFile: 'Choose a supported file no larger than 10 MB.', allDepartments: 'All departments', allTypes: 'All document types' },
  ar: { title: 'مستندات الموظفين', subtitle: 'رفع ملفات الموظفين والتحقق منها ومتابعة تواريخ انتهائها', add: 'رفع مستند', summary: 'ملخص الانتهاء', expired: 'منتهي', seven: 'خلال 7 أيام', fifteen: 'خلال 15 يومًا', thirty: 'خلال 30 يومًا', search: 'ابحث بالموظف أو الرقم أو الملف أو نوع المستند', employee: 'الموظف', department: 'القسم', documentType: 'نوع المستند', expiry: 'حالة الانتهاء', all: 'الكل', expiring: 'ينتهي قريبًا', valid: 'ساري', noExpiry: 'بدون انتهاء', file: 'الملف', issueDate: 'تاريخ الإصدار', expiryDate: 'تاريخ الانتهاء', uploaded: 'تاريخ الرفع', actions: 'الإجراءات', noRows: 'لا توجد مستندات موظفين', noRowsHelp: 'ارفع أول مستند أو عدّل عوامل التصفية.', loadError: 'تعذر تحميل مستندات الموظفين.', detailsError: 'تعذر تحميل تفاصيل المستند.', saveError: 'تعذر حفظ المستند.', replaceError: 'تعذر استبدال ملف المستند.', deleteError: 'تعذر حذف المستند.', previewError: 'تعذرت معاينة هذا الملف.', downloadError: 'تعذر تنزيل هذا الملف.', created: 'تم رفع المستند.', updated: 'تم تحديث بيانات المستند.', replaced: 'تم استبدال ملف المستند.', deleted: 'تم حذف المستند.', edit: 'تعديل البيانات', replace: 'استبدال الملف', details: 'تفاصيل المستند', download: 'تنزيل', preview: 'معاينة', remove: 'حذف', close: 'إغلاق', cancel: 'إلغاء', save: 'حفظ', upload: 'رفع', reason: 'سبب الحذف (اختياري)', deleteTitle: 'حذف المستند', deleteMessage: 'هل تريد حذف {file}؟ ستبقى بيانات العملية في سجل التدقيق، ولا يمكن حذف مستند مرتبط بطلب إجازة.', required: 'الموظف ونوع المستند والملف مطلوبون.', dateError: 'لا يمكن أن يسبق تاريخ الانتهاء تاريخ الإصدار.', fileHelp: 'PDF أو JPEG أو PNG أو DOCX بحد أقصى 10 ميجابايت، ويتحقق الخادم من محتوى الملف.', meta: 'بيانات المستند', uploadedBy: 'رُفع بواسطة', uploadedAt: 'تاريخ الرفع', size: 'حجم الملف', notes: 'ملاحظات', hash: 'SHA-256', refresh: 'تحديث', editFile: 'اختر الملف البديل', invalidFile: 'اختر ملفًا مدعومًا لا يتجاوز 10 ميجابايت.', allDepartments: 'كل الأقسام', allTypes: 'كل أنواع المستندات' },
} as const;

function tone(status: string): StatusTone { return status === 'Expired' ? 'danger' : status === 'ExpiringSoon' ? 'warning' : status === 'Valid' ? 'success' : 'neutral'; }
function formatBytes(value: number) { const units = window.localStorage.getItem('mis.language') === 'ar' ? ['بايت', 'ك.ب', 'م.ب'] : ['B', 'KB', 'MB']; if (value < 1024) return `${value} ${units[0]}`; if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} ${units[1]}`; return `${(value / 1024 / 1024).toFixed(1)} ${units[2]}`; }
function formatDate(value: string | null, locale: string) { return value ? new Intl.DateTimeFormat(locale, { dateStyle: 'medium' }).format(new Date(`${value}T00:00:00`)) : '—'; }
function formatDateTime(value: string, locale: string) { return new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
function nullable(value: string) { return value.trim() || null; }

function DocumentFormModal({ document, initialEmployee, onClose, onSaved, types }: { document: EmployeeDocumentDetails | null; initialEmployee: EmployeeListItem | null; onClose: () => void; onSaved: () => void; types: MasterDataItem[] }) {
  const { language } = useLocalization(); const text = copy[language]; const toast = useToast();
  const [employeeId, setEmployeeId] = useState(document?.employeeId ?? initialEmployee?.id ?? '');
  const [employee, setEmployee] = useState<EmployeeListItem | null>(initialEmployee);
  const [metadata, setMetadata] = useState<SaveEmployeeDocumentMetadata>({ documentTypeId: document?.documentTypeId ?? '', issueDate: document?.issueDate ?? null, expiryDate: document?.expiryDate ?? null, notes: document?.notes ?? null });
  const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError('');
    if (!employeeId || !metadata.documentTypeId || (!document && !file)) { setError(text.required); return; }
    if (metadata.issueDate && metadata.expiryDate && metadata.expiryDate < metadata.issueDate) { setError(text.dateError); return; }
    if (file && file.size > 10 * 1024 * 1024) { setError(text.invalidFile); return; }
    setSaving(true);
    try { if (document) await hrEmployeeDocumentService.update(document.id, metadata); else await hrEmployeeDocumentService.create(employeeId, metadata, file!); toast.success(document ? text.updated : text.created); onSaved(); }
    catch (requestError) { setError(getApiErrorMessage(requestError, text.saveError)); }
    finally { setSaving(false); }
  }
  return <Modal closeOnBackdrop={!saving} onClose={onClose} open size="lg" title={document ? text.edit : text.add}><form className="grid gap-5 sm:grid-cols-2" onSubmit={submit}>{error ? <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</div> : null}{document ? <div className="rounded-xl bg-mis-surface p-4 sm:col-span-2"><p className="text-xs text-slate-500">{text.employee}</p><p className="mt-1 font-semibold text-mis-navy">{document.employeeNumber} · {document.employeeName}</p></div> : <div className="sm:col-span-2"><EmployeeSearchSelect initialSelection={employee} label={text.employee} onChange={(id, item) => { setEmployeeId(id); setEmployee(item); }} required value={employeeId} /></div>}<SelectInput label={text.documentType} onChange={(event) => setMetadata((current) => ({ ...current, documentTypeId: event.target.value }))} required value={metadata.documentTypeId}><option value="">{text.allTypes}</option>{types.filter((item) => item.isActive || item.id === metadata.documentTypeId).map((item) => <option key={item.id} value={item.id}>{language === 'ar' && item.nameArabic ? item.nameArabic : item.nameEnglish}</option>)}</SelectInput>{!document ? <FileInput accept=".pdf,.jpg,.jpeg,.png,.docx,application/pdf,image/jpeg,image/png,application/vnd.openxmlformats-officedocument.wordprocessingml.document" hint={text.fileHelp} label={text.file} onChange={(event) => setFile(event.target.files?.[0] ?? null)} required /> : <div />}<DateInput label={text.issueDate} onChange={(event) => setMetadata((current) => ({ ...current, issueDate: event.target.value || null }))} value={metadata.issueDate ?? ''} /><DateInput label={text.expiryDate} min={metadata.issueDate ?? undefined} onChange={(event) => setMetadata((current) => ({ ...current, expiryDate: event.target.value || null }))} value={metadata.expiryDate ?? ''} /><TextAreaInput containerClassName="sm:col-span-2" label={text.notes} maxLength={1000} onChange={(event) => setMetadata((current) => ({ ...current, notes: event.target.value }))} value={metadata.notes ?? ''} /><div className="flex justify-end gap-2 sm:col-span-2"><Button disabled={saving} fullWidth={false} onClick={onClose} type="button" variant="outline">{text.cancel}</Button><Button fullWidth={false} isLoading={saving} type="submit">{document ? text.save : text.upload}</Button></div></form></Modal>;
}

export function HrEmployeeDocumentsPage() {
  const { language, t } = useLocalization(); const text = copy[language]; const locale = language === 'ar' ? 'ar-EG' : 'en-GB'; const toast = useToast(); const [searchParams] = useSearchParams();
  const initialEmployeeId = searchParams.get('employeeId') ?? '';
  const [query, setQuery] = useState<EmployeeDocumentQuery>({ page: 1, pageSize: 20, search: '', employeeId: initialEmployeeId, departmentId: '', documentTypeId: '', expiryStatus: 'All', expiringWithinDays: 30, sortBy: 'uploadedAt', sortDirection: 'desc' });
  const [search, setSearch] = useState(''); const [data, setData] = useState(emptyPage); const [summary, setSummary] = useState({ expired: 0, expiringWithin7Days: 0, expiringWithin15Days: 0, expiringWithin30Days: 0 });
  const [departments, setDepartments] = useState<MasterDataLookup[]>([]); const [types, setTypes] = useState<MasterDataItem[]>([]); const [selectedEmployee, setSelectedEmployee] = useState<EmployeeListItem | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<EmployeeDocumentDetails | null>(null); const [details, setDetails] = useState<EmployeeDocumentDetails | null>(null); const [replaceTarget, setReplaceTarget] = useState<EmployeeDocumentListItem | null>(null); const [deleteTarget, setDeleteTarget] = useState<EmployeeDocumentListItem | null>(null); const [reason, setReason] = useState(''); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState('');

  useEffect(() => { const timer = window.setTimeout(() => setQuery((current) => ({ ...current, page: 1, search: search.trim() })), 300); return () => window.clearTimeout(timer); }, [search]);
  useEffect(() => { void Promise.all([hrMasterDataService.getLookup('departments'), hrMasterDataService.getPaged({ category: 'document-types', isActive: null, page: 1, pageSize: 200, search: '' })]).then(([departmentItems, typeItems]) => { setDepartments(departmentItems); setTypes(typeItems.items); }).catch(() => undefined); }, []);
  useEffect(() => { if (!initialEmployeeId) return; void hrEmployeeService.getEmployee(initialEmployeeId).then((item) => setSelectedEmployee(item)).catch(() => undefined); }, [initialEmployeeId]);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [items, totals] = await Promise.all([hrEmployeeDocumentService.getPaged(query), hrEmployeeDocumentService.getSummary()]); setData(items); setSummary(totals); } catch (requestError) { setError(getApiErrorMessage(requestError, text.loadError)); } finally { setLoading(false); } }, [query, text.loadError]);
  useEffect(() => { void load(); }, [load]);
  async function openDetails(item: EmployeeDocumentListItem, mode: 'details' | 'edit') { setBusy(item.id); try { const value = await hrEmployeeDocumentService.getDetails(item.id); if (mode === 'details') setDetails(value); else { setEditing(value); setFormOpen(true); } } catch (requestError) { toast.error(getApiErrorMessage(requestError, text.detailsError)); } finally { setBusy(''); } }
  async function download(item: Pick<EmployeeDocumentListItem, 'id' | 'fileName'>) { setBusy(item.id); try { await hrEmployeeDocumentService.download(item.id, item.fileName); } catch (requestError) { toast.error(getApiErrorMessage(requestError, text.downloadError)); } finally { setBusy(''); } }
  async function preview(item: EmployeeDocumentListItem) {
    const previewWindow = window.open('about:blank', '_blank');
    if (!previewWindow) { toast.error(text.previewError); return; }
    previewWindow.opener = null;
    setBusy(item.id);
    try {
      const value = await hrEmployeeDocumentService.preview(item.id);
      const url = URL.createObjectURL(value.blob);
      previewWindow.location.replace(url);
      window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
    } catch (requestError) {
      previewWindow.close();
      toast.error(getApiErrorMessage(requestError, text.previewError));
    } finally { setBusy(''); }
  }
  async function replace() { if (!replaceTarget || !file) return; if (file.size > 10 * 1024 * 1024) { toast.error(text.invalidFile); return; } setBusy(replaceTarget.id); try { await hrEmployeeDocumentService.replace(replaceTarget.id, file); toast.success(text.replaced); setReplaceTarget(null); setFile(null); await load(); } catch (requestError) { toast.error(getApiErrorMessage(requestError, text.replaceError)); } finally { setBusy(''); } }
  async function remove() { if (!deleteTarget) return; setBusy(deleteTarget.id); try { await hrEmployeeDocumentService.delete(deleteTarget.id, nullable(reason)); toast.success(text.deleted); setDeleteTarget(null); setReason(''); await load(); } catch (requestError) { toast.error(getApiErrorMessage(requestError, text.deleteError)); } finally { setBusy(''); } }
  function closeDeleteDialog() { setDeleteTarget(null); setReason(''); }
  function applyExpiry(status: DocumentExpiryStatus, days = 30) { setQuery((current) => ({ ...current, page: 1, expiryStatus: status, expiringWithinDays: days })); }
  const expiryLabel: Record<string, string> = { Expired: text.expired, ExpiringSoon: text.expiring, Valid: text.valid, NoExpiry: text.noExpiry };

  return <div className="mx-auto max-w-[1500px]"><PageHeader actions={<Button fullWidth={false} leftIcon={<FilePlus2 className="h-4 w-4" />} onClick={() => { setEditing(null); setFormOpen(true); }}>{text.add}</Button>} description={text.subtitle} eyebrow={t('hrDepartment')} title={text.title} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[text.expired, summary.expired, 'Expired', 30, 'text-red-700 bg-red-50'], [text.seven, summary.expiringWithin7Days, 'ExpiringSoon', 7, 'text-amber-700 bg-amber-50'], [text.fifteen, summary.expiringWithin15Days, 'ExpiringSoon', 15, 'text-orange-700 bg-orange-50'], [text.thirty, summary.expiringWithin30Days, 'ExpiringSoon', 30, 'text-sky-700 bg-sky-50']].map(([label, value, status, days, style]) => <button className={`rounded-2xl border border-mis-border p-5 text-start shadow-sm ${style}`} key={String(label)} onClick={() => applyExpiry(status as DocumentExpiryStatus, Number(days))} type="button"><span className="text-sm font-semibold">{label}</span><strong className="mt-3 block text-3xl tabular-nums">{value}</strong></button>)}</div>
    <Card className="mt-6" padding="none"><div className="grid gap-3 border-b border-mis-border p-4 md:grid-cols-2 xl:grid-cols-[minmax(230px,1fr)_220px_180px_180px_180px]"><label className="relative"><Search className="absolute start-3 top-3 h-5 w-5 text-slate-400" /><input className="h-11 w-full rounded-xl border border-mis-border pe-3 ps-10 text-sm" onChange={(event) => setSearch(event.target.value)} placeholder={text.search} value={search} /></label><div className="xl:col-span-1"><EmployeeSearchSelect initialSelection={selectedEmployee} label={text.employee} onChange={(id, item) => { setSelectedEmployee(item); setQuery((current) => ({ ...current, employeeId: id, page: 1 })); }} value={query.employeeId} /></div><ProfessionalSelect className="h-11 rounded-xl border border-mis-border bg-white px-3 text-sm" onChange={(event) => setQuery((current) => ({ ...current, departmentId: event.target.value, page: 1 }))} value={query.departmentId}><option value="">{text.allDepartments}</option>{departments.map((item) => <option key={item.id} value={item.id}>{language === 'ar' && item.nameArabic ? item.nameArabic : item.nameEnglish}</option>)}</ProfessionalSelect><ProfessionalSelect className="h-11 rounded-xl border border-mis-border bg-white px-3 text-sm" onChange={(event) => setQuery((current) => ({ ...current, documentTypeId: event.target.value, page: 1 }))} value={query.documentTypeId}><option value="">{text.allTypes}</option>{types.map((item) => <option key={item.id} value={item.id}>{language === 'ar' && item.nameArabic ? item.nameArabic : item.nameEnglish}</option>)}</ProfessionalSelect><ProfessionalSelect className="h-11 rounded-xl border border-mis-border bg-white px-3 text-sm" onChange={(event) => applyExpiry(event.target.value as DocumentExpiryStatus)} value={query.expiryStatus}><option value="All">{text.all}</option><option value="Expired">{text.expired}</option><option value="ExpiringSoon">{text.expiring}</option><option value="Valid">{text.valid}</option><option value="NoExpiry">{text.noExpiry}</option></ProfessionalSelect></div>
      {error ? <div className="p-5"><ErrorState compact message={error} onRetry={() => void load()} title={text.loadError} /></div> : loading ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : data.items.length === 0 ? <EmptyState description={text.noRowsHelp} icon={<FileArchive />} title={text.noRows} /> : <><div className="overflow-x-auto"><table className="w-full min-w-[1100px]"><thead className="bg-mis-surface text-xs uppercase text-slate-500"><tr>{[text.employee, text.documentType, text.file, text.issueDate, text.expiryDate, text.expiry, text.uploaded, text.actions].map((heading) => <th className="px-4 py-3 text-start" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map((item) => <tr key={item.id}><td className="px-4 py-4"><p className="font-semibold text-mis-navy">{item.employeeName}</p><p className="text-xs text-slate-500">{item.employeeNumber} · {item.departmentName}</p></td><td className="px-4 py-4 text-sm">{item.documentType}</td><td className="max-w-48 px-4 py-4"><p className="truncate text-sm" title={item.fileName}>{item.fileName}</p><p className="text-xs text-slate-400">{formatBytes(item.fileSize)}</p></td><td className="px-4 py-4 text-sm">{formatDate(item.issueDate, locale)}</td><td className="px-4 py-4 text-sm">{formatDate(item.expiryDate, locale)}</td><td className="px-4 py-4"><StatusBadge tone={tone(item.expiryStatus)}>{expiryLabel[item.expiryStatus] ?? item.expiryStatus}</StatusBadge></td><td className="px-4 py-4 text-sm">{formatDateTime(item.uploadedAt, locale)}</td><td className="px-4 py-4"><div className="flex justify-end gap-1"><button aria-label={text.details} className="rounded-lg p-2 text-mis-primary hover:bg-mis-pale" disabled={busy === item.id} onClick={() => void openDetails(item, 'details')}><Eye className="h-4 w-4" /></button><button aria-label={text.edit} className="rounded-lg p-2 text-mis-primary hover:bg-mis-pale" onClick={() => void openDetails(item, 'edit')}><FilePenLine className="h-4 w-4" /></button><button aria-label={text.preview} className="rounded-lg p-2 text-mis-primary hover:bg-mis-pale" onClick={() => void preview(item)}><Eye className="h-4 w-4" /></button><button aria-label={text.download} className="rounded-lg p-2 text-mis-primary hover:bg-mis-pale" onClick={() => void download(item)}><Download className="h-4 w-4" /></button><button aria-label={text.replace} className="rounded-lg p-2 text-mis-primary hover:bg-mis-pale" onClick={() => setReplaceTarget(item)}><Upload className="h-4 w-4" /></button><button aria-label={text.remove} className="rounded-lg p-2 text-red-600 hover:bg-red-50" onClick={() => setDeleteTarget(item)}><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div><Pagination onPageChange={(page) => setQuery((current) => ({ ...current, page }))} page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} /></>}</Card>
    {formOpen ? <DocumentFormModal document={editing} initialEmployee={selectedEmployee} onClose={() => { setFormOpen(false); setEditing(null); }} onSaved={() => { setFormOpen(false); setEditing(null); void load(); }} types={types} /> : null}
    {details ? <Modal footer={<><Button fullWidth={false} isLoading={busy === details.id} leftIcon={<Download className="h-4 w-4" />} onClick={() => void download(details)} variant="outline">{text.download}</Button><Button disabled={busy === details.id} fullWidth={false} onClick={() => setDetails(null)}>{text.close}</Button></>} onClose={() => setDetails(null)} open size="lg" title={text.details}><dl className="grid gap-4 sm:grid-cols-2">{[[text.employee, `${details.employeeNumber} · ${details.employeeName}`], [text.documentType, details.documentType], [text.file, details.fileName], [text.size, formatBytes(details.fileSize)], [text.issueDate, formatDate(details.issueDate, locale)], [text.expiryDate, formatDate(details.expiryDate, locale)], [text.uploadedBy, details.uploadedBy], [text.uploadedAt, formatDateTime(details.uploadedAt, locale)], [text.hash, details.sha256Hash ?? '—'], [text.notes, details.notes ?? '—']].map(([label, value]) => <div className="rounded-xl bg-mis-surface p-4" key={label}><dt className="text-xs font-semibold text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm font-semibold text-mis-navy">{value}</dd></div>)}</dl></Modal> : null}
    {replaceTarget ? <Modal footer={<><Button fullWidth={false} onClick={() => { setReplaceTarget(null); setFile(null); }} variant="outline">{text.cancel}</Button><Button disabled={!file} fullWidth={false} isLoading={busy === replaceTarget.id} onClick={() => void replace()}>{text.replace}</Button></>} onClose={() => { setReplaceTarget(null); setFile(null); }} open title={text.replace}><FileInput accept=".pdf,.jpg,.jpeg,.png,.docx" hint={text.fileHelp} label={text.editFile} onChange={(event) => setFile(event.target.files?.[0] ?? null)} required /></Modal> : null}
    {deleteTarget ? <Modal closeOnBackdrop={busy !== deleteTarget.id} closeOnEscape={busy !== deleteTarget.id} footer={<><Button disabled={busy === deleteTarget.id} fullWidth={false} onClick={closeDeleteDialog} variant="outline">{text.cancel}</Button><Button fullWidth={false} isLoading={busy === deleteTarget.id} onClick={() => void remove()} variant="danger">{text.remove}</Button></>} hideCloseButton={busy === deleteTarget.id} onClose={closeDeleteDialog} open title={text.deleteTitle}><p className="text-sm text-slate-600">{text.deleteMessage.replace('{file}', deleteTarget.fileName)}</p><div className="mt-4"><TextAreaInput label={text.reason} maxLength={500} onChange={(event) => setReason(event.target.value)} value={reason} /></div></Modal> : null}
  </div>;
}
