import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { DateControl } from '../../components/forms/DateControl';
import { Archive, Eye, Pencil, Plus, RotateCcw, Search, UsersRound } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '../../components/common/Button';
import { EmptyState } from '../../components/common/EmptyState';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { StatusBadge, type StatusTone } from '../../components/common/StatusBadge';
import { useToast } from '../../components/common/Toast';
import { useLocalization } from '../../context/LocalizationContext';
import { hrEmployeeService } from '../../features/hr/services/hrEmployeeService';
import { hrMasterDataService } from '../../features/hr/services/hrMasterDataService';
import type { DepartmentOption, EmployeeDetails, EmployeeListItem, EmployeeListStatus, EmployeeOperationalRole, PagedEmployees, SaveEmployeeRequest } from '../../features/hr/types/employee';
import type { MasterDataLookup } from '../../features/hr/types/masterData';
import type { TranslationKey } from '../../localization/translations';
import { getApiErrorMessage } from '../../services/apiClient';

const pageSize = 20;
const emptyPage: PagedEmployees = { items: [], page: 1, pageSize, totalCount: 0, totalPages: 0 };
const roles: EmployeeOperationalRole[] = ['COLLECTOR', 'ADMIN', 'SUPERVISOR'];
const statusOptions: EmployeeListStatus[] = ['Active', 'Inactive', 'OnLeave', 'Suspended', 'Terminated'];
const statusLabels: Record<EmployeeListStatus, TranslationKey> = { Active: 'employeeStatusActive', Inactive: 'employeeStatusInactive', OnLeave: 'employeeStatusOnLeave', Suspended: 'employeeStatusSuspended', Terminated: 'employeeStatusTerminated' };
const statusTones: Record<EmployeeListStatus, StatusTone> = { Active: 'success', Inactive: 'neutral', OnLeave: 'info', Suspended: 'warning', Terminated: 'danger' };
const inputClass = 'mt-2 h-11 w-full rounded-xl border border-mis-border bg-white px-3 text-sm outline-none focus:border-mis-blue focus:shadow-input';
const roleText = { en: { COLLECTOR: 'Collector', ADMIN: 'Admin', SUPERVISOR: 'Supervisor' }, ar: { COLLECTOR: 'محصل', ADMIN: 'إداري', SUPERVISOR: 'مشرف' } } as const;
const extra = {
  en: { position: 'Position', role: 'Employee Role', workStart: 'Work Start Date', fingerprint: 'Fingerprint Enrollment Date', dob: 'Date of Birth', address: 'Address', workEnd: 'Work End Date', archived: 'Archived', archive: 'Archive Employee', restore: 'Restore Employee', reason: 'Archive Reason', archivePrompt: 'Archive Employee?', normal: 'Current workspace', archiveView: 'Archived employees', required: 'Position, role, and work start date are required.', invalidEnd: 'Work End Date must be on or after Work Start Date.', invalidBirth: 'Date of Birth cannot be in the future.' },
  ar: { position: 'المسمى الوظيفي', role: 'الدور الوظيفي', workStart: 'تاريخ بدء العمل', fingerprint: 'تاريخ تسجيل البصمة', dob: 'تاريخ الميلاد', address: 'العنوان', workEnd: 'تاريخ انتهاء العمل', archived: 'مؤرشف', archive: 'أرشفة الموظف', restore: 'استعادة الموظف', reason: 'سبب الأرشفة', archivePrompt: 'أرشفة الموظف؟', normal: 'الموظفون الحاليون', archiveView: 'الموظفون المؤرشفون', required: 'المسمى الوظيفي والدور الوظيفي وتاريخ بدء العمل حقول مطلوبة.', invalidEnd: 'تاريخ انتهاء العمل يجب ألا يسبق تاريخ بدء العمل.', invalidBirth: 'تاريخ الميلاد لا يمكن أن يكون في المستقبل.' },
};
function currentStatus(employee: EmployeeListItem): EmployeeListStatus { return employee.status ?? (employee.isActive ? 'Active' : 'Inactive'); }

function EmployeeForm({ departments, positions, employee, onClose, onSaved }: { departments: DepartmentOption[]; positions: MasterDataLookup[]; employee: EmployeeDetails | null; onClose: () => void; onSaved: () => void }) {
  const { language, t } = useLocalization(); const x = extra[language]; const toast = useToast(); const today = new Date().toISOString().slice(0, 10);
  const [form, setForm] = useState<SaveEmployeeRequest>(() => employee ? { employeeNumber: employee.employeeNumber, fullName: employee.fullName, nationalId: employee.nationalId ?? '', departmentId: employee.departmentId, positionId: employee.positionId ?? '', operationalRole: employee.operationalRole ?? '', workStartDate: employee.workStartDate ?? '', fingerprintEnrollmentDate: employee.fingerprintEnrollmentDate, dateOfBirth: employee.dateOfBirth, address: employee.address, workEndDate: employee.workEndDate, isActive: employee.isActive } : { employeeNumber: '', fullName: '', nationalId: '', departmentId: '', positionId: '', operationalRole: '', workStartDate: '', fingerprintEnrollmentDate: null, dateOfBirth: null, address: null, workEndDate: null, isActive: true });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const formId = 'employee-form';
  const set = <K extends keyof SaveEmployeeRequest>(key: K, value: SaveEmployeeRequest[K]) => setForm(current => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); if (!form.employeeNumber.trim() || form.fullName.trim().length < 2 || !form.departmentId || !form.positionId || !form.operationalRole || !form.workStartDate) { setError(x.required); return; } if (form.dateOfBirth && form.dateOfBirth > today) { setError(x.invalidBirth); return; } if (form.workEndDate && form.workEndDate < form.workStartDate) { setError(x.invalidEnd); return; } setSaving(true); try { employee ? await hrEmployeeService.updateEmployee(employee.id, form) : await hrEmployeeService.createEmployee(form); toast.success(t(employee ? 'employeeUpdatedSuccess' : 'employeeCreatedSuccess')); onSaved(); } catch (requestError) { const message = getApiErrorMessage(requestError, t('saveEmployeeError')); setError(message); toast.error(message); } finally { setSaving(false); } }
  const label = (text: string, required = false) => <>{text}{required ? <span className="ms-1 text-red-500">*</span> : null}</>;
  return <Modal closeOnBackdrop={!saving} closeOnEscape={!saving} footer={<><Button disabled={saving} fullWidth={false} onClick={onClose} size="md" variant="outline">{t('cancel')}</Button><Button form={formId} fullWidth={false} isLoading={saving} size="md" type="submit">{t('saveChanges')}</Button></>} hideCloseButton={saving} onClose={onClose} open size="xl" title={t(employee ? 'editEmployee' : 'addEmployee')}>
    <form className="grid gap-4 sm:grid-cols-2" id={formId} onSubmit={submit}>{error ? <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</div> : null}
      <label className="text-sm font-semibold text-slate-700">{label(t('employeeId'), true)}<input className={inputClass} maxLength={50} onChange={e => set('employeeNumber', e.target.value)} required value={form.employeeNumber} /></label>
      <label className="text-sm font-semibold text-slate-700">{label(t('employeeName'), true)}<input className={inputClass} maxLength={160} onChange={e => set('fullName', e.target.value)} required value={form.fullName} /></label>
      <label className="text-sm font-semibold text-slate-700">{label(language === 'ar' ? 'الرقم القومي' : 'National ID', true)}<input className={inputClass} inputMode="numeric" maxLength={14} minLength={14} onChange={e => set('nationalId', e.target.value)} pattern="[0-9]{14}" required title={language === 'ar' ? 'أدخل 14 رقمًا فقط' : 'Enter exactly 14 digits'} value={form.nationalId} /></label>
      <label className="text-sm font-semibold text-slate-700">{label(t('department'), true)}<ProfessionalSelect className={inputClass} onChange={e => set('departmentId', e.target.value)} required value={form.departmentId}><option value="">{t('selectDepartment')}</option>{departments.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</ProfessionalSelect></label>
      <label className="text-sm font-semibold text-slate-700">{label(x.position, true)}<ProfessionalSelect className={inputClass} onChange={e => set('positionId', e.target.value)} required value={form.positionId}><option value="">—</option>{positions.filter(item => item.isActive || item.id === form.positionId).map(item => <option key={item.id} value={item.id}>{language === 'ar' ? item.nameArabic ?? item.nameEnglish : item.nameEnglish}</option>)}</ProfessionalSelect></label>
      <label className="text-sm font-semibold text-slate-700">{label(x.role, true)}<ProfessionalSelect className={inputClass} onChange={e => set('operationalRole', e.target.value as EmployeeOperationalRole)} required value={form.operationalRole}><option value="">—</option>{roles.map(role => <option key={role} value={role}>{roleText[language][role]}</option>)}</ProfessionalSelect></label>
      <label className="text-sm font-semibold text-slate-700">{label(x.workStart, true)}<DateControl className={inputClass} onChange={e => set('workStartDate', e.target.value)} required  value={form.workStartDate} /></label>
      <label className="text-sm font-semibold text-slate-700">{x.fingerprint}<DateControl className={inputClass} onChange={e => set('fingerprintEnrollmentDate', e.target.value || null)}  value={form.fingerprintEnrollmentDate ?? ''} /></label>
      <label className="text-sm font-semibold text-slate-700">{x.dob}<DateControl className={inputClass} max={today} onChange={e => set('dateOfBirth', e.target.value || null)}  value={form.dateOfBirth ?? ''} /></label>
      <label className="text-sm font-semibold text-slate-700">{x.workEnd}<DateControl className={inputClass} min={form.workStartDate || undefined} onChange={e => set('workEndDate', e.target.value || null)}  value={form.workEndDate ?? ''} /></label>
      <label className="text-sm font-semibold text-slate-700">{t('status')}<ProfessionalSelect className={inputClass} onChange={e => set('isActive', e.target.value === 'active')} value={form.isActive ? 'active' : 'inactive'}><option value="active">{t('active')}</option><option value="inactive">{t('inactive')}</option></ProfessionalSelect></label>
      <label className="text-sm font-semibold text-slate-700 sm:col-span-2">{x.address}<textarea className="mt-2 min-h-20 w-full rounded-xl border border-mis-border p-3 text-sm outline-none focus:border-mis-blue" maxLength={500} onChange={e => set('address', e.target.value || null)} value={form.address ?? ''} /></label>
    </form></Modal>;
}

export function HrEmployeesPage() {
  const { language, t } = useLocalization(); const x = extra[language]; const toast = useToast();
  const [data, setData] = useState(emptyPage); const [departments, setDepartments] = useState<DepartmentOption[]>([]); const [positions, setPositions] = useState<MasterDataLookup[]>([]); const [searchInput, setSearchInput] = useState(''); const [search, setSearch] = useState(''); const [departmentId, setDepartmentId] = useState(''); const [status, setStatus] = useState('all'); const [role, setRole] = useState(''); const [archived, setArchived] = useState(false); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [formEmployee, setFormEmployee] = useState<EmployeeDetails | null | undefined>(undefined); const [archiveTarget, setArchiveTarget] = useState<EmployeeListItem | null>(null); const [archiveReason, setArchiveReason] = useState('');
  useEffect(() => { const timer = window.setTimeout(() => { setSearch(searchInput.trim()); setPage(1); }, 350); return () => window.clearTimeout(timer); }, [searchInput]);
  useEffect(() => { void Promise.all([hrEmployeeService.getDepartments(), hrMasterDataService.getLookup('positions', true)]).then(([d, p]) => { setDepartments(d); setPositions(p); }).catch(reason => setError(getApiErrorMessage(reason, t('loadDepartmentsError')))); }, [t]);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await hrEmployeeService.getEmployees({ archived, departmentId, page, pageSize, role, search, status })); } catch (reason) { setError(getApiErrorMessage(reason, t('loadEmployeesError'))); } finally { setLoading(false); } }, [archived, departmentId, page, role, search, status, t]); useEffect(() => { void load(); }, [load]);
  async function edit(employee: EmployeeListItem) { try { setFormEmployee(await hrEmployeeService.getEmployee(employee.id)); } catch (reason) { toast.error(getApiErrorMessage(reason, t('loadEmployeeError'))); } }
  async function archiveEmployee() { if (!archiveTarget || archiveReason.trim().length < 2) return; try { await hrEmployeeService.archiveEmployee(archiveTarget.id, archiveReason.trim()); toast.success(x.archive); setArchiveTarget(null); setArchiveReason(''); void load(); } catch (reason) { toast.error(getApiErrorMessage(reason, t('saveEmployeeError'))); } }
  async function restore(employee: EmployeeListItem) { if (!window.confirm(`${x.restore}: ${employee.fullName}?`)) return; try { await hrEmployeeService.restoreEmployee(employee.id); toast.success(x.restore); void load(); } catch (reason) { toast.error(getApiErrorMessage(reason, t('saveEmployeeError'))); } }
  return <div className="mx-auto max-w-7xl"><PageHeader actions={<Button fullWidth={false} leftIcon={<Plus className="h-4 w-4" />} onClick={() => setFormEmployee(null)} size="md">{t('addEmployee')}</Button>} description={t('employeesSubtitle')} eyebrow={t('hrDepartment')} title={t('employees')} />
    <section className="overflow-hidden rounded-2xl border border-mis-border bg-white shadow-sm"><div className="grid gap-3 border-b border-mis-border p-4 lg:grid-cols-[minmax(220px,1fr)_180px_150px_150px_170px]"><label className="relative"><Search className="absolute start-3 top-3 h-5 w-5 text-slate-400" /><input className="h-11 w-full rounded-xl border border-mis-border pe-3 ps-10 text-sm" onChange={e => setSearchInput(e.target.value)} placeholder={t('searchEmployee')} value={searchInput} /></label><ProfessionalSelect className="h-11 rounded-xl border border-mis-border px-3 text-sm" onChange={e => { setDepartmentId(e.target.value); setPage(1); }} value={departmentId}><option value="">{t('allDepartments')}</option>{departments.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</ProfessionalSelect><ProfessionalSelect className="h-11 rounded-xl border border-mis-border px-3 text-sm" onChange={e => { setRole(e.target.value); setPage(1); }} value={role}><option value="">{x.role}</option>{roles.map(item => <option key={item} value={item}>{roleText[language][item]}</option>)}</ProfessionalSelect><ProfessionalSelect className="h-11 rounded-xl border border-mis-border px-3 text-sm" onChange={e => { setStatus(e.target.value); setPage(1); }} value={status}><option value="all">{t('allStatuses')}</option>{statusOptions.map(item => <option key={item} value={item.toLowerCase()}>{t(statusLabels[item])}</option>)}</ProfessionalSelect><ProfessionalSelect className="h-11 rounded-xl border border-mis-border px-3 text-sm" onChange={e => { setArchived(e.target.value === 'true'); setPage(1); }} value={String(archived)}><option value="false">{x.normal}</option><option value="true">{x.archiveView}</option></ProfessionalSelect></div>
      {error ? <div className="p-5"><ErrorState message={error} onRetry={() => void load()} title={t('loadEmployeesError')} /></div> : loading ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : !data.items.length ? <EmptyState description={t('adjustFilters')} icon={<UsersRound />} title={t('noEmployeesFound')} /> : <><div className="overflow-x-auto"><table className="w-full min-w-[980px]"><thead className="bg-mis-surface text-xs uppercase text-slate-500"><tr>{[t('employeeId'), t('employeeName'), t('department'), x.position, x.role, t('status'), t('actions')].map(v => <th className="px-5 py-4 text-start" key={v}>{v}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(employee => { const s = currentStatus(employee); return <tr key={employee.id}><td className="px-5 py-4 font-semibold text-mis-navy">{employee.employeeNumber}</td><td className="px-5 py-4">{employee.fullName}</td><td className="px-5 py-4">{employee.departmentName}</td><td className="px-5 py-4">{employee.positionName ?? '—'}</td><td className="px-5 py-4">{employee.operationalRole ? roleText[language][employee.operationalRole] : '—'}</td><td className="px-5 py-4">{employee.isArchived ? <StatusBadge tone="neutral">{x.archived}</StatusBadge> : <StatusBadge dot tone={statusTones[s]}>{t(statusLabels[s])}</StatusBadge>}</td><td className="px-5 py-4"><div className="flex gap-1"><Link className="rounded-lg p-2 text-mis-primary hover:bg-mis-pale" to={`/hr/employees/${employee.id}`}><Eye className="h-4 w-4" /></Link><button className="rounded-lg p-2 text-mis-primary hover:bg-mis-pale" onClick={() => void edit(employee)}><Pencil className="h-4 w-4" /></button>{employee.isArchived ? <button className="rounded-lg p-2 text-emerald-700 hover:bg-emerald-50" onClick={() => void restore(employee)}><RotateCcw className="h-4 w-4" /></button> : <button className="rounded-lg p-2 text-amber-700 hover:bg-amber-50" onClick={() => setArchiveTarget(employee)}><Archive className="h-4 w-4" /></button>}</div></td></tr>; })}</tbody></table></div><Pagination onPageChange={setPage} page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} /></>}
      {formEmployee !== undefined ? <EmployeeForm departments={departments} employee={formEmployee} onClose={() => setFormEmployee(undefined)} onSaved={() => { setFormEmployee(undefined); void load(); }} positions={positions} /> : null}
      {archiveTarget ? <Modal footer={<><Button fullWidth={false} onClick={() => setArchiveTarget(null)} variant="outline">{t('cancel')}</Button><Button disabled={archiveReason.trim().length < 2} fullWidth={false} onClick={() => void archiveEmployee()} variant="danger">{x.archive}</Button></>} onClose={() => setArchiveTarget(null)} open title={x.archivePrompt}><p className="mb-4 font-semibold">{archiveTarget.fullName}</p><label className="text-sm font-semibold">{x.reason} *<textarea className="mt-2 min-h-24 w-full rounded-xl border border-mis-border p-3" maxLength={500} onChange={e => setArchiveReason(e.target.value)} value={archiveReason} /></label></Modal> : null}
    </section></div>;
}
