import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { ArrowLeft, Download, Eye, FileCheck2, HandCoins, MessageSquarePlus, Paperclip, Phone, ShieldCheck } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button } from '../../components/common/Button';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { CollectionStatus, KpiCard, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { CaseDetails, CollectionAttachment } from '../../features/collections/types/collections';
import { useAuth } from '../../context/AuthContext';
import { ProfessionalDateInput } from '../../components/forms/ProfessionalDateInput';
import { FileInput } from '../../components/forms/FileInput';

type Action = 'activity' | 'promise' | 'payment';
export function CollectionCaseDetailsPage() {
  const { id = '' } = useParams(); const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const { user } = useAuth(); const [data, setData] = useState<CaseDetails>(); const [attachments, setAttachments] = useState<CollectionAttachment[]>([]); const [error, setError] = useState(false); const [action, setAction] = useState<Action>('activity'); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = () => { setError(false); Promise.all([collectionsService.caseDetails(id), collectionsService.attachments(id)]).then(([details, files]) => { setData(details); setAttachments(files); }).catch(() => setError(true)); }; useEffect(load, [id]);
  const revealAllowed = user?.roles.some(role => ['Admin', 'CollectionsOperationsManager', 'CollectionsSupervisor', 'CollectionsAuditor'].includes(role));
  const reveal = async () => { setSaving(true); setMessage(''); try { setData(await collectionsService.revealSensitive(id)); setMessage(ct('revealed')); } catch { setMessage(ct('saveError')); } finally { setSaving(false); } };
  if (error) return <ErrorState title={ct('loadError')} onRetry={load} />; if (!data) return <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div>;
  return <div><PageHeader breadcrumbs={<Link to="/collections/cases" className="inline-flex items-center gap-2 text-sm font-semibold text-mis-primary"><ArrowLeft className="h-4 w-4 rtl:rotate-180" />{ct('backToCases')}</Link>} eyebrow={`${data.clientName} · ${data.portfolioName}`} title={`${ct('case360')} — ${data.caseNumber}`} description={<span>{data.customerName} · <span data-bidi="ltr">{data.accountReference}</span></span>} actions={<div className="flex items-center gap-2"><CollectionStatus value={data.priority} />{revealAllowed && !data.sensitiveValuesRevealed ? <button disabled={saving} onClick={reveal} className="inline-flex items-center gap-2 rounded-xl border border-mis-primary px-4 py-2.5 text-sm font-bold text-mis-primary hover:bg-mis-pale disabled:opacity-50"><Eye className="h-4 w-4" />{ct('reveal')}</button> : null}</div>} />
    {message && <div className={`mb-5 rounded-xl border px-4 py-3 text-sm ${message === ct('revealed') ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-rose-200 bg-rose-50 text-rose-800'}`}>{message}</div>}
    <section className="mb-5 rounded-2xl border border-blue-200 bg-gradient-to-r from-blue-50 to-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-mis-primary">{ct('nextBestAction')}</p><div className="mt-2 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-mis-navy">{ct(data.recommendedActionCode)}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{data.recommendedActionReason}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-mis-primary shadow-sm" data-bidi="ltr">{data.recommendedActionCode}</span></div></section>
    <section className="grid gap-5 xl:grid-cols-2"><Panel title={ct('customerIdentity')} icon={<ShieldCheck className="h-5 w-5" />}><dl className="grid gap-4 sm:grid-cols-2"><Info label={ct('customer')} value={`${data.customerName} (${data.customerCode})`} /><Info label={ct('nationalId')} value={data.nationalId} bidi /><Info label={ct('phone')} value={data.primaryPhone} bidi /><Info label={ct('alternatePhone')} value={data.alternatePhone || '—'} bidi /><Info label={ct('address')} value={data.address || '—'} wide /><Info label={ct('collector')} value={data.assignedCollectorName || '—'} /></dl></Panel><Panel title={ct('financialPosition')} icon={<HandCoins className="h-5 w-5" />}><div className="grid gap-3 sm:grid-cols-2"><KpiCard label={ct('balance')} value={f.money(data.outstandingBalance)} /><KpiCard label={ct('overdue')} value={f.money(data.overdueBalance)} accent="red" /><KpiCard label={ct('originalAmount')} value={f.money(data.originalAmount)} /><KpiCard label={ct('dpdBucket')} value={`${data.daysPastDue} · ${data.bucket}`} accent="amber" /></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Info label={ct('accountReference')} value={data.accountReference} bidi /><Info label={ct('contractReference')} value={data.contractReference || '—'} bidi /><Info label={ct('product')} value={data.productType || '—'} /><Info label={ct('feesPenalties')} value={f.money(data.fees + data.penalties)} bidi /></dl></Panel></section>
    <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(340px,.6fr)]"><Panel title={ct('timeline')} icon={<Phone className="h-5 w-5" />}>{data.timeline.length ? <ol className="space-y-5">{data.timeline.map(item => <li key={item.id} className="relative border-s-2 border-mis-border ps-5"><span className="absolute -start-[7px] top-1.5 h-3 w-3 rounded-full bg-mis-blue" /><div className="flex flex-wrap items-start justify-between gap-2"><p className="font-bold text-mis-navy">{item.type}</p><time className="text-xs text-slate-500" data-bidi="ltr">{f.dateTime(item.createdAt)}</time></div>{item.result && <p className="mt-1 text-sm font-semibold text-mis-primary">{item.result}</p>}{item.notes && <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.notes}</p>}<p className="mt-2 text-xs text-slate-400">{item.createdBy}</p></li>)}</ol> : <p className="text-sm text-slate-500">{ct('noActivity')}</p>}</Panel><Panel title={action === 'activity' ? ct('addActivity') : action === 'promise' ? ct('addPromise') : ct('submitCollection')} icon={action === 'activity' ? <MessageSquarePlus className="h-5 w-5" /> : <FileCheck2 className="h-5 w-5" />}><div className="mb-5 grid grid-cols-3 rounded-xl bg-slate-100 p-1"><ActionTab active={action === 'activity'} onClick={() => setAction('activity')}>{ct('addActivity')}</ActionTab><ActionTab active={action === 'promise'} onClick={() => setAction('promise')}>{ct('promises')}</ActionTab><ActionTab active={action === 'payment'} onClick={() => setAction('payment')}>{ct('payments')}</ActionTab></div><ActionForm type={action} caseId={id} onSaved={async () => { setMessage(ct('saved')); setData(await collectionsService.caseDetails(id)); }} setSaving={setSaving} saving={saving} /></Panel></section>
    <section className="mt-6"><Panel title={ct('attachments')} icon={<Paperclip className="h-5 w-5" />}><AttachmentForm caseId={id} payments={data.payments} saving={saving} setSaving={setSaving} onSaved={async () => setAttachments(await collectionsService.attachments(id))} />{attachments.length ? <div className="mt-5 divide-y divide-mis-border rounded-xl border border-mis-border">{attachments.map(file => <div key={file.id} className="flex items-center gap-4 px-4 py-3"><Paperclip className="h-5 w-5 text-mis-primary" /><div className="min-w-0 flex-1"><p className="truncate font-semibold text-mis-navy">{file.originalFileName}</p><p className="mt-1 text-xs text-slate-500">{ct(file.category)} · {(file.fileSize / 1024).toFixed(1)} KB · {file.uploadedBy}</p></div><button onClick={() => collectionsService.downloadAttachment(file.id, file.originalFileName)} className="rounded-lg p-2 text-mis-primary hover:bg-mis-pale"><Download className="h-5 w-5" /></button></div>)}</div> : <p className="mt-5 text-sm text-slate-500">{ct('noAttachments')}</p>}</Panel></section>
  </div>;
}

function ActionForm({ type, caseId, onSaved, saving, setSaving }: { type: Action; caseId: string; onSaved: () => Promise<void>; saving: boolean; setSaving: (v: boolean) => void }) {
  const { ct } = useCollectionsLocalization(); const [error, setError] = useState(''); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); const form = new FormData(event.currentTarget); try { if (type === 'activity') await collectionsService.createActivity(caseId, { activityType: String(form.get('activityType')), result: String(form.get('result') || ''), notes: String(form.get('notes') || ''), channel: String(form.get('channel') || ''), nextFollowUpAt: String(form.get('nextFollowUpAt') || '') || undefined }); else if (type === 'promise') await collectionsService.createPromise(caseId, { promisedAmount: Number(form.get('amount')), promiseDate: String(form.get('date')), channel: String(form.get('channel')), notes: String(form.get('notes') || '') }); else await collectionsService.submitPayment(caseId, { amount: Number(form.get('amount')), paymentDate: String(form.get('date')), method: String(form.get('method')), referenceNumber: String(form.get('reference')) }); event.currentTarget.reset(); await onSaved(); } catch { setError(ct('saveError')); } finally { setSaving(false); } };
  return <form className="space-y-4" onSubmit={submit}>{type === 'activity' ? <><Field label={ct('activityType')}><ProfessionalSelect name="activityType" required className="field"><option value="CALL">CALL</option><option value="SMS">SMS</option><option value="EMAIL">EMAIL</option><option value="NOTE">NOTE</option></ProfessionalSelect></Field><Field label={ct('result')}><input name="result" maxLength={100} className="field" /></Field><Field label={ct('channel')}><input name="channel" maxLength={40} className="field" /></Field><Field label={ct('nextFollowUp')}><ProfessionalDateInput name="nextFollowUpAt" mode="datetime" /></Field></> : type === 'promise' ? <><Field label={ct('amount')}><input name="amount" type="number" min="0.01" step="0.01" required className="field" /></Field><Field label={ct('promiseDate')}><ProfessionalDateInput name="date" required /></Field><Field label={ct('channel')}><ProfessionalSelect name="channel" required className="field"><option value="CALL">CALL</option><option value="VISIT">VISIT</option><option value="WHATSAPP">WHATSAPP</option></ProfessionalSelect></Field></> : <><Field label={ct('amount')}><input name="amount" type="number" min="0.01" step="0.01" required className="field" /></Field><Field label={ct('paymentDate')}><ProfessionalDateInput name="date" required /></Field><Field label={ct('method')}><ProfessionalSelect name="method" required className="field"><option value="CASH">CASH</option><option value="BANK_TRANSFER">BANK TRANSFER</option><option value="CARD">CARD</option></ProfessionalSelect></Field><Field label={ct('reference')}><input name="reference" required maxLength={160} className="field" /></Field></>} {type !== 'payment' && <Field label={ct('notes')}><textarea name="notes" rows={3} maxLength={2000} className="field" /></Field>}{error && <p className="text-sm text-rose-700">{error}</p>}<button disabled={saving} className="w-full rounded-xl bg-mis-primary px-4 py-3 font-bold text-white hover:bg-mis-deep disabled:opacity-50">{saving ? ct('loading') : type === 'activity' ? ct('saveActivity') : type === 'promise' ? ct('submitPromise') : ct('submit')}</button></form>;
}
function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <article className="rounded-2xl border border-mis-border bg-white p-6 shadow-sm"><h2 className="mb-5 flex items-center gap-2 text-lg font-bold text-mis-navy">{icon}{title}</h2>{children}</article>; }
function Info({ label, value, wide = false, bidi = false }: { label: string; value: string; wide?: boolean; bidi?: boolean }) { return <div className={wide ? 'sm:col-span-2' : ''}><dt className="text-xs font-semibold text-slate-500">{label}</dt><dd className="mt-1 break-words font-semibold text-mis-navy" {...(bidi ? { 'data-bidi': 'ltr' } : {})}>{value}</dd></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-600">{label}</span>{children}</label>; }
function ActionTab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} className={`rounded-lg px-2 py-2 text-xs font-bold ${active ? 'bg-white text-mis-primary shadow-sm' : 'text-slate-500'}`}>{children}</button>; }
function AttachmentForm({ caseId, payments, saving, setSaving, onSaved }: { caseId: string; payments: CaseDetails['payments']; saving: boolean; setSaving: (value: boolean) => void; onSaved: () => Promise<void> }) { const { ct } = useCollectionsLocalization(); const [category, setCategory] = useState('CASE_DOCUMENT'); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const file = form.get('file'); if (!(file instanceof File) || !file.size) return; setSaving(true); try { await collectionsService.uploadAttachment(caseId, category, file, category === 'PAYMENT_PROOF' ? String(form.get('paymentId')) : undefined); formElement.reset(); setCategory('CASE_DOCUMENT'); await onSaved(); } finally { setSaving(false); } }; return <form onSubmit={submit} className="grid items-end gap-3 md:grid-cols-[220px_minmax(220px,1fr)_auto]"><label className="text-sm font-semibold text-slate-700">{ct('category')}<ProfessionalSelect name="category" value={category} onChange={event => setCategory(event.target.value)} className="field mt-2"><option value="CASE_DOCUMENT">{ct('CASE_DOCUMENT')}</option>{payments.length > 0 && <option value="PAYMENT_PROOF">{ct('PAYMENT_PROOF')}</option>}<option value="VISIT_EVIDENCE">{ct('VISIT_EVIDENCE')}</option><option value="COMPLAINT_DOCUMENT">{ct('COMPLAINT_DOCUMENT')}</option><option value="SETTLEMENT_DOCUMENT">{ct('SETTLEMENT_DOCUMENT')}</option></ProfessionalSelect></label>{category === 'PAYMENT_PROOF' && <label className="text-sm font-semibold text-slate-700">{ct('relatedPayment')}<ProfessionalSelect required name="paymentId" aria-label={ct('relatedPayment')} className="field mt-2"><option value="">{ct('relatedPayment')}</option>{payments.map(payment => <option key={payment.id} value={payment.id}>{payment.referenceNumber} · {payment.amount}</option>)}</ProfessionalSelect></label>}<FileInput required name="file" accept=".pdf,.jpg,.jpeg,.png" label={ct('file')} /><Button disabled={saving} fullWidth={false} size="md" type="submit">{ct('uploadAttachment')}</Button></form>; }
