import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { type FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { ProfessionalDateInput } from '../../components/forms/ProfessionalDateInput';
import { useAuth } from '../../context/AuthContext';
import { CollectionStatus, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { CollectionCase, CollectorLookup, FieldVisit, PagedResult } from '../../features/collections/types/collections';

export function CollectionVisitsPage() {
  const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const { user } = useAuth();
  const canPlan = user?.roles.some(role => ['Admin', 'CollectionsOperationsManager', 'CollectionsSupervisor'].includes(role));
  const [data, setData] = useState<PagedResult<FieldVisit>>(); const [cases, setCases] = useState<CollectionCase[]>([]); const [collectors, setCollectors] = useState<CollectorLookup[]>([]); const [page, setPage] = useState(1); const [status] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = () => collectionsService.visits({ page, pageSize: 20, status }).then(setData).catch(() => setError(ct('loadError')));
  useEffect(() => { void load(); }, [page, status]);
  useEffect(() => { if (canPlan) void Promise.all([collectionsService.cases({ pageSize: 100, status: 'ACTIVE' }), collectionsService.collectors()]).then(([casePage, users]) => { setCases(casePage.items); setCollectors(users); }); }, [canPlan]);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; setSaving(true); setError(''); const form = new FormData(formElement); try { await collectionsService.createVisit({ caseId: String(form.get('caseId')), collectorId: String(form.get('collectorId')), scheduledAt: new Date(String(form.get('scheduledAt'))).toISOString(), address: String(form.get('address')), governorate: String(form.get('governorate') || ''), area: String(form.get('area') || '') }); formElement.reset(); load(); } catch { setError(ct('saveError')); } finally { setSaving(false); } };
  const complete = async (item: FieldVisit) => { const result = window.prompt(ct('visitResult'))?.trim(); if (!result) return; setSaving(true); try { await collectionsService.completeVisit(item.id, result); load(); } finally { setSaving(false); } };
  return <div><PageHeader eyebrow={ct('collections')} title={ct('visits')} description={ct('visitsSubtitle')} />
    {canPlan && <details className="mb-6 rounded-2xl border border-mis-border bg-white p-5 shadow-sm"><summary className="cursor-pointer font-bold text-mis-primary">{ct('scheduleVisit')}</summary><form onSubmit={create} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label={ct('cases')}><ProfessionalSelect required name="caseId" className="field"><option value="">—</option>{cases.map(item => <option key={item.id} value={item.id}>{item.caseNumber} — {item.customerName}</option>)}</ProfessionalSelect></Field><Field label={ct('collector')}><ProfessionalSelect required name="collectorId" className="field"><option value="">—</option>{collectors.map(item => <option key={item.id} value={item.id}>{item.name} ({item.activeWorkload})</option>)}</ProfessionalSelect></Field><Field label={ct('scheduledAt')}><ProfessionalDateInput required name="scheduledAt" mode="datetime" /></Field><Field label={ct('address')}><input required name="address" maxLength={600} className="field" /></Field><Field label="Governorate / المحافظة"><input name="governorate" maxLength={100} className="field" /></Field><Field label="Area / المنطقة"><input name="area" maxLength={100} className="field" /></Field><button disabled={saving} className="rounded-xl bg-mis-primary px-4 py-3 font-bold text-white md:col-span-2 xl:col-span-3">{saving ? ct('loading') : ct('scheduleVisit')}</button></form></details>}
    {error && !data ? <ErrorState title={error} /> : !data ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : <div className="overflow-hidden rounded-2xl border border-mis-border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50"><tr>{[ct('customer'), ct('collector'), ct('scheduledAt'), ct('address'), ct('status'), ''].map((heading, index) => <th key={`${heading}${index}`} className="px-5 py-4 text-start text-xs text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(item => <tr key={item.id}><td className="px-5 py-4"><Link to={`/collections/cases/${item.caseId}`} className="font-bold text-mis-primary">{item.customerName}</Link><p className="text-xs text-slate-500" data-bidi="ltr">{item.caseNumber}</p></td><td className="px-5 py-4">{item.collectorName}</td><td className="px-5 py-4" data-bidi="ltr">{f.dateTime(item.scheduledAt)}</td><td className="max-w-xs px-5 py-4">{item.address}</td><td className="px-5 py-4"><CollectionStatus value={item.status} /></td><td className="px-5 py-4">{!['COMPLETED', 'CANCELLED'].includes(item.status) && (item.collectorId === user?.id || canPlan) ? <button disabled={saving} onClick={() => complete(item)} className="rounded-lg border border-mis-primary px-3 py-2 text-xs font-bold text-mis-primary">{ct('completeVisit')}</button> : null}</td></tr>)}</tbody></table>{!data.items.length && <p className="p-12 text-center text-slate-500">{ct('noVisits')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>}
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-sm font-semibold text-slate-600">{label}</span>{children}</label>; }
