import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { DateControl } from '../../components/forms/DateControl';
import { Check, ClipboardCheck, Eye, PiggyBank, Search, WalletCards, X } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { Button } from '../../components/common/Button';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { CollectionStatus, KpiCard, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { PagedResult, PaymentDetails, PaymentFilterOptions, PaymentItem, PaymentSummary } from '../../features/collections/types/collections';

const copy = {
  en: { subtitle: 'Authorized payments across all banks and installment companies.', todayAmount: "Today's Collected Amount", todayCount: 'Collection Transactions Today', pending: 'Pending Review', search: 'Search customer, case, account or reference...', organization: 'Bank / Company', allOrganizations: 'All Banks / Companies', collector: 'Collector', allCollectors: 'All Collectors', status: 'Status', date: 'Collection Date', customer: 'Customer', amount: 'Amount', method: 'Payment Method', details: 'Details', view: 'View Details', paymentDetails: 'Collection Details', case: 'Case', account: 'Account Reference', portfolio: 'Portfolio', reference: 'Reference Number', submitted: 'Created / Submitted By', reviewed: 'Reviewed / Confirmed By', submittedAt: 'Submitted At', reviewedAt: 'Reviewed At', rejection: 'Rejection Reason', close: 'Close' },
  ar: { subtitle: 'المدفوعات المصرح بها عبر جميع البنوك وشركات التقسيط.', todayAmount: 'تحصيل اليوم', todayCount: 'عدد عمليات اليوم', pending: 'بانتظار المراجعة', search: 'ابحث بالعميل أو الحالة أو الحساب أو الرقم المرجعي...', organization: 'البنك / الشركة', allOrganizations: 'كل البنوك / الشركات', collector: 'المحصل', allCollectors: 'كل المحصلين', status: 'الحالة', date: 'تاريخ التحصيل', customer: 'العميل', amount: 'المبلغ', method: 'وسيلة السداد', details: 'التفاصيل', view: 'عرض التفاصيل', paymentDetails: 'تفاصيل التحصيل', case: 'الحالة', account: 'مرجع الحساب', portfolio: 'المحفظة', reference: 'الرقم المرجعي', submitted: 'تم الإنشاء / التقديم بواسطة', reviewed: 'تمت المراجعة / التأكيد بواسطة', submittedAt: 'وقت التقديم', reviewedAt: 'وقت المراجعة', rejection: 'سبب الرفض', close: 'إغلاق' },
};

export function CollectionPaymentsPage() {
  const { ct, language } = useCollectionsLocalization();
  const t = copy[language]; const f = useCollectionFormat(); const { user } = useAuth();
  const canReview = user?.roles.some(x => ['Admin', 'CollectionsOperationsManager', 'CollectionsReviewer'].includes(x));
  const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [organizationId, setOrganizationId] = useState(''); const [collectorId, setCollectorId] = useState(''); const [status, setStatus] = useState(''); const [date, setDate] = useState(''); const [page, setPage] = useState(1);
  const [data, setData] = useState<PagedResult<PaymentItem>>(); const [summary, setSummary] = useState<PaymentSummary>(); const [options, setOptions] = useState<PaymentFilterOptions>({ organizations: [], collectors: [] }); const [selected, setSelected] = useState<PaymentDetails>(); const [detailsLoading, setDetailsLoading] = useState(false); const [error, setError] = useState(false); const [saving, setSaving] = useState(false); const [rejectOpen, setRejectOpen] = useState(false); const [rejectReason, setRejectReason] = useState('');

  const load = useCallback(() => { setError(false); collectionsService.payments({ page, pageSize: 20, search: query, organizationId, collectorId, status, from: date, to: date }).then(setData).catch(() => setError(true)); }, [collectorId, date, organizationId, page, query, status]);
  const loadHeader = useCallback(() => Promise.all([collectionsService.paymentSummary(), collectionsService.paymentFilterOptions()]).then(([s, o]) => { setSummary(s); setOptions(o); }).catch(() => setError(true)), []);
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); }, 350); return () => clearTimeout(timer); }, [search]);
  useEffect(load, [load]); useEffect(() => { void loadHeader(); }, [loadHeader, language]);
  const change = (setter: (value: string) => void, value: string) => { setter(value); setPage(1); };
  const openDetails = async (id: string) => { setDetailsLoading(true); try { setSelected(await collectionsService.payment(id)); } finally { setDetailsLoading(false); } };
  const review = async (approve: boolean, reason?: string) => { if (!selected) return; if (!approve && !reason?.trim()) return; setSaving(true); try { await collectionsService.reviewPayment(selected.id, approve, reason?.trim()); setSelected(await collectionsService.payment(selected.id)); setRejectOpen(false); setRejectReason(''); load(); await loadHeader(); } finally { setSaving(false); } };
  const rows = selected ? [[t.customer, selected.customerName], [t.case, selected.caseNumber], [t.account, selected.accountReference], [t.organization, selected.organizationName], [t.portfolio, selected.portfolioName], [t.collector, selected.collectorName], [t.amount, `${f.money(selected.amount)} (${selected.currencyCode})`], [t.date, selected.paymentDate], [t.method, ct(selected.method)], [t.reference, selected.referenceNumber], [t.status, ct(selected.status)], [t.submitted, selected.submittedBy], [t.submittedAt, f.dateTime(selected.submittedAt)], [t.reviewed, selected.verifiedBy ?? '—'], [t.reviewedAt, selected.verifiedAt ? f.dateTime(selected.verifiedAt) : '—'], ...(selected.rejectionReason ? [[t.rejection, selected.rejectionReason]] : [])] : [];

  return <div><PageHeader eyebrow={ct('collections')} title={ct('payments')} description={t.subtitle} />
    <div className="mb-4 grid gap-3 sm:grid-cols-3"><KpiCard icon={<PiggyBank />} label={t.todayAmount} value={summary ? f.money(summary.todayCollectedAmount) : '—'} accent="green" /><KpiCard icon={<WalletCards />} label={t.todayCount} value={summary ? f.number(summary.todayTransactionCount) : '—'} /><KpiCard icon={<ClipboardCheck />} label={t.pending} value={summary ? f.number(summary.pendingReview) : '—'} accent="amber" /></div>
    <div className="mb-4 rounded-2xl border border-mis-border bg-white p-3 shadow-sm"><div className="module-filter-grid">
      <label><span className="mb-1 block text-xs font-semibold text-slate-600">{ct('search')}</span><span className="relative block"><Search className="absolute top-3 h-5 w-5 text-slate-400" style={{ insetInlineStart: '0.8rem' }} /><input className="field h-11 ps-11" placeholder={t.search} value={search} onChange={e => setSearch(e.target.value)} /></span></label>
      <Filter label={t.organization}><ProfessionalSelect className="field h-11" value={organizationId} onChange={e => change(setOrganizationId, e.target.value)}><option value="">{t.allOrganizations}</option>{options.organizations.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></Filter>
      <Filter label={t.collector}><ProfessionalSelect className="field h-11" value={collectorId} onChange={e => change(setCollectorId, e.target.value)}><option value="">{t.allCollectors}</option>{options.collectors.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></Filter>
      <Filter label={t.status}><ProfessionalSelect className="field h-11" value={status} onChange={e => change(setStatus, e.target.value)}><option value="">{ct('allStatuses')}</option>{['SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'REVERSED'].map(x => <option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></Filter>
      <Filter label={t.date}><DateControl className="field h-11" value={date} onChange={e => change(setDate, e.target.value)} /></Filter>
    </div></div>
    {error ? <ErrorState title={ct('loadError')} /> : !data ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : <div className="overflow-hidden rounded-2xl border border-mis-border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[48rem] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{[t.customer, t.organization, t.collector, t.date, t.amount, t.method, t.status, t.details].map(x => <th key={x} className="px-4 py-3 text-start">{x}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(x => <tr key={x.id} className="hover:bg-slate-50/70"><td className="px-4 py-3"><Link className="font-bold text-mis-primary" to={`/collections/cases/${x.caseId}`}>{x.customerName}</Link><p className="mt-0.5 text-xs text-slate-500" data-bidi="ltr">{x.caseNumber}</p></td><td className="px-4 py-3"><span className="font-medium">{x.organizationName}</span><p className="text-xs text-slate-500">{ct(x.organizationType)}</p></td><td className="px-4 py-3">{x.collectorName}</td><td className="px-4 py-3" data-bidi="ltr">{x.paymentDate}</td><td className="px-4 py-3 font-bold" data-bidi="ltr">{f.money(x.amount)}</td><td className="px-4 py-3">{ct(x.method)}</td><td className="px-4 py-3"><CollectionStatus value={x.status} /></td><td className="px-4 py-3"><button className="inline-flex items-center gap-1.5 rounded-lg border border-mis-border px-3 py-2 font-semibold text-mis-primary hover:bg-sky-50" onClick={() => void openDetails(x.id)}><Eye className="h-4 w-4" />{t.view}</button></td></tr>)}</tbody></table>{data.items.length === 0 && <p className="p-12 text-center text-slate-500">{ct('noPayments')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>}
    <Modal open={Boolean(selected) || detailsLoading} onClose={() => setSelected(undefined)} title={t.paymentDetails} size="lg" footer={<div className="flex flex-wrap justify-end gap-2">{selected && canReview && ['SUBMITTED', 'UNDER_REVIEW'].includes(selected.status) && <><Button variant="danger" fullWidth={false} disabled={saving} onClick={() => setRejectOpen(true)} leftIcon={<X className="h-4 w-4" />}>{ct('reject')}</Button><Button fullWidth={false} isLoading={saving} onClick={() => void review(true)} leftIcon={<Check className="h-4 w-4" />}>{ct('approve')}</Button></>}<Button variant="outline" fullWidth={false} onClick={() => setSelected(undefined)}>{t.close}</Button></div>}>{detailsLoading && !selected ? <div className="flex min-h-48 items-center justify-center"><LoadingSpinner /></div> : selected ? <div><div className="mb-4 flex justify-between gap-4 rounded-xl bg-slate-50 p-4"><div><p className="text-lg font-bold text-mis-navy">{selected.customerName}</p><Link to={`/collections/cases/${selected.caseId}`} className="text-sm font-semibold text-mis-primary">{selected.caseNumber}</Link></div><CollectionStatus value={selected.status} /></div><dl className="grid gap-x-6 gap-y-4 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className="border-b border-slate-100 pb-3"><dt className="text-xs font-semibold text-slate-500">{label}</dt><dd className="mt-1 font-medium text-slate-800">{value}</dd></div>)}</dl></div> : null}</Modal>
    <Modal open={rejectOpen} onClose={() => { if (!saving) setRejectOpen(false); }} title={ct('reject')} size="sm" footer={<><Button variant="outline" fullWidth={false} onClick={() => setRejectOpen(false)} disabled={saving}>{ct('cancel')}</Button><Button variant="danger" fullWidth={false} isLoading={saving} disabled={!rejectReason.trim()} onClick={() => void review(false, rejectReason)}>{ct('reject')}</Button></>}>
      <label className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-600">{ct('rejectionReason')}</span><textarea className="field" rows={3} maxLength={1000} value={rejectReason} onChange={e => setRejectReason(e.target.value)} autoFocus /></label>
    </Modal>
  </div>;
}

function Filter({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
