import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { Check, Search, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { CollectionStatus, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { PagedResult, PaymentItem } from '../../features/collections/types/collections';

export function CollectionPaymentsPage() {
  const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const { user } = useAuth(); const canReview = user?.roles.some(x => ['Admin', 'CollectionsOperationsManager', 'CollectionsReviewer'].includes(x)); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [data, setData] = useState<PagedResult<PaymentItem>>(); const [error, setError] = useState(false); const [saving, setSaving] = useState('');
  const load = () => { setError(false); collectionsService.payments({ page, pageSize: 20, search: query, status }).then(setData).catch(() => setError(true)); }; useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); }, 350); return () => clearTimeout(timer); }, [search]); useEffect(load, [page, query, status]);
  const review = async (item: PaymentItem, approve: boolean) => { const reason = approve ? undefined : window.prompt(ct('rejectionReason'))?.trim(); if (!approve && !reason) return; setSaving(item.id); try { await collectionsService.reviewPayment(item.id, approve, reason); load(); } finally { setSaving(''); } };
  return <div><PageHeader eyebrow={ct('collections')} title={ct('payments')} description={ct('dcrSubtitle')} /><div className="mb-5 grid gap-3 md:grid-cols-[1fr_240px]"><label className="relative"><Search className="absolute top-3.5 h-5 w-5 text-slate-400" style={{ insetInlineStart: '0.9rem' }} /><input className="field ps-12" placeholder={ct('searchCases')} value={search} onChange={e => setSearch(e.target.value)} /></label><ProfessionalSelect className="field" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">{ct('allStatuses')}</option>{['SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED'].map(x => <option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></div>{error ? <ErrorState title={ct('loadError')} /> : !data ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : <div className="overflow-hidden rounded-2xl border border-mis-border bg-white"><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{[ct('customer'), ct('date'), ct('amount'), ct('method'), ct('reference'), ct('submittedBy'), ct('status'), ''].map((x, i) => <th key={`${x}${i}`} className="px-5 py-4 text-start">{x}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(x => <tr key={x.id}><td className="px-5 py-4"><Link className="font-bold text-mis-primary" to={`/collections/cases/${x.caseId}`}>{x.customerName}</Link><p className="mt-1 text-xs text-slate-500" data-bidi="ltr">{x.caseNumber}</p></td><td className="px-5 py-4" data-bidi="ltr">{x.paymentDate}</td><td className="px-5 py-4 font-bold" data-bidi="ltr">{f.money(x.amount)}</td><td className="px-5 py-4">{x.method}</td><td className="px-5 py-4" data-bidi="ltr">{x.referenceNumber}</td><td className="px-5 py-4">{x.submittedBy}</td><td className="px-5 py-4"><CollectionStatus value={x.status} /></td><td className="px-5 py-4">{canReview && ['SUBMITTED', 'UNDER_REVIEW'].includes(x.status) ? <div className="flex gap-2"><button disabled={saving === x.id} onClick={() => review(x, true)} className="rounded-lg bg-emerald-100 p-2 text-emerald-800" title={ct('approve')}><Check className="h-4 w-4" /></button><button disabled={saving === x.id} onClick={() => review(x, false)} className="rounded-lg bg-rose-100 p-2 text-rose-800" title={ct('reject')}><X className="h-4 w-4" /></button></div> : null}</td></tr>)}</tbody></table>{data.items.length === 0 && <p className="p-12 text-center text-slate-500">{ct('noPayments')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>}</div>;
}
