import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { Download } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { ProfessionalDateInput } from '../../components/forms/ProfessionalDateInput';
import { useAuth } from '../../context/AuthContext';
import { KpiCard, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { ClientCard, CollectionReport, CollectionReportBreakdown } from '../../features/collections/types/collections';

const today = new Date(); const initialTo = today.toISOString().slice(0, 10); const initialFrom = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), 1)).toISOString().slice(0, 10);
export function CollectionsReportsPage() {
  const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const { user } = useAuth(); const canExport = user?.roles.some(role => ['Admin', 'CollectionsOperationsManager', 'CollectionsSupervisor', 'CollectionsAuditor'].includes(role));
  const [clients, setClients] = useState<ClientCard[]>([]); const [report, setReport] = useState<CollectionReport>(); const [filters, setFilters] = useState<Record<string, unknown>>({ from: initialFrom, to: initialTo }); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const run = async (values = filters) => { setLoading(true); setError(''); try { setReport(await collectionsService.executiveReport(values)); } catch { setError(ct('loadError')); } finally { setLoading(false); } };
  useEffect(() => { void collectionsService.clients({ pageSize: 100 }).then(page => setClients(page.items)); void run(); }, []);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const next = { organizationId: String(form.get('organizationId') || ''), from: String(form.get('from')), to: String(form.get('to')) }; setFilters(next); void run(next); };
  return <div><PageHeader eyebrow={ct('collections')} title={ct('reports')} description={ct('reportsSubtitle')} actions={canExport ? <button disabled={!report} onClick={() => collectionsService.exportExecutiveReport(filters)} className="inline-flex items-center gap-2 rounded-xl border border-mis-primary px-4 py-2.5 text-sm font-bold text-mis-primary"><Download className="h-4 w-4" />{ct('exportCsv')}</button> : undefined} />
    <form onSubmit={submit} className="mb-6 grid gap-4 rounded-2xl border border-mis-border bg-white p-5 shadow-sm md:grid-cols-[1fr_220px_220px_auto]"><Field label={ct('selectClient')}><ProfessionalSelect name="organizationId" className="field"><option value="">All / الكل</option>{clients.map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</ProfessionalSelect></Field><Field label={ct('from')}><ProfessionalDateInput name="from" required defaultValue={initialFrom} /></Field><Field label={ct('to')}><ProfessionalDateInput name="to" required defaultValue={initialTo} /></Field><button className="self-end rounded-xl bg-mis-primary px-5 py-3 font-bold text-white">{ct('runReport')}</button></form>
    {error && <p className="mb-5 rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{loading && !report ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : report && <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label={ct('totalCases')} value={f.number(report.summary.totalCases)} /><KpiCard label={ct('totalOutstanding')} value={f.money(report.summary.outstanding)} /><KpiCard label={ct('approvedCollection')} value={f.money(report.summary.approvedCollection)} accent="green" /><KpiCard label={ct('recoveryRate')} value={`${report.summary.recoveryRate.toFixed(1)}%`} accent="green" /><KpiCard label={ct('activePtp')} value={f.money(report.summary.promiseAmount)} /><KpiCard label={ct('fulfilledAmount')} value={f.money(report.summary.fulfilledPromiseAmount)} accent="green" /><KpiCard label={ct('fulfillmentRate')} value={`${report.summary.promiseFulfillmentRate.toFixed(1)}%`} /><KpiCard label={ct('totalOverdue')} value={f.money(report.summary.overdue)} accent="red" /></section><div className="mt-7 grid gap-6 xl:grid-cols-3"><Breakdown title={ct('byClient')} rows={report.byClient} /><Breakdown title={ct('byBucket')} rows={report.byBucket} /><Breakdown title={ct('byCollector')} rows={report.byCollector} /></div></>}
  </div>;
}
function Breakdown({ title, rows }: { title: string; rows: CollectionReportBreakdown[] }) { const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); return <section className="overflow-hidden rounded-2xl border border-mis-border bg-white"><h2 className="border-b border-mis-border px-5 py-4 font-bold text-mis-navy">{title}</h2><div className="max-h-[500px] divide-y divide-mis-border overflow-auto">{rows.map(row => <div key={row.code} className="p-4"><p className="font-bold text-mis-navy">{row.name}</p><p className="mt-1 text-xs text-slate-500" data-bidi="ltr">{row.code} · {ct('casesCount')}: {f.number(row.cases)}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span>{ct('balance')}: <b data-bidi="ltr">{f.money(row.outstanding)}</b></span><span>{ct('collected')}: <b className="text-emerald-700" data-bidi="ltr">{f.money(row.collected)}</b></span></div></div>)}</div></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-sm font-semibold text-slate-600">{label}</span>{children}</label>; }
