import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { MessageSquarePlus } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '../../components/common/Button';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { ProfessionalDateInput } from '../../components/forms/ProfessionalDateInput';
import { useAuth } from '../../context/AuthContext';
import { CollectionStatus, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { CollectionCase, Complaint, PagedResult } from '../../features/collections/types/collections';

export function CollectionComplaintsPage() {
  const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const { user } = useAuth();
  const [data, setData] = useState<PagedResult<Complaint>>(); const [cases, setCases] = useState<CollectionCase[]>([]); const [page, setPage] = useState(1); const [status] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [statusEditor, setStatusEditor] = useState<Complaint>(); const [nextStatus, setNextStatus] = useState('IN_PROGRESS'); const [resolution, setResolution] = useState('');
  const load = () => collectionsService.complaints({ page, pageSize: 20, status }).then(setData).catch(() => setError(ct('loadError')));
  useEffect(() => { void load(); }, [page, status]); useEffect(() => { void collectionsService.cases({ pageSize: 100, status: 'ACTIVE' }).then(result => setCases(result.items)); }, []);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; setSaving(true); const form = new FormData(formElement); try { await collectionsService.createComplaint({ caseId: String(form.get('caseId')), reference: String(form.get('reference')), source: String(form.get('source')), category: String(form.get('category')), severity: String(form.get('severity')), description: String(form.get('description')), receivedAt: new Date(String(form.get('receivedAt'))).toISOString(), slaDueAt: new Date(String(form.get('slaDueAt'))).toISOString(), ownerId: user!.id }); formElement.reset(); load(); } catch { setError(ct('saveError')); } finally { setSaving(false); } };
  const openStatus = (item: Complaint) => { setStatusEditor(item); setNextStatus('IN_PROGRESS'); setResolution(''); };
  const resolutionRequired = ['RESOLVED', 'CLOSED'].includes(nextStatus);
  const submitStatus = async () => { if (!statusEditor) return; if (resolutionRequired && !resolution.trim()) return; setSaving(true); try { await collectionsService.changeComplaintStatus(statusEditor.id, nextStatus, resolutionRequired ? resolution.trim() : undefined); setStatusEditor(undefined); load(); } catch { setError(ct('saveError')); } finally { setSaving(false); } };
  return <div><PageHeader eyebrow={ct('collections')} title={ct('complaints')} description={ct('complaintsSubtitle')} />
    <details className="mb-6 rounded-2xl border border-mis-border bg-white p-5 shadow-sm"><summary className="flex cursor-pointer items-center gap-2 font-bold text-mis-primary"><MessageSquarePlus className="h-5 w-5" />{ct('newComplaint')}</summary><form onSubmit={create} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label={ct('case')}><ProfessionalSelect required name="caseId" className="field"><option value="">—</option>{cases.map(item => <option key={item.id} value={item.id}>{item.caseNumber} — {item.customerName}</option>)}</ProfessionalSelect></Field><Field label={ct('reference')}><input required name="reference" maxLength={80} className="field" /></Field><Field label={ct('source')}><ProfessionalSelect required name="source" className="field"><option value="CALL_CENTER">{ct('CALL_CENTER')}</option><option value="CLIENT">{ct('CLIENT')}</option><option value="FIELD">{ct('FIELD')}</option></ProfessionalSelect></Field><Field label={ct('category')}><input required name="category" maxLength={100} className="field" /></Field><Field label={ct('severity')}><ProfessionalSelect required name="severity" className="field"><option value="LOW">{ct('LOW')}</option><option value="MEDIUM">{ct('MEDIUM')}</option><option value="HIGH">{ct('HIGH')}</option><option value="CRITICAL">{ct('CRITICAL')}</option></ProfessionalSelect></Field><Field label={ct('date')}><ProfessionalDateInput required name="receivedAt" mode="datetime" /></Field><Field label={ct('sla')}><ProfessionalDateInput required name="slaDueAt" mode="datetime" /></Field><label className="md:col-span-2"><span className="mb-1.5 block text-sm font-semibold text-slate-600">{ct('description')}</span><textarea required name="description" rows={3} maxLength={4000} className="field" /></label><button disabled={saving} className="rounded-xl bg-mis-primary px-4 py-3 font-bold text-white md:col-span-2 xl:col-span-3">{saving ? ct('loading') : ct('newComplaint')}</button></form></details>
    {error && !data ? <ErrorState title={error} /> : !data ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : <div className="overflow-hidden rounded-2xl border border-mis-border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[52rem] text-sm"><thead className="bg-slate-50"><tr>{[ct('reference'), ct('customer'), ct('category'), ct('severity'), ct('owner'), ct('sla'), ct('status'), ''].map((heading, index) => <th key={`${heading}${index}`} className="px-5 py-4 text-start text-xs text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(item => <tr key={item.id}><td className="px-5 py-4 font-semibold" data-bidi="ltr">{item.reference}</td><td className="px-5 py-4"><Link to={`/collections/cases/${item.caseId}`} className="font-bold text-mis-primary">{item.customerName}</Link><p className="text-xs text-slate-500">{item.clientName}</p></td><td className="px-5 py-4">{item.category}</td><td className="px-5 py-4"><CollectionStatus value={item.severity} /></td><td className="px-5 py-4">{item.ownerName}</td><td className="px-5 py-4"><CollectionStatus value={item.slaStatus} /><p className="mt-1 text-xs text-slate-500" data-bidi="ltr">{f.dateTime(item.slaDueAt)}</p></td><td className="px-5 py-4"><CollectionStatus value={item.status} /></td><td className="px-5 py-4"><Button variant="outline" size="sm" fullWidth={false} disabled={saving} onClick={() => openStatus(item)}>{ct('changeStatus')}</Button></td></tr>)}</tbody></table>{!data.items.length && <p className="p-12 text-center text-slate-500">{ct('noComplaints')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>}
    <Modal open={Boolean(statusEditor)} onClose={() => { if (!saving) setStatusEditor(undefined); }} title={ct('changeStatus')} description={statusEditor ? `${statusEditor.reference} · ${statusEditor.customerName}` : undefined} size="sm" footer={<><Button variant="outline" fullWidth={false} onClick={() => setStatusEditor(undefined)} disabled={saving}>{ct('cancel')}</Button><Button fullWidth={false} onClick={() => void submitStatus()} isLoading={saving} disabled={resolutionRequired && !resolution.trim()}>{ct('confirm')}</Button></>}>
      <div className="space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-600">{ct('status')}</span><ProfessionalSelect className="field" value={nextStatus} onChange={e => setNextStatus(e.target.value)}>{['IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED'].map(s => <option key={s} value={s}>{ct(s)}</option>)}</ProfessionalSelect></label>{resolutionRequired && <label className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-600">{ct('resolution')}</span><textarea className="field" rows={3} maxLength={4000} value={resolution} onChange={e => setResolution(e.target.value)} /></label>}</div>
    </Modal>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-sm font-semibold text-slate-600">{label}</span>{children}</label>; }
