import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { Download, FileSpreadsheet } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import { Button } from '../../components/common/Button';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { FileInput } from '../../components/forms/FileInput';
import { CollectionStatus, KpiCard, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { ClientCard, ImportBatch, ImportPreview, PagedResult, PortfolioLookup } from '../../features/collections/types/collections';

export function CollectionImportsPage() {
  const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const [clients, setClients] = useState<ClientCard[]>([]); const [portfolios, setPortfolios] = useState<PortfolioLookup[]>([]); const [history, setHistory] = useState<PagedResult<ImportBatch>>(); const [preview, setPreview] = useState<ImportPreview>(); const [organizationId, setOrganizationId] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const loadHistory = () => collectionsService.imports({ page: 1, pageSize: 20 }).then(setHistory); useEffect(() => { Promise.all([collectionsService.clients({ pageSize: 100 }), collectionsService.portfolios(), collectionsService.imports({ pageSize: 20 })]).then(([c, p, h]) => { setClients(c.items); setPortfolios(p); setHistory(h); }).catch(() => setError(ct('loadError'))); }, []);
  const upload = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); const form = new FormData(event.currentTarget); const file = form.get('file'); try { if (!(file instanceof File) || !file.size) throw new Error(); const batch = await collectionsService.uploadImport(String(form.get('organizationId')), String(form.get('portfolioId')), file); setPreview(await collectionsService.importPreview(batch.id, { pageSize: 100 })); loadHistory(); } catch { setError(ct('saveError')); } finally { setSaving(false); } };
  const confirm = async () => { if (!preview || preview.batch.invalidRows > 0 && !window.confirm(`${ct('invalidRows')}: ${preview.batch.invalidRows}. ${ct('confirmImport')}?`)) return; setSaving(true); try { const batch = await collectionsService.confirmImport(preview.batch.id); setPreview(await collectionsService.importPreview(batch.id, { pageSize: 100 })); loadHistory(); } catch { setError(ct('saveError')); } finally { setSaving(false); } };
  return <div><PageHeader eyebrow={ct('collections')} title={ct('imports')} description={ct('importSubtitle')} />
    <section className="rounded-2xl border border-mis-border bg-white p-4 sm:p-6"><form onSubmit={upload} className="grid items-end gap-4 sm:grid-cols-2 xl:grid-cols-[1fr_1fr_1.2fr_auto]"><Field label={ct('selectClient')}><ProfessionalSelect required name="organizationId" className="field" value={organizationId} onChange={e => setOrganizationId(e.target.value)}><option value="">—</option>{clients.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></Field><Field label={ct('selectPortfolio')}><ProfessionalSelect required name="portfolioId" className="field"><option value="">—</option>{portfolios.filter(x => !organizationId || x.organizationId === organizationId).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></Field><FileInput required name="file" accept=".csv,.xlsx" label={ct('file')} /><Button disabled={saving} fullWidth={false} size="md" type="submit">{saving ? ct('loading') : ct('uploadPreview')}</Button></form>{error && <p className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}</section>
    {preview && <section className="mt-6"><div className="grid gap-4 sm:grid-cols-3"><KpiCard label={ct('totalRows')} value={f.number(preview.batch.totalRows)} /><KpiCard label={ct('validRows')} value={f.number(preview.batch.validRows)} accent="green" /><KpiCard label={ct('invalidRows')} value={f.number(preview.batch.invalidRows)} accent={preview.batch.invalidRows ? 'red' : 'blue'} /></div><div className="mt-5 overflow-hidden rounded-2xl border border-mis-border bg-white"><header className="flex flex-wrap items-center gap-3 border-b border-mis-border px-5 py-4"><h2 className="font-bold text-mis-navy">{ct('preview')} — {preview.batch.fileName}</h2><CollectionStatus value={preview.batch.status} /><div className="ms-auto flex gap-2">{preview.batch.invalidRows > 0 && <button onClick={() => collectionsService.downloadImportErrors(preview.batch.id)} className="inline-flex items-center gap-2 rounded-lg border border-mis-border px-3 py-2 text-sm font-bold text-mis-primary"><Download className="h-4 w-4" />{ct('downloadErrors')}</button>}{preview.batch.status === 'PREVIEW_READY' && <button disabled={saving} onClick={confirm} className="rounded-lg bg-mis-primary px-4 py-2 text-sm font-bold text-white">{ct('confirmImport')}</button>}</div></header><div className="max-h-[500px] overflow-auto"><table className="min-w-[900px] w-full text-sm"><thead className="sticky top-0 bg-slate-50"><tr>{[ct('row'), ct('accountReference'), ct('customer'), ct('balance'), ct('overdue'), 'DPD', ct('status'), ct('errors')].map(x => <th key={x} className="px-4 py-3 text-start text-xs text-slate-500">{x}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{preview.rows.items.map(x => <tr key={x.id}><td className="px-4 py-3" data-bidi="ltr">{x.rowNumber}</td><td className="px-4 py-3" data-bidi="ltr">{x.accountReference}</td><td className="px-4 py-3"><p>{x.customerName}</p><p className="text-xs text-slate-500">{x.customerCode}</p></td><td className="px-4 py-3" data-bidi="ltr">{x.outstandingBalance == null ? '—' : f.money(x.outstandingBalance)}</td><td className="px-4 py-3" data-bidi="ltr">{x.overdueBalance == null ? '—' : f.money(x.overdueBalance)}</td><td className="px-4 py-3" data-bidi="ltr">{x.daysPastDue ?? '—'}</td><td className="px-4 py-3"><CollectionStatus value={x.isValid ? 'APPROVED' : 'REJECTED'} /></td><td className="max-w-xs px-4 py-3 text-xs text-rose-700">{x.errors.join(' · ')}</td></tr>)}</tbody></table></div></div></section>}
    <section className="mt-8"><h2 className="mb-4 text-xl font-bold text-mis-navy">{ct('importHistory')}</h2>{!history ? error ? <ErrorState title={error} /> : <div className="flex min-h-40 items-center justify-center"><LoadingSpinner /></div> : history.items.length ? <div className="grid gap-4">{history.items.map(x => <button key={x.id} onClick={async () => setPreview(await collectionsService.importPreview(x.id, { pageSize: 100 }))} className="flex flex-wrap items-center gap-4 rounded-2xl border border-mis-border bg-white p-5 text-start hover:border-mis-sky"><FileSpreadsheet className="h-7 w-7 text-mis-primary" /><div className="min-w-0 flex-1"><p className="truncate font-bold text-mis-navy">{x.fileName}</p><p className="mt-1 text-xs text-slate-500">{x.organizationName} · {x.portfolioName} · {f.dateTime(x.uploadedAt)}</p></div><div className="flex gap-4 text-xs text-slate-500"><span>{ct('validRows')}: <b>{x.validRows}</b></span><span>{ct('invalidRows')}: <b>{x.invalidRows}</b></span></div><CollectionStatus value={x.status} /></button>)}</div> : <p className="rounded-2xl border border-dashed border-mis-border p-10 text-center text-slate-500">{ct('noImports')}</p>}</section>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-sm font-semibold text-slate-600">{label}</span>{children}</label>; }
