import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { ChevronRight, Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { CollectionStatus, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { CollectionCase, PagedResult } from '../../features/collections/types/collections';

export function CollectionCasesPage() {
  const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const [url] = useSearchParams(); const organizationId = url.get('organizationId') ?? undefined;
  const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [priority, setPriority] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [data, setData] = useState<PagedResult<CollectionCase>>(); const [error, setError] = useState(false);
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); }, 350); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { let active = true; setError(false); collectionsService.cases({ page, pageSize: 20, search: query, priority, status, organizationId }).then(x => active && setData(x)).catch(() => active && setError(true)); return () => { active = false; }; }, [page, query, priority, status, organizationId]);
  return <div><PageHeader eyebrow={ct('collections')} title={ct('cases')} description={ct('caseWorkbenchSubtitle')} />
    <div className="mb-5 grid gap-3 lg:grid-cols-[1fr_220px_220px]"><label className="relative"><Search className="absolute top-3.5 h-5 w-5 text-slate-400" style={{ insetInlineStart: '0.9rem' }} /><input className="w-full rounded-xl border border-mis-border bg-white py-3 pe-4 ps-12 outline-none focus:border-mis-blue" placeholder={ct('searchCases')} value={search} onChange={e => setSearch(e.target.value)} /></label><ProfessionalSelect className="rounded-xl border border-mis-border bg-white px-4 py-3" value={priority} onChange={e => { setPriority(e.target.value); setPage(1); }}><option value="">{ct('allPriorities')}</option><option value="HIGH">{ct('HIGH')}</option><option value="MEDIUM">{ct('MEDIUM')}</option><option value="NORMAL">{ct('NORMAL')}</option></ProfessionalSelect><ProfessionalSelect className="rounded-xl border border-mis-border bg-white px-4 py-3" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">{ct('allStatuses')}</option><option value="ACTIVE">{ct('ACTIVE')}</option><option value="CLOSED">CLOSED</option><option value="LEGAL">LEGAL</option></ProfessionalSelect></div>
    {error ? <ErrorState title={ct('loadError')} /> : !data ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : <div className="overflow-hidden rounded-2xl border border-mis-border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><Th>{ct('customer')}</Th><Th>{ct('clientPortfolio')}</Th><Th>{ct('balance')}</Th><Th>{ct('overdue')}</Th><Th>{ct('dpdBucket')}</Th><Th>{ct('collector')}</Th><Th>{ct('priority')}</Th><Th /></tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(row => <tr key={row.id} className="hover:bg-slate-50/70"><Td><p className="font-bold text-mis-navy">{row.customerName}</p><p className="mt-1 text-xs text-slate-500"><span data-bidi="ltr">{row.caseNumber}</span> · {row.customerCode}</p></Td><Td><p>{row.clientName}</p><p className="mt-1 text-xs text-slate-500">{row.portfolioName}</p></Td><Td bidi>{f.money(row.outstandingBalance)}</Td><Td bidi>{f.money(row.overdueBalance)}</Td><Td><span data-bidi="ltr" className="font-semibold">{row.daysPastDue}</span><p className="mt-1 text-xs text-slate-500">{row.bucket}</p></Td><Td>{row.assignedCollectorName ?? '—'}</Td><Td><CollectionStatus value={row.priority} /><p className="mt-1 text-xs font-semibold text-slate-500" data-bidi="ltr">{row.priorityScore}/100</p></Td><Td><Link to={`/collections/cases/${row.id}`} className="inline-grid h-9 w-9 place-items-center rounded-lg text-mis-primary hover:bg-mis-pale"><ChevronRight className="h-5 w-5 rtl:rotate-180" /></Link></Td></tr>)}</tbody></table>{data.items.length === 0 && <p className="p-12 text-center text-slate-500">{ct('noCases')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>}
  </div>;
}
function Th({ children }: { children?: React.ReactNode }) { return <th className="px-5 py-4 text-start font-bold">{children}</th>; }
function Td({ children, bidi = false }: { children?: React.ReactNode; bidi?: boolean }) { return <td className="px-5 py-4 align-top" {...(bidi ? { 'data-bidi': 'ltr' } : {})}>{children}</td>; }
