import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { type FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { ProfessionalDateInput } from '../../components/forms/ProfessionalDateInput';
import { useAuth } from '../../context/AuthContext';
import { CollectionStatus, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { CollectionCase, Complaint, PagedResult } from '../../features/collections/types/collections';

export function CollectionComplaintsPage() {
  const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const { user } = useAuth();
  const [data, setData] = useState<PagedResult<Complaint>>(); const [cases, setCases] = useState<CollectionCase[]>([]); const [page, setPage] = useState(1); const [status] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const load = () => collectionsService.complaints({ page, pageSize: 20, status }).then(setData).catch(() => setError(ct('loadError')));
  useEffect(() => { void load(); }, [page, status]); useEffect(() => { void collectionsService.cases({ pageSize: 100, status: 'ACTIVE' }).then(result => setCases(result.items)); }, []);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; setSaving(true); const form = new FormData(formElement); try { await collectionsService.createComplaint({ caseId: String(form.get('caseId')), reference: String(form.get('reference')), source: String(form.get('source')), category: String(form.get('category')), severity: String(form.get('severity')), description: String(form.get('description')), receivedAt: new Date(String(form.get('receivedAt'))).toISOString(), slaDueAt: new Date(String(form.get('slaDueAt'))).toISOString(), ownerId: user!.id }); formElement.reset(); load(); } catch { setError(ct('saveError')); } finally { setSaving(false); } };
  const change = async (item: Complaint) => { const next = window.prompt(`${ct('changeStatus')}: IN_PROGRESS / RESOLVED / CLOSED / ESCALATED`)?.trim().toUpperCase(); if (!next) return; const resolution = ['RESOLVED', 'CLOSED'].includes(next) ? window.prompt(ct('resolution'))?.trim() : undefined; if (['RESOLVED', 'CLOSED'].includes(next) && !resolution) return; setSaving(true); try { await collectionsService.changeComplaintStatus(item.id, next, resolution); load(); } finally { setSaving(false); } };
  return <div><PageHeader eyebrow={ct('collections')} title={ct('complaints')} description={ct('complaintsSubtitle')} />
    <details className="mb-6 rounded-2xl border border-mis-border bg-white p-5 shadow-sm"><summary className="cursor-pointer font-bold text-mis-primary">{ct('newComplaint')}</summary><form onSubmit={create} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label={ct('cases')}><ProfessionalSelect required name="caseId" className="field"><option value="">—</option>{cases.map(item => <option key={item.id} value={item.id}>{item.caseNumber} — {item.customerName}</option>)}</ProfessionalSelect></Field><Field label={ct('reference')}><input required name="reference" maxLength={80} className="field" /></Field><Field label={ct('source')}><ProfessionalSelect required name="source" className="field"><option value="CALL_CENTER">CALL CENTER</option><option value="CLIENT">CLIENT</option><option value="FIELD">FIELD</option></ProfessionalSelect></Field><Field label={ct('category')}><input required name="category" maxLength={100} className="field" /></Field><Field label={ct('severity')}><ProfessionalSelect required name="severity" className="field"><option value="LOW">LOW</option><option value="MEDIUM">MEDIUM</option><option value="HIGH">HIGH</option><option value="CRITICAL">CRITICAL</option></ProfessionalSelect></Field><Field label={ct('date')}><ProfessionalDateInput required name="receivedAt" mode="datetime" /></Field><Field label={ct('sla')}><ProfessionalDateInput required name="slaDueAt" mode="datetime" /></Field><label className="md:col-span-2"><span className="mb-1.5 block text-sm font-semibold text-slate-600">{ct('description')}</span><textarea required name="description" rows={3} maxLength={4000} className="field" /></label><button disabled={saving} className="rounded-xl bg-mis-primary px-4 py-3 font-bold text-white md:col-span-2 xl:col-span-3">{saving ? ct('loading') : ct('newComplaint')}</button></form></details>
    {error && !data ? <ErrorState title={error} /> : !data ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : <div className="overflow-hidden rounded-2xl border border-mis-border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-slate-50"><tr>{[ct('reference'), ct('customer'), ct('category'), ct('severity'), ct('owner'), ct('sla'), ct('status'), ''].map((heading, index) => <th key={`${heading}${index}`} className="px-5 py-4 text-start text-xs text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(item => <tr key={item.id}><td className="px-5 py-4 font-semibold" data-bidi="ltr">{item.reference}</td><td className="px-5 py-4"><Link to={`/collections/cases/${item.caseId}`} className="font-bold text-mis-primary">{item.customerName}</Link><p className="text-xs text-slate-500">{item.clientName}</p></td><td className="px-5 py-4">{item.category}</td><td className="px-5 py-4"><CollectionStatus value={item.severity} /></td><td className="px-5 py-4">{item.ownerName}</td><td className="px-5 py-4"><CollectionStatus value={item.slaStatus} /><p className="mt-1 text-xs text-slate-500" data-bidi="ltr">{f.dateTime(item.slaDueAt)}</p></td><td className="px-5 py-4"><CollectionStatus value={item.status} /></td><td className="px-5 py-4"><button disabled={saving} onClick={() => change(item)} className="rounded-lg border border-mis-primary px-3 py-2 text-xs font-bold text-mis-primary">{ct('changeStatus')}</button></td></tr>)}</tbody></table>{!data.items.length && <p className="p-12 text-center text-slate-500">{ct('noComplaints')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>}
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-sm font-semibold text-slate-600">{label}</span>{children}</label>; }
