import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { CollectionStatus, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { PagedResult, PromiseItem } from '../../features/collections/types/collections';

export function CollectionPromisesPage() {
  const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [data, setData] = useState<PagedResult<PromiseItem>>(); const [error, setError] = useState(false);
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); }, 350); return () => clearTimeout(timer); }, [search]); useEffect(() => { let active = true; setError(false); collectionsService.promises({ page, pageSize: 20, search: query, status }).then(x => active && setData(x)).catch(() => active && setError(true)); return () => { active = false; }; }, [page, query, status]);
  return <div><PageHeader eyebrow={ct('collections')} title={ct('promises')} description={ct('ptpSubtitle')} /><div className="mb-5 grid gap-3 md:grid-cols-[1fr_240px]"><label className="relative"><Search className="absolute top-3.5 h-5 w-5 text-slate-400" style={{ insetInlineStart: '0.9rem' }} /><input className="field ps-12" placeholder={ct('searchCases')} value={search} onChange={e => setSearch(e.target.value)} /></label><ProfessionalSelect className="field" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">{ct('allStatuses')}</option>{['ACTIVE', 'UPCOMING', 'DUE_TODAY', 'FULFILLED', 'PARTIALLY_FULFILLED', 'BROKEN'].map(x => <option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></div>{error ? <ErrorState title={ct('loadError')} /> : !data ? <Loading /> : <Table data={data} setPage={setPage} ct={ct} money={f.money} />}</div>;
}
function Table({ data, setPage, ct, money }: { data: PagedResult<PromiseItem>; setPage: (p: number) => void; ct: (key: string) => string; money: (n: number) => string }) { return <div className="overflow-hidden rounded-2xl border border-mis-border bg-white"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{[ct('customer'), ct('date'), ct('amount'), ct('actualPaid'), ct('collector'), ct('channel'), ct('status')].map(x => <th key={x} className="px-5 py-4 text-start">{x}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(x => <tr key={x.id}><td className="px-5 py-4"><Link className="font-bold text-mis-primary" to={`/collections/cases/${x.caseId}`}>{x.customerName}</Link><p className="mt-1 text-xs text-slate-500" data-bidi="ltr">{x.caseNumber}</p></td><td className="px-5 py-4" data-bidi="ltr">{x.promiseDate}</td><td className="px-5 py-4 font-semibold" data-bidi="ltr">{money(x.promisedAmount)}</td><td className="px-5 py-4" data-bidi="ltr">{money(x.actualPaidAmount)}</td><td className="px-5 py-4">{x.collectorName}</td><td className="px-5 py-4">{x.channel}</td><td className="px-5 py-4"><CollectionStatus value={x.status} /></td></tr>)}</tbody></table>{data.items.length === 0 && <p className="p-12 text-center text-slate-500">{ct('noPromises')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>; }
function Loading() { return <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div>; }
