import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { DateControl } from '../../components/forms/DateControl';
import { CalendarClock, CalendarPlus, Check, CheckCircle2, Eye, MapPin, Search } from 'lucide-react';
import { type FormEvent, type ReactNode, useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { useAuth } from '../../context/AuthContext';
import { CollectionStatus, KpiCard, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { FieldVisit, FieldVisitDetails, FieldVisitFilterOptions, FieldVisitScheduleOptions, FieldVisitSummary, PagedResult } from '../../features/collections/types/collections';

const copy = {
  en: { subtitle: 'Authorized field visits across all banks and installment companies.', visitsToday: 'Visits Today', scheduled: 'Scheduled Visits', completed: 'Completed Visits', schedule: 'Schedule Visit', searchLabel: 'Search', search: 'Search customer, case, account or address...', organization: 'Bank / Company', allOrganizations: 'All Banks / Companies', collector: 'Collector', allCollectors: 'All Collectors', status: 'Status', date: 'Visit Date', time: 'Visit Time', customer: 'Customer', address: 'Address', details: 'Details', view: 'View Details', visitDetails: 'Visit Details', case: 'Customer / Case', selectCase: 'Select customer / case', notes: 'Notes', result: 'Visit Result / Outcome', feedback: 'Feedback', createdBy: 'Created By', createdAt: 'Created At', completedAt: 'Completed At', account: 'Account Reference', relatedDcr: 'Related DCR', relatedPtp: 'Related PTP', complete: 'Complete Visit', cancel: 'Cancel', save: 'Schedule Visit', noAddress: 'The selected case has no saved address.', selectResult: 'Select visit result' },
  ar: { subtitle: 'الزيارات الميدانية المصرح بها عبر جميع البنوك وشركات التقسيط.', visitsToday: 'زيارات اليوم', scheduled: 'زيارات مجدولة', completed: 'زيارات مكتملة', schedule: 'جدولة زيارة', searchLabel: 'بحث', search: 'ابحث بالعميل أو الحالة أو الحساب أو العنوان...', organization: 'البنك / الشركة', allOrganizations: 'كل البنوك / الشركات', collector: 'المحصل', allCollectors: 'كل المحصلين', status: 'الحالة', date: 'تاريخ الزيارة', time: 'وقت الزيارة', customer: 'العميل', address: 'العنوان', details: 'التفاصيل', view: 'عرض التفاصيل', visitDetails: 'تفاصيل الزيارة', case: 'العميل / الحالة', selectCase: 'اختر العميل / الحالة', notes: 'ملاحظات', result: 'نتيجة الزيارة', feedback: 'التغذية الراجعة', createdBy: 'تم الإنشاء بواسطة', createdAt: 'وقت الإنشاء', completedAt: 'وقت الإكمال', account: 'مرجع الحساب', relatedDcr: 'سجل التحصيل اليومي المرتبط', relatedPtp: 'وعد السداد المرتبط', complete: 'إكمال الزيارة', cancel: 'إلغاء', save: 'جدولة الزيارة', noAddress: 'لا يوجد عنوان محفوظ للحالة المحددة.', selectResult: 'اختر نتيجة الزيارة' },
};
const statuses = ['SCHEDULED', 'ASSIGNED', 'PLANNED', 'RESCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'MISSED'];
const results = ['CUSTOMER_MET', 'CUSTOMER_NOT_AVAILABLE', 'ADDRESS_NOT_FOUND', 'WRONG_ADDRESS', 'REFUSED_CONTACT', 'PROMISE_TO_PAY_DISCUSSED', 'FOLLOW_UP_REQUIRED', 'OTHER'];

export function CollectionVisitsPage() {
  const { ct, language } = useCollectionsLocalization(); const t = copy[language]; const f = useCollectionFormat(); const { user } = useAuth();
  const canPlan = user?.roles.some(role => ['Admin', 'CollectionsOperationsManager', 'CollectionsSupervisor'].includes(role));
  const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [organizationId, setOrganizationId] = useState(''); const [collectorId, setCollectorId] = useState(''); const [status, setStatus] = useState(''); const [date, setDate] = useState(''); const [page, setPage] = useState(1);
  const [data, setData] = useState<PagedResult<FieldVisit>>(); const [summary, setSummary] = useState<FieldVisitSummary>(); const [options, setOptions] = useState<FieldVisitFilterOptions>({ organizations: [], collectors: [] }); const [scheduleOptions, setScheduleOptions] = useState<FieldVisitScheduleOptions>({ cases: [], collectors: [] }); const [selectedCaseId, setSelectedCaseId] = useState(''); const selectedCase = useMemo(() => scheduleOptions.cases.find(x => x.id === selectedCaseId), [scheduleOptions.cases, selectedCaseId]);
  const [scheduleOpen, setScheduleOpen] = useState(false); const [scheduleCollectorId, setScheduleCollectorId] = useState(''); const [details, setDetails] = useState<FieldVisitDetails>(); const [detailsLoading, setDetailsLoading] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [result, setResult] = useState(''); const [completionNotes, setCompletionNotes] = useState('');

  const load = useCallback(() => { setError(''); collectionsService.visits({ page, pageSize: 20, search: query, organizationId, collectorId, status, date }).then(setData).catch(() => setError(ct('loadError'))); }, [collectorId, date, organizationId, page, query, status, ct]);
  const loadHeader = useCallback(() => Promise.all([collectionsService.visitSummary(), collectionsService.visitFilterOptions()]).then(([s, o]) => { setSummary(s); setOptions(o); }).catch(() => setError(ct('loadError'))), [ct]);
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); }, 350); return () => clearTimeout(timer); }, [search]); useEffect(load, [load]); useEffect(() => { void loadHeader(); }, [loadHeader, language]);
  useEffect(() => { setScheduleCollectorId(selectedCase?.assignedCollectorId ?? ''); }, [selectedCase]);
  const openSchedule = async () => { setScheduleOpen(true); setError(''); try { setScheduleOptions(await collectionsService.visitScheduleOptions()); } catch { setError(ct('loadError')); } };
  const openDetails = async (id: string) => { setDetailsLoading(true); try { setDetails(await collectionsService.visit(id)); } finally { setDetailsLoading(false); } };
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedCase?.address) { setError(t.noAddress); return; } const form = new FormData(event.currentTarget); setSaving(true); try { await collectionsService.createVisit({ caseId: selectedCase.id, collectorId: String(form.get('collectorId')), scheduledAt: new Date(String(form.get('scheduledAt'))).toISOString(), address: selectedCase.address, governorate: selectedCase.governorate, area: selectedCase.area, notes: String(form.get('notes') || '') }); setScheduleOpen(false); setSelectedCaseId(''); load(); await loadHeader(); } catch { setError(ct('saveError')); } finally { setSaving(false); } };
  const complete = async () => { if (!details || !result) return; setSaving(true); try { await collectionsService.completeVisit(details.id, result, completionNotes || undefined); setDetails(await collectionsService.visit(details.id)); setResult(''); setCompletionNotes(''); load(); await loadHeader(); } finally { setSaving(false); } };
  const change = (setter: (value: string) => void, value: string) => { setter(value); setPage(1); };
  const dateParts = (value: string) => { const d = new Date(value); const locale = language === 'ar' ? 'ar-EG' : 'en-EG'; return { date: new Intl.DateTimeFormat(locale, { dateStyle: 'medium' }).format(d), time: new Intl.DateTimeFormat(locale, { hour: '2-digit', minute: '2-digit' }).format(d) }; };
  const canComplete = details && !['COMPLETED', 'CANCELLED', 'MISSED', 'FAILED'].includes(details.status) && (details.collectorId === user?.id || canPlan);
  const workspaceBase = details?.organizationType === 'CONSUMER_FINANCE' ? `/installment-companies/${details.organizationId}` : `/banks/${details?.organizationId}`;

  return <div><PageHeader eyebrow={ct('collections')} title={ct('visits')} description={t.subtitle} actions={canPlan ? <button onClick={() => void openSchedule()} className="inline-flex items-center gap-2 rounded-xl bg-mis-primary px-4 py-2.5 font-bold text-white"><CalendarPlus className="h-4 w-4" />{t.schedule}</button> : undefined} />
    <div className="mb-4 grid gap-3 sm:grid-cols-3"><KpiCard icon={<MapPin />} label={t.visitsToday} value={summary ? f.number(summary.visitsToday) : '—'} /><KpiCard icon={<CalendarClock />} label={t.scheduled} value={summary ? f.number(summary.scheduledVisits) : '—'} accent="amber" /><KpiCard icon={<CheckCircle2 />} label={t.completed} value={summary ? f.number(summary.completedVisits) : '—'} accent="green" /></div>
    <div className="mb-4 rounded-2xl border border-mis-border bg-white p-3 shadow-sm"><div className="module-filter-grid">
      <Field label={t.searchLabel}><span className="relative block"><Search className="absolute top-3 h-5 w-5 text-slate-400" style={{ insetInlineStart: '0.8rem' }} /><input className="field h-11 ps-11" placeholder={t.search} value={search} onChange={e => setSearch(e.target.value)} /></span></Field>
      <Field label={t.organization}><ProfessionalSelect className="field h-11" value={organizationId} onChange={e => change(setOrganizationId, e.target.value)}><option value="">{t.allOrganizations}</option>{options.organizations.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></Field>
      <Field label={t.collector}><ProfessionalSelect className="field h-11" value={collectorId} onChange={e => change(setCollectorId, e.target.value)}><option value="">{t.allCollectors}</option>{options.collectors.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></Field>
      <Field label={t.status}><ProfessionalSelect className="field h-11" value={status} onChange={e => change(setStatus, e.target.value)}><option value="">{ct('allStatuses')}</option>{statuses.map(x => <option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></Field>
      <Field label={t.date}><DateControl className="field h-11" value={date} onChange={e => change(setDate, e.target.value)} /></Field>
    </div></div>
    {error && !data ? <ErrorState title={error} /> : !data ? <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div> : <div className="overflow-hidden rounded-2xl border border-mis-border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[52rem] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{[t.customer, t.organization, t.collector, t.date, t.time, t.address, t.status, t.details].map(x => <th key={x} className="px-4 py-3 text-start">{x}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(item => { const scheduled = dateParts(item.scheduledAt); return <tr key={item.id} className="hover:bg-slate-50/70"><td className="px-4 py-3"><Link to={`/collections/cases/${item.caseId}`} className="font-bold text-mis-primary">{item.customerName}</Link><p className="text-xs text-slate-500" data-bidi="ltr">{item.caseNumber}</p></td><td className="px-4 py-3"><span className="font-medium">{item.organizationName}</span><p className="text-xs text-slate-500">{ct(item.organizationType)}</p></td><td className="px-4 py-3">{item.collectorName}</td><td className="px-4 py-3">{scheduled.date}</td><td className="px-4 py-3" data-bidi="ltr">{scheduled.time}</td><td className="max-w-xs px-4 py-3"><span className="line-clamp-2">{item.address}</span></td><td className="px-4 py-3"><CollectionStatus value={item.status} /></td><td className="px-4 py-3"><button onClick={() => void openDetails(item.id)} className="inline-flex items-center gap-1.5 rounded-lg border border-mis-border px-3 py-2 font-semibold text-mis-primary"><Eye className="h-4 w-4" />{t.view}</button></td></tr>; })}</tbody></table>{!data.items.length && <p className="p-12 text-center text-slate-500">{ct('noVisits')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>}

    <Modal open={scheduleOpen} onClose={() => setScheduleOpen(false)} title={t.schedule} size="lg"><form onSubmit={create} className="grid gap-4 sm:grid-cols-2"><Field label={t.case}><ProfessionalSelect required className="field" value={selectedCaseId} onChange={e => setSelectedCaseId(e.target.value)}><option value="">{t.selectCase}</option>{scheduleOptions.cases.map(x => <option key={x.id} value={x.id}>{x.caseNumber} — {x.customerName}</option>)}</ProfessionalSelect></Field><Field label={t.collector}><ProfessionalSelect required name="collectorId" className="field" value={scheduleCollectorId} onChange={e => setScheduleCollectorId(e.target.value)}><option value="">{t.allCollectors}</option>{scheduleOptions.collectors.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></Field>{selectedCase && <div className="sm:col-span-2 rounded-xl bg-slate-50 p-4"><p className="font-bold text-mis-navy">{selectedCase.customerName}</p><p className="mt-1 text-sm text-slate-600">{selectedCase.organizationName}</p><p className="mt-2 text-sm">{selectedCase.address || t.noAddress}</p></div>}<Field label={`${t.date} / ${t.time}`}><DateControl required name="scheduledAt" mode="datetime" /></Field><Field label={t.address}><input className="field bg-slate-50" readOnly value={selectedCase?.address ?? ''} /></Field><label className="sm:col-span-2"><span className="mb-1 block text-sm font-semibold text-slate-600">{t.notes}</span><textarea name="notes" maxLength={3000} className="field min-h-24" /></label><div className="sm:col-span-2 flex justify-end gap-2"><button type="button" onClick={() => setScheduleOpen(false)} className="rounded-lg border border-mis-border px-4 py-2 font-semibold">{t.cancel}</button><button disabled={saving || !selectedCase?.address || !scheduleCollectorId} className="rounded-lg bg-mis-primary px-4 py-2 font-bold text-white">{t.save}</button></div></form></Modal>

    <Modal open={Boolean(details) || detailsLoading} onClose={() => setDetails(undefined)} title={t.visitDetails} size="lg">{detailsLoading && !details ? <div className="flex min-h-48 items-center justify-center"><LoadingSpinner /></div> : details ? <div><div className="mb-4 flex justify-between gap-4 rounded-xl bg-slate-50 p-4"><div><p className="text-lg font-bold text-mis-navy">{details.customerName}</p><Link to={`/collections/cases/${details.caseId}`} className="text-sm font-semibold text-mis-primary">{details.caseNumber}</Link></div><CollectionStatus value={details.status} /></div><dl className="grid gap-x-6 gap-y-3 sm:grid-cols-2">{[[t.account, details.accountReference], [t.organization, details.organizationName], [t.collector, details.collectorName], [t.date, dateParts(details.scheduledAt).date], [t.time, dateParts(details.scheduledAt).time], [t.address, details.address], [t.result, details.result ? ct(details.result) : '—'], [t.notes, details.notes ?? '—'], [t.createdBy, details.createdBy], [t.createdAt, f.dateTime(details.createdAt)], [t.completedAt, details.completedAt ? f.dateTime(details.completedAt) : '—'], [t.feedback, details.dcrFeedback ?? '—']].map(([label, value]) => <div key={label} className="border-b border-slate-100 pb-2"><dt className="text-xs font-semibold text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl>{details.relatedDcrId && <div className="mt-4 flex gap-3"><Link className="font-bold text-mis-primary" to={`${workspaceBase}/dcr`}>{t.relatedDcr}</Link>{details.relatedPtpId && <Link className="font-bold text-mis-primary" to={`${workspaceBase}/ptp`}>{t.relatedPtp}</Link>}</div>}{canComplete && <div className="mt-5 rounded-xl border border-mis-border p-4"><p className="mb-3 font-bold text-mis-navy">{t.complete}</p><div className="grid gap-3 sm:grid-cols-2"><ProfessionalSelect className="field" value={result} onChange={e => setResult(e.target.value)}><option value="">{t.selectResult}</option>{results.map(x => <option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect><input className="field" placeholder={t.notes} value={completionNotes} onChange={e => setCompletionNotes(e.target.value)} /><button disabled={saving || !result} onClick={() => void complete()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white sm:col-span-2"><Check className="h-4 w-4" />{t.complete}</button></div></div>}</div> : null}</Modal>
  </div>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label><span className="mb-1 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
