import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { Ban, CheckCircle2, Search, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ConfirmDialog } from '../../components/common/ConfirmDialog';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { Pagination } from '../../components/common/Pagination';
import { CollectionStatus, useCollectionFormat } from '../../features/collections/components/CollectionsUi';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { PagedResult, PromiseItem } from '../../features/collections/types/collections';

type PendingAction = { promise: PromiseItem; status: 'FULFILLED' | 'BROKEN' | 'CANCELLED' };

export function CollectionPromisesPage() {
  const { ct } = useCollectionsLocalization(); const f = useCollectionFormat(); const [url] = useSearchParams(); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState(url.get('status') ?? ''); const [page, setPage] = useState(1); const [data, setData] = useState<PagedResult<PromiseItem>>(); const [error, setError] = useState(false); const [reloadKey, setReloadKey] = useState(0); const [pending, setPending] = useState<PendingAction>(); const [saving, setSaving] = useState(false); const [toast, setToast] = useState('');
  useEffect(() => { const timer = setTimeout(() => { setQuery(search); setPage(1); }, 350); return () => clearTimeout(timer); }, [search]);
  useEffect(() => { let active = true; setError(false); collectionsService.promises({ page, pageSize: 20, search: query, status }).then(x => active && setData(x)).catch(() => active && setError(true)); return () => { active = false; }; }, [page, query, status, reloadKey]);
  const confirmAction = async () => { if (!pending) return; setSaving(true); try { await collectionsService.changePromiseStatus(pending.promise.id, pending.status); setToast(pending.status === 'FULFILLED' ? ct('markKeptSuccess') : pending.status === 'BROKEN' ? ct('markBrokenSuccess') : ct('ptpCancelledSuccess')); setPending(undefined); setReloadKey(k => k + 1); } catch { setToast(ct('saveError')); setPending(undefined); } finally { setSaving(false); } };
  const actionCopy = pending?.status === 'FULFILLED' ? { title: ct('markKept'), message: ct('markKeptConfirm'), variant: 'primary' as const } : pending?.status === 'BROKEN' ? { title: ct('markBroken'), message: ct('markBrokenConfirm'), variant: 'danger' as const } : { title: ct('cancelPtp'), message: ct('cancelPtpConfirm'), variant: 'danger' as const };
  return <div><PageHeader eyebrow={ct('collections')} title={ct('promises')} description={ct('ptpSubtitle')} />{toast && <p className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{toast}</p>}<div className="mb-5 grid gap-3 md:grid-cols-[1fr_240px]"><label className="relative"><Search className="absolute top-3.5 h-5 w-5 text-slate-400" style={{ insetInlineStart: '0.9rem' }} /><input className="field ps-12" placeholder={ct('searchCases')} value={search} onChange={e => setSearch(e.target.value)} /></label><ProfessionalSelect className="field" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">{ct('allStatuses')}</option>{['ACTIVE', 'UPCOMING', 'DUE_TODAY', 'FULFILLED', 'PARTIALLY_FULFILLED', 'BROKEN', 'CANCELLED'].map(x => <option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></div>{error ? <ErrorState title={ct('loadError')} /> : !data ? <Loading /> : <Table data={data} setPage={setPage} ct={ct} money={f.money} date={f.date} onAction={(promise, s) => setPending({ promise, status: s })} />}
    {pending && <ConfirmDialog open title={actionCopy.title} message={actionCopy.message} description={`${pending.promise.customerName} · ${pending.promise.caseNumber}`} confirmVariant={actionCopy.variant} confirmLabel={ct('confirm')} cancelLabel={ct('cancel')} isConfirming={saving} onCancel={() => setPending(undefined)} onConfirm={() => void confirmAction()} />}
  </div>;
}
function Table({ data, setPage, ct, money, date, onAction }: { data: PagedResult<PromiseItem>; setPage: (p: number) => void; ct: (key: string) => string; money: (n: number) => string; date: (v: string) => string; onAction: (promise: PromiseItem, status: 'FULFILLED' | 'BROKEN' | 'CANCELLED') => void }) { return <div className="overflow-hidden rounded-2xl border border-mis-border bg-white"><div className="table-scroll"><table className="w-full min-w-[48rem] text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{[ct('customer'), ct('date'), ct('amount'), ct('actualPaid'), ct('collector'), ct('channel'), ct('status'), ct('actions')].map(x => <th key={x} className="px-5 py-4 text-start">{x}</th>)}</tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(x => <tr key={x.id}><td className="px-5 py-4"><Link className="font-bold text-mis-primary" to={`/collections/cases/${x.caseId}`}>{x.customerName}</Link><p className="mt-1 text-xs text-slate-500" data-bidi="ltr">{x.caseNumber}</p></td><td className="px-5 py-4" data-bidi="ltr">{date(x.promiseDate)}</td><td className="px-5 py-4 font-semibold" data-bidi="ltr">{money(x.promisedAmount)}</td><td className="px-5 py-4" data-bidi="ltr">{money(x.actualPaidAmount)}</td><td className="px-5 py-4">{x.collectorName}</td><td className="px-5 py-4">{ct(x.channel)}</td><td className="px-5 py-4"><CollectionStatus value={x.status} /></td><td className="px-5 py-4">{x.status === 'ACTIVE' ? <div className="flex items-center gap-1"><button type="button" onClick={() => onAction(x, 'FULFILLED')} aria-label={ct('markKept')} title={ct('markKept')} className="rounded-lg p-2 text-emerald-600 hover:bg-emerald-50"><CheckCircle2 className="h-4 w-4" /></button><button type="button" onClick={() => onAction(x, 'BROKEN')} aria-label={ct('markBroken')} title={ct('markBroken')} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50"><XCircle className="h-4 w-4" /></button><button type="button" onClick={() => onAction(x, 'CANCELLED')} aria-label={ct('cancelPtp')} title={ct('cancelPtp')} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Ban className="h-4 w-4" /></button></div> : <span className="text-xs text-slate-400">—</span>}</td></tr>)}</tbody></table>{data.items.length === 0 && <p className="p-12 text-center text-slate-500">{ct('noPromises')}</p>}</div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div>; }
function Loading() { return <div className="flex min-h-72 items-center justify-center"><LoadingSpinner /></div>; }
