import { Activity, Search, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { useLocalization } from '../../context/LocalizationContext';
import { adminService } from '../../features/admin/services/adminService';
import type { AdminAuditItem } from '../../features/admin/types/admin';

const copy={ar:{eyebrow:'رقابة غير قابلة للمحو',title:'سجل إدارة النظام',desc:'أثر زمني واضح لكل تغيير في الحسابات والصلاحيات؛ السجل للقراءة فقط.',search:'ابحث بالإجراء أو التفاصيل',event:'الحدث',target:'الحساب المتأثر',actor:'نفّذ بواسطة',details:'التفاصيل',time:'التوقيت',ip:'المصدر',empty:'لا توجد أحداث مطابقة.',error:'تعذر تحميل سجل الإدارة.',retry:'إعادة المحاولة'},en:{eyebrow:'Immutable oversight',title:'Administration audit',desc:'A clear timeline for every account and access change. This record is read-only.',search:'Search action or details',event:'Event',target:'Affected account',actor:'Performed by',details:'Details',time:'Time',ip:'Source',empty:'No matching events.',error:'Could not load the administration audit.',retry:'Try again'}};
const names:Record<string,{ar:string;en:string}>={USER_CREATED:{ar:'إنشاء مستخدم',en:'User created'},USER_ACTIVATED:{ar:'تفعيل مستخدم',en:'User activated'},USER_SUSPENDED:{ar:'إيقاف مستخدم',en:'User suspended'},ACCESS_REVIEW_COMPLETED:{ar:'اعتماد مراجعة صلاحيات',en:'Access review authorized'},PASSWORD_RESET_BY_ADMIN:{ar:'تعيين كلمة مرور مؤقتة',en:'Temporary password set'}};
export function AdminAuditPage(){const{language}=useLocalization();const t=copy[language];const[items,setItems]=useState<AdminAuditItem[]>([]);const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);const[failed,setFailed]=useState(false);const load=()=>{setLoading(true);setFailed(false);adminService.audit({search:search||undefined,pageSize:100}).then(x=>setItems(x.items)).catch(()=>setFailed(true)).finally(()=>setLoading(false))};useEffect(()=>{const id=setTimeout(load,250);return()=>clearTimeout(id)},[search]);return <div className="mx-auto max-w-[1500px]"><PageHeader eyebrow={t.eyebrow} title={t.title} description={t.desc}/><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-4"><label className="relative block max-w-lg"><Search className="absolute start-3 top-3 h-5 w-5 text-slate-400"/><input className="field !py-2.5 ps-10" placeholder={t.search} value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{failed?<ErrorState className="m-5" compact title={t.error} onRetry={load} retryLabel={t.retry}/>:loading&&!items.length?<div className="flex min-h-72 items-center justify-center"><LoadingSpinner/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3 text-start">{t.event}</th><th className="px-5 py-3 text-start">{t.target}</th><th className="px-5 py-3 text-start">{t.actor}</th><th className="px-5 py-3 text-start">{t.details}</th><th className="px-5 py-3 text-start">{t.time}</th><th className="px-5 py-3 text-start">{t.ip}</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(a=><tr key={a.id} className="align-top hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-2"><span className="rounded-lg bg-cyan-50 p-2 text-cyan-700"><Activity className="h-4 w-4"/></span><span className="font-bold text-slate-900">{names[a.action]?.[language]??a.action}</span></div></td><td className="px-5 py-4 font-bold text-slate-700">{a.targetName??a.targetType}</td><td className="px-5 py-4"><span className="inline-flex items-center gap-1.5 font-semibold text-slate-700"><ShieldCheck className="h-4 w-4 text-emerald-600"/>{a.actorName}</span></td><td className="max-w-md px-5 py-4 leading-6 text-slate-600">{a.details}</td><td className="px-5 py-4 text-slate-600">{new Intl.DateTimeFormat(language==='ar'?'ar-EG':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(a.occurredAt))}</td><td className="px-5 py-4 font-mono text-xs text-slate-500" dir="ltr">{a.sourceIp??'—'}</td></tr>)}</tbody></table>{!items.length&&<p className="py-16 text-center text-sm text-slate-500">{t.empty}</p>}</div>}</section></div>}
