import { AlertTriangle, ArrowUpLeft, CheckCircle2, Clock3, KeyRound, ShieldAlert, UserCheck, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { PageHeader } from '../../components/common/PageHeader';
import { useLocalization } from '../../context/LocalizationContext';
import { adminService } from '../../features/admin/services/adminService';
import type { AdminDashboard } from '../../features/admin/types/admin';

const text = {
  ar: { eyebrow: 'إدارة مبنية على المخاطر', title: 'ملخص إدارة النظام', desc: 'ما يحتاج قرارك الآن، وحالة الوصول على مستوى الشركة.', users: 'إجمالي المستخدمين', active: 'حسابات مفعلة', privileged: 'وصول مرتفع الحساسية', pending: 'طلبات تنتظر المراجعة', decisions: 'قرارات مطلوبة', noDecisions: 'لا توجد مخاطر معلقة تحتاج تدخلك الآن.', departments: 'توزيع المستخدمين', dept: 'القسم', total: 'الإجمالي', activeCol: 'مفعّل', high: 'صلاحيات حساسة', recent: 'آخر تغييرات الإدارة', actor: 'بواسطة', openUsers: 'مراجعة المستخدمين', retry: 'إعادة المحاولة', error: 'تعذر تحميل ملخص الإدارة.', never: 'لم يسجلوا الدخول', expiring: 'تنتهي قريبًا' },
  en: { eyebrow: 'Risk-based administration', title: 'System administration overview', desc: 'What needs your decision now and the company-wide access posture.', users: 'Total users', active: 'Active accounts', privileged: 'Privileged access', pending: 'Awaiting review', decisions: 'Decisions required', noDecisions: 'No outstanding access risks need your intervention now.', departments: 'User distribution', dept: 'Department', total: 'Total', activeCol: 'Active', high: 'Privileged', recent: 'Recent administration changes', actor: 'By', openUsers: 'Review users', retry: 'Try again', error: 'Could not load the administration overview.', never: 'Never signed in', expiring: 'Expiring soon' },
};

const actionNames: Record<string, { ar: string; en: string }> = { USER_CREATED: { ar: 'إنشاء مستخدم', en: 'User created' }, USER_ACTIVATED: { ar: 'تفعيل مستخدم', en: 'User activated' }, USER_SUSPENDED: { ar: 'إيقاف مستخدم', en: 'User suspended' }, ACCESS_REVIEW_COMPLETED: { ar: 'مراجعة صلاحيات', en: 'Access review completed' }, PASSWORD_RESET_BY_ADMIN: { ar: 'إعادة تعيين كلمة المرور', en: 'Password reset' } };

export function AdminDashboardPage() {
  const { language } = useLocalization(); const t = text[language]; const [data, setData] = useState<AdminDashboard>(); const [error, setError] = useState(false);
  const load = () => { setError(false); adminService.dashboard().then(setData).catch(() => setError(true)); };
  useEffect(load, []);
  if (error) return <ErrorState title={t.error} onRetry={load} retryLabel={t.retry} />;
  if (!data) return <div className="flex min-h-[420px] items-center justify-center"><LoadingSpinner /></div>;
  const cards = [{label:t.users,value:data.totalUsers,icon:Users,color:'text-sky-700 bg-sky-50'}, {label:t.active,value:data.activeUsers,icon:UserCheck,color:'text-emerald-700 bg-emerald-50'}, {label:t.privileged,value:data.privilegedUsers,icon:ShieldAlert,color:'text-amber-700 bg-amber-50'}, {label:t.pending,value:data.pendingAccessRequests,icon:KeyRound,color:'text-rose-700 bg-rose-50'}];
  return <div className="mx-auto max-w-[1500px]">
    <PageHeader eyebrow={t.eyebrow} title={t.title} description={t.desc} actions={<Link to="/admin/users" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#09263d] px-4 text-sm font-bold text-white hover:bg-[#113b59]">{t.openUsers}<ArrowUpLeft className="h-4 w-4"/></Link>} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,icon:Icon,color}) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-3 text-3xl font-black text-[#09263d]">{value.toLocaleString(language === 'ar' ? 'ar-EG' : 'en-US')}</p></div><span className={`rounded-xl p-3 ${color}`}><Icon className="h-5 w-5"/></span></div></article>)}</section>
    <div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4"><Clock3 className="h-5 w-5 text-amber-600"/><div><p className="text-sm font-bold text-slate-800">{t.expiring}</p><p className="text-2xl font-black text-[#09263d]">{data.expiringAccessCount}</p></div></div><div className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4"><AlertTriangle className="h-5 w-5 text-slate-500"/><div><p className="text-sm font-bold text-slate-800">{t.never}</p><p className="text-2xl font-black text-[#09263d]">{data.neverLoggedInCount}</p></div></div></div>
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-[#09263d]">{t.decisions}</h2><div className="mt-4 grid gap-3 lg:grid-cols-3">{data.decisionQueue.length ? data.decisionQueue.map(item => <Link to="/admin/users" key={item.type} className={`rounded-xl border p-4 transition hover:-translate-y-0.5 hover:shadow-md ${item.severity === 'HIGH' ? 'border-rose-200 bg-rose-50/70' : item.severity === 'MEDIUM' ? 'border-amber-200 bg-amber-50/70' : 'border-slate-200 bg-slate-50'}`}><div className="flex items-center justify-between"><p className="font-black text-slate-900">{language === 'ar' ? item.titleAr : item.titleEn}</p><span className="rounded-full bg-white px-2.5 py-1 text-sm font-black text-slate-800">{item.count}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{language === 'ar' ? item.descriptionAr : item.descriptionEn}</p></Link>) : <div className="col-span-full flex items-center gap-3 rounded-xl bg-emerald-50 p-4 text-emerald-800"><CheckCircle2 className="h-5 w-5"/><p className="text-sm font-bold">{t.noDecisions}</p></div>}</div></section>
    <div className="mt-7 grid gap-7 xl:grid-cols-[1.1fr_.9fr]">
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-black text-[#09263d]">{t.departments}</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3 text-start">{t.dept}</th><th className="px-5 py-3 text-start">{t.total}</th><th className="px-5 py-3 text-start">{t.activeCol}</th><th className="px-5 py-3 text-start">{t.high}</th></tr></thead><tbody className="divide-y divide-slate-100">{data.departments.map(d => <tr key={d.id}><td className="px-5 py-4 font-bold text-slate-800">{language === 'ar' ? d.nameAr : d.nameEn}</td><td className="px-5 py-4">{d.totalUsers}</td><td className="px-5 py-4 text-emerald-700">{d.activeUsers}</td><td className="px-5 py-4 text-amber-700">{d.privilegedUsers}</td></tr>)}</tbody></table></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-black text-[#09263d]">{t.recent}</h2></div><div className="divide-y divide-slate-100 px-5">{data.recentActivity.map(a => <article key={a.id} className="py-4"><div className="flex items-start gap-3"><span className="mt-1 h-2 w-2 rounded-full bg-cyan-500"/><div><p className="text-sm font-bold text-slate-800">{actionNames[a.action]?.[language] ?? a.action} · {a.targetName ?? a.targetType}</p><p className="mt-1 text-xs text-slate-500">{t.actor} {a.actorName} · {new Intl.DateTimeFormat(language === 'ar' ? 'ar-EG' : 'en-GB', {dateStyle:'medium',timeStyle:'short'}).format(new Date(a.occurredAt))}</p><p className="mt-1 line-clamp-1 text-xs text-slate-500">{a.details}</p></div></div></article>)}</div></section>
    </div>
  </div>;
}
