import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { DateControl } from '../../components/forms/DateControl';
import { AlertOctagon, Check, ChevronLeft, CircleUserRound, KeyRound, LockKeyhole, Plus, Search, ShieldCheck, ShieldOff, SlidersHorizontal, UserCheck, UserX, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Button } from '../../components/common/Button';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { PageHeader } from '../../components/common/PageHeader';
import { useToast } from '../../components/common/Toast';
import { useLocalization } from '../../context/LocalizationContext';
import { adminService } from '../../features/admin/services/adminService';
import type { AdminPermission, AdminReferenceData, AdminUser, CreateAdminUser, SaveAccessGrant } from '../../features/admin/types/admin';
import { getApiErrorMessage } from '../../services/apiClient';

const copy = {
  ar: { eyebrow:'الهوية والوصول',title:'المستخدمون والصلاحيات',desc:'منح أقل صلاحية لازمة، بنطاق واضح وقرار قابل للمراجعة.',add:'إضافة مستخدم',search:'ابحث بالاسم أو الكود أو البريد',allDept:'كل الأقسام',allStatus:'كل الحالات',active:'مفعّل',inactive:'غير مفعّل',user:'المستخدم',department:'القسم',access:'الوصول الحالي',lastLogin:'آخر دخول',actions:'الإجراء',never:'لم يدخل',permissions:'صلاحية',review:'مراجعة الصلاحيات',security:'الحساب والأمان',noUsers:'لا يوجد مستخدمون مطابقون.',error:'تعذر تحميل المستخدمين.',retry:'إعادة المحاولة',pending:'مقترحة',roles:'أدوار',grants:'صلاحيات',accessTitle:'مراجعة وصول',accessDesc:'حدد ما يحتاجه هذا المستخدم فعلًا لتنفيذ عمله.',roleTemplates:'الأدوار الوظيفية',permissionGroups:'الصلاحيات التفصيلية',scope:'النطاق',own:'بياناته فقط',team:'فريقه',dept:'قسمه',client:'عميل محدد',all:'كل بيانات الموديول',expires:'تاريخ الانتهاء (اختياري)',clients:'العملاء المسموحون',impact:'مراجعة الأثر قبل التنفيذ',criticalWarning:'الصلاحيات المحددة قد تسمح بقراءة بيانات حساسة أو اعتماد عمليات أو تصدير بيانات. منحها يعني أن المستخدم سيصل إلى بيانات تشغيلية حقيقية داخل النطاق المحدد.',adminRoleWarning:'تنبيه حرج: دور Admin يمنح تحكمًا غير مقيد في المستخدمين والصلاحيات وكل الموديولات. لا تمنحه لحساب تشغيل عادي.',selected:'صلاحية محددة',critical:'عالية/حرجة',reason:'سبب العمل',reasonHint:'اكتب لماذا يحتاج المستخدم هذه الصلاحيات الآن (12 حرفًا على الأقل).',ack:'أقر أنني راجعت حاجة العمل والنطاق، وأن الوصول سيُسجل باسمي ويمكن مراجعته.',phrase:'للتأكيد اكتب بالإنجليزية: GRANT ACCESS',adminPhrase:'لتأكيد دور Admin اكتب بالإنجليزية: GRANT ADMIN ACCESS',save:'اعتماد الوصول',cancel:'إلغاء',success:'تم تحديث الصلاحيات وتسجيل القرار.',low:'منخفضة',medium:'متوسطة',high:'عالية',criticalRisk:'حرجة',statusTitle:'الحساب والأمان',reset:'تعيين كلمة مرور مؤقتة',password:'كلمة المرور المؤقتة',passwordHelp:'12 حرفًا على الأقل: حرف كبير وصغير ورقم ورمز.',statusReason:'سبب الإجراء',activate:'تفعيل الحساب',suspend:'إيقاف الحساب فورًا',statusWarning:'إيقاف الحساب يمنع أي تسجيل دخول جديد. التفعيل لا يمنح صلاحيات غير التي تمت مراجعتها.',statusSuccess:'تم تحديث حالة الحساب.',passwordSuccess:'تم تعيين كلمة مرور مؤقتة آمنة.',createTitle:'إضافة مستخدم جديد',fullName:'الاسم الكامل',username:'اسم الدخول',email:'البريد الإلكتروني',createReason:'سبب إنشاء الحساب',create:'إنشاء الحساب',createSuccess:'تم إنشاء الحساب بنجاح.',noAccess:'لا توجد صلاحيات فعالة',planned:'الموديول قيد التجهيز؛ الصلاحية ستصبح فعالة عند إطلاقه.' },
  en: { eyebrow:'Identity & access',title:'Users and access',desc:'Grant the least access needed, with a clear scope and reviewable decision.',add:'Add user',search:'Search name, code, or email',allDept:'All departments',allStatus:'All statuses',active:'Active',inactive:'Inactive',user:'User',department:'Department',access:'Current access',lastLogin:'Last sign-in',actions:'Action',never:'Never',permissions:'permission',review:'Review access',security:'Account & security',noUsers:'No matching users.',error:'Could not load users.',retry:'Try again',pending:'Proposed',roles:'Roles',grants:'Permissions',accessTitle:'Access review',accessDesc:'Select only what this user genuinely needs to do their job.',roleTemplates:'Functional roles',permissionGroups:'Granular permissions',scope:'Scope',own:'Own records only',team:'Their team',dept:'Their department',client:'Specific client',all:'All module data',expires:'Expiry date (optional)',clients:'Allowed clients',impact:'Review impact before execution',criticalWarning:'Selected access may reveal sensitive data, approve transactions, or export records. Granting it gives the user real operational access within the selected scope.',adminRoleWarning:'Critical warning: Admin grants unrestricted control over users, access, and every module. Never use it for a normal operational account.',selected:'selected permissions',critical:'high/critical',reason:'Business reason',reasonHint:'Explain why this user needs the access now (at least 12 characters).',ack:'I confirm I reviewed the business need and scope, and understand this decision is recorded under my account.',phrase:'To confirm, type: GRANT ACCESS',adminPhrase:'To confirm the Admin role, type: GRANT ADMIN ACCESS',save:'Authorize access',cancel:'Cancel',success:'Access updated and the decision was recorded.',low:'Low',medium:'Medium',high:'High',criticalRisk:'Critical',statusTitle:'Account & security',reset:'Set temporary password',password:'Temporary password',passwordHelp:'At least 12 characters with upper, lower, number, and symbol.',statusReason:'Reason for action',activate:'Activate account',suspend:'Suspend account now',statusWarning:'Suspension blocks new sign-ins immediately. Activation grants only access that has already been reviewed.',statusSuccess:'Account status updated.',passwordSuccess:'A secure temporary password was set.',createTitle:'Add a new user',fullName:'Full name',username:'Sign-in name',email:'Email',createReason:'Reason for creating account',create:'Create account',createSuccess:'User created successfully.',noAccess:'No effective permissions',planned:'This module is planned; access will apply when it is released.' },
};
const groups: Record<string,{ar:string;en:string;planned?:boolean}> = { ADMIN:{ar:'إدارة النظام',en:'Administration'},HR:{ar:'الموارد البشرية',en:'Human Resources'},ACCOUNTING:{ar:'الحسابات',en:'Accounting',planned:true},LEGAL:{ar:'الشؤون القانونية',en:'Legal',planned:true},DATA_ENTRY:{ar:'إدخال البيانات',en:'Data Entry',planned:true},COLLECTIONS:{ar:'التحصيل والبنوك',en:'Collections'} };

export function AdminUsersPage() {
  const { language } = useLocalization(); const t = copy[language]; const toast = useToast();
  const [refs,setRefs]=useState<AdminReferenceData>(); const [users,setUsers]=useState<AdminUser[]>([]); const [total,setTotal]=useState(0); const [loading,setLoading]=useState(true); const [failed,setFailed]=useState(false);
  const [search,setSearch]=useState(''); const [department,setDepartment]=useState(''); const [status,setStatus]=useState(''); const [selected,setSelected]=useState<AdminUser>(); const [mode,setMode]=useState<'access'|'security'|'create'>();
  const load = async () => { setLoading(true);setFailed(false);try { const [r,u]=await Promise.all([refs ? Promise.resolve(refs):adminService.referenceData(),adminService.users({search:search||undefined,department:department||undefined,status:status||undefined,pageSize:100})]);setRefs(r);setUsers(u.items);setTotal(u.total); } catch { setFailed(true); } finally { setLoading(false); } };
  useEffect(()=>{ const id=window.setTimeout(load,250);return()=>window.clearTimeout(id);},[search,department,status]);
  const refreshUser=(user:AdminUser)=>{setUsers(current=>current.map(x=>x.id===user.id?user:x));setSelected(user);};
  if (failed && !users.length) return <ErrorState title={t.error} onRetry={load} retryLabel={t.retry}/>;
  return <div className="mx-auto max-w-[1600px]">
    <PageHeader eyebrow={t.eyebrow} title={t.title} description={t.desc} actions={<Button fullWidth={false} leftIcon={<Plus className="h-4 w-4"/>} onClick={()=>setMode('create')} size="md">{t.add}</Button>}/>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 lg:flex-row"><label className="relative flex-1"><Search className="absolute start-3 top-3 h-5 w-5 text-slate-400"/><input className="field !py-2.5 ps-10" placeholder={t.search} value={search} onChange={e=>setSearch(e.target.value)}/></label><ProfessionalSelect className="field !w-auto !py-2.5" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">{t.allDept}</option>{refs?.departments.map(d=><option key={d.id} value={d.code}>{language==='ar'?d.nameAr:d.nameEn}</option>)}</ProfessionalSelect><ProfessionalSelect className="field !w-auto !py-2.5" value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t.allStatus}</option><option value="ACTIVE">{t.active}</option><option value="INACTIVE">{t.inactive}</option></ProfessionalSelect></div>
      {loading&&!users.length?<div className="flex min-h-72 items-center justify-center"><LoadingSpinner/></div>:<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3 text-start">{t.user}</th><th className="px-5 py-3 text-start">{t.department}</th><th className="px-5 py-3 text-start">{t.access}</th><th className="px-5 py-3 text-start">{t.lastLogin}</th><th className="px-5 py-3 text-start">{t.actions}</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map(user=><tr key={user.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 font-black text-[#0b3b58]">{user.fullName.slice(0,1).toUpperCase()}</span><div><p className="font-bold text-slate-900">{user.fullName}</p><p className="mt-0.5 text-xs text-slate-500" dir="ltr">{user.loginCode} · {user.username}</p></div><span className={`ms-2 rounded-full px-2 py-1 text-[11px] font-bold ${user.isActive?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{user.isActive?t.active:t.inactive}</span></div></td><td className="px-5 py-4 font-semibold text-slate-700">{language==='ar'?user.departmentNameAr:user.departmentNameEn}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-1.5">{user.roles.slice(0,2).map(r=><span key={r.id} className="rounded-full bg-cyan-50 px-2 py-1 text-xs font-bold text-cyan-800">{r.name}</span>)}{user.accessGrants.length>0&&<span className="rounded-full bg-indigo-50 px-2 py-1 text-xs font-bold text-indigo-700">{user.accessGrants.length} {t.permissions}</span>}{!user.roles.length&&!user.accessGrants.length&&<span className="text-xs text-slate-400">{t.noAccess}</span>}{user.accessGrants.some(g=>g.status==='PENDING')&&<span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">{t.pending}</span>}</div></td><td className="px-5 py-4 text-slate-600">{user.lastLoginAt?new Intl.DateTimeFormat(language==='ar'?'ar-EG':'en-GB',{dateStyle:'medium'}).format(new Date(user.lastLoginAt)):t.never}</td><td className="px-5 py-4"><div className="flex gap-2"><button className="inline-flex items-center gap-1.5 rounded-lg bg-[#09263d] px-3 py-2 text-xs font-bold text-white hover:bg-[#164867]" onClick={()=>{setSelected(user);setMode('access')}}><SlidersHorizontal className="h-3.5 w-3.5"/>{t.review}</button><button className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700 hover:bg-slate-50" onClick={()=>{setSelected(user);setMode('security')}}><KeyRound className="h-3.5 w-3.5"/>{t.security}</button></div></td></tr>)}</tbody></table>{!users.length&&<p className="py-16 text-center text-sm text-slate-500">{t.noUsers}</p>}</div>}
      <div className="border-t border-slate-200 px-5 py-3 text-xs font-semibold text-slate-500">{total} {t.user}</div>
    </section>
    {selected&&refs&&<AccessReviewModal open={mode==='access'} user={selected} refs={refs} language={language} onClose={()=>setMode(undefined)} onSaved={u=>{refreshUser(u);setMode(undefined);toast.success(t.success)}}/>}
    {selected&&<SecurityModal open={mode==='security'} user={selected} language={language} onClose={()=>setMode(undefined)} onSaved={u=>{refreshUser(u);toast.success(t.statusSuccess)}}/>}
    {refs&&<CreateUserModal open={mode==='create'} refs={refs} language={language} onClose={()=>setMode(undefined)} onCreated={u=>{setUsers(v=>[u,...v]);setTotal(v=>v+1);setMode(undefined);toast.success(t.createSuccess)}}/>}
  </div>;
}

function AccessReviewModal({open,user,refs,language,onClose,onSaved}:{open:boolean;user:AdminUser;refs:AdminReferenceData;language:'ar'|'en';onClose:()=>void;onSaved:(u:AdminUser)=>void}) {
  const t=copy[language]; const toast=useToast(); const [roles,setRoles]=useState<string[]>([]); const [grants,setGrants]=useState<SaveAccessGrant[]>([]); const [phrase,setPhrase]=useState(''); const [saving,setSaving]=useState(false);
  useEffect(()=>{if(open){setRoles(user.roles.map(x=>x.id));setGrants(user.accessGrants.filter(x=>x.status!=='REVOKED').map(x=>({permissionCode:x.permissionCode,scopeType:x.scopeType,clientOrganizationId:x.clientOrganizationId,expiresAt:x.expiresAt?.slice(0,10)})));setPhrase('');}},[open,user]);
  const selectedCodes=new Set(grants.map(x=>x.permissionCode)); const chosen=refs.permissions.filter(x=>selectedCodes.has(x.code)); const adminRoleSelected=refs.roles.some(x=>x.name==='Admin'&&roles.includes(x.id)); const high=chosen.filter(x=>x.riskLevel==='HIGH'||x.riskLevel==='CRITICAL').length+(adminRoleSelected?1:0);
  const togglePermission=(p:AdminPermission)=>setGrants(current=>selectedCodes.has(p.code)?current.filter(x=>x.permissionCode!==p.code):[...current,{permissionCode:p.code,scopeType:p.allowedScopes[0]}]);
  const updateGrant=(code:string,changes:Partial<SaveAccessGrant>)=>setGrants(current=>current.map(x=>x.permissionCode===code?{...x,...changes}:x));
  const changeScope=(code:string,scopeType:string)=>setGrants(current=>{const first=current.find(x=>x.permissionCode===code);return [...current.filter(x=>x.permissionCode!==code),{permissionCode:code,scopeType,expiresAt:first?.expiresAt}]});
  const toggleClient=(code:string,clientOrganizationId:string,checked:boolean)=>setGrants(current=>{const same=current.filter(x=>x.permissionCode===code);const rest=current.filter(x=>x.permissionCode!==code);const expiry=same[0]?.expiresAt;const clientGrants=same.filter(x=>x.scopeType==='CLIENT'&&x.clientOrganizationId!==clientOrganizationId);if(checked)clientGrants.push({permissionCode:code,scopeType:'CLIENT',clientOrganizationId,expiresAt:expiry});return [...rest,...clientGrants]});
  const submit=async()=>{setSaving(true);try{const payloadGrants=grants.flatMap(g=>g.scopeType==='CLIENT'&&!g.clientOrganizationId?[]:[g]).map(g=>({...g,expiresAt:g.expiresAt?new Date(`${g.expiresAt}T23:59:59.999Z`).toISOString():undefined}));const result=await adminService.saveAccess(user.id,{roleIds:roles,grants:payloadGrants,confirmationPhrase:adminRoleSelected?phrase:''});onSaved(result);}catch(e){toast.error(getApiErrorMessage(e,language==='ar'?'تعذر اعتماد الصلاحيات. راجع البيانات وحاول مرة أخرى.':'Could not authorize access. Review the details and try again.'));}finally{setSaving(false)}};
  const scopeLabel=(s:string)=>s==='OWN'?t.own:s==='TEAM'?t.team:s==='DEPARTMENT'?t.dept:s==='CLIENT'?t.client:t.all;
  return <Modal open={open} onClose={onClose} size="full" className="h-[calc(100vh-2rem)]" title={`${t.accessTitle} — ${user.fullName}`} description={`${t.accessDesc} ${user.loginCode}`} bodyClassName="p-0" footer={<><Button fullWidth={false} variant="outline" size="md" onClick={onClose}>{t.cancel}</Button><Button fullWidth={false} size="md" isLoading={saving} disabled={(adminRoleSelected&&phrase!=='GRANT ADMIN ACCESS')||grants.some(g=>g.scopeType==='CLIENT'&&!g.clientOrganizationId)} onClick={submit} leftIcon={<ShieldCheck className="h-4 w-4"/>}>{t.save}</Button></>}>
    <div className="grid h-full min-h-0 overflow-y-auto xl:grid-cols-[260px_1fr_360px] xl:overflow-hidden">
      <aside className="border-e border-slate-200 bg-slate-50 p-5 xl:min-h-0 xl:overflow-y-auto xl:overscroll-contain"><p className="text-xs font-black uppercase tracking-wider text-slate-400">{t.roleTemplates}</p><div className="mt-3 space-y-2">{refs.roles.map(role=><label key={role.id} className={`flex cursor-pointer gap-3 rounded-xl border p-3 ${roles.includes(role.id)?'border-cyan-300 bg-white shadow-sm':'border-transparent hover:bg-white'}`}><input type="checkbox" checked={roles.includes(role.id)} onChange={()=>setRoles(v=>v.includes(role.id)?v.filter(x=>x!==role.id):[...v,role.id])}/><div><p className="text-sm font-bold text-slate-800">{role.name}</p><p className="mt-1 text-xs leading-5 text-slate-500">{role.description}</p></div></label>)}</div></aside>
      <main className="p-5 sm:p-6 xl:min-h-0 xl:overflow-y-auto xl:overscroll-contain"><p className="text-xs font-black uppercase tracking-wider text-slate-400">{t.permissionGroups}</p><div className="mt-4 space-y-6">{Object.entries(groups).map(([group,label])=>{const items=refs.permissions.filter(p=>p.group===group);return <section key={group}><div className="mb-3 flex items-center gap-2"><h3 className="font-black text-[#09263d]">{label[language]}</h3>{label.planned&&<span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-500">{t.planned}</span>}</div><div className="grid gap-3 lg:grid-cols-2">{items.map(p=>{const grant=grants.find(g=>g.permissionCode===p.code);const clientIds=grants.filter(g=>g.permissionCode===p.code&&g.scopeType==='CLIENT').map(g=>g.clientOrganizationId);return <article key={p.code} className={`rounded-xl border p-4 transition ${grant?'border-cyan-300 bg-cyan-50/30':'border-slate-200'}`}><button className="flex w-full items-start gap-3 text-start" onClick={()=>togglePermission(p)}><span className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded border ${grant?'border-cyan-600 bg-cyan-600 text-white':'border-slate-300'}`}>{grant&&<Check className="h-3.5 w-3.5"/>}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><strong className="text-sm text-slate-900">{language==='ar'?p.nameAr:p.nameEn}</strong><RiskBadge risk={p.riskLevel} language={language}/></span><span className="mt-1 block text-xs leading-5 text-slate-500">{language==='ar'?p.descriptionAr:p.descriptionEn}</span></span></button>{grant&&<div className="mt-4 grid gap-3 border-t border-slate-200 pt-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">{t.scope}<ProfessionalSelect className="field mt-1 !py-2 text-xs" value={grant.scopeType} onChange={e=>changeScope(p.code,e.target.value)}>{p.allowedScopes.map(s=><option key={s} value={s}>{scopeLabel(s)}</option>)}</ProfessionalSelect></label><label className="text-xs font-bold text-slate-600">{t.expires}<DateControl className="field mt-1 !py-2 text-xs"  value={grant.expiresAt??''} onChange={e=>updateGrant(p.code,{expiresAt:e.target.value||undefined})}/></label>{grant.scopeType==='CLIENT'&&<div className="sm:col-span-2"><p className="text-xs font-bold text-slate-600">{t.clients}</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{refs.clients.filter(c=>c.isActive).map(c=><label key={c.id} className={`flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-2 text-xs ${clientIds.includes(c.id)?'border-cyan-300 bg-white text-cyan-900':'border-slate-200 bg-white text-slate-600'}`}><input type="checkbox" checked={clientIds.includes(c.id)} onChange={e=>toggleClient(p.code,c.id,e.target.checked)}/><span>{language==='ar'?c.nameAr:c.nameEn}</span></label>)}</div></div>}</div>}</article>})}</div></section>})}</div></main>
      <aside className="overflow-y-auto border-s border-slate-200 bg-[#f8fafc] p-5"><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex gap-3"><AlertOctagon className="h-5 w-5 shrink-0 text-amber-700"/><div><h3 className="font-black text-amber-900">{t.impact}</h3><p className="mt-2 text-xs leading-6 text-amber-900/80">{t.criticalWarning}</p></div></div></div>{adminRoleSelected&&<div className="mt-3 rounded-xl border-2 border-rose-300 bg-rose-50 p-4 text-xs font-bold leading-6 text-rose-900"><AlertOctagon className="mb-2 h-5 w-5"/>{t.adminRoleWarning}</div>}<div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-2xl font-black text-[#09263d]">{chosen.length}</p><p className="text-xs text-slate-500">{t.selected}</p></div><div className="rounded-xl border border-rose-200 bg-white p-3"><p className="text-2xl font-black text-rose-700">{high}</p><p className="text-xs text-slate-500">{t.critical}</p></div></div>{adminRoleSelected&&<label className="mt-5 block text-xs font-black text-rose-800">{t.adminPhrase}<input className="field mt-2 text-sm" dir="ltr" autoComplete="off" value={phrase} onChange={e=>setPhrase(e.target.value)}/></label>}</aside>
    </div>
  </Modal>;
}

function RiskBadge({risk,language}:{risk:AdminPermission['riskLevel'];language:'ar'|'en'}) { const t=copy[language]; const label=risk==='LOW'?t.low:risk==='MEDIUM'?t.medium:risk==='HIGH'?t.high:t.criticalRisk; const cls=risk==='CRITICAL'?'bg-rose-100 text-rose-700':risk==='HIGH'?'bg-amber-100 text-amber-700':risk==='MEDIUM'?'bg-sky-100 text-sky-700':'bg-slate-100 text-slate-600'; return <span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-black ${cls}`}>{label}</span> }

function SecurityModal({open,user,language,onClose,onSaved}:{open:boolean;user:AdminUser;language:'ar'|'en';onClose:()=>void;onSaved:(u:AdminUser)=>void}) { const t=copy[language],toast=useToast();const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const act=async(kind:'status'|'password')=>{setBusy(true);try{if(kind==='password'){await adminService.resetPassword(user.id,password);setPassword('');toast.success(t.passwordSuccess)}else{const u=await adminService.setStatus(user.id,!user.isActive);onSaved(u)}}catch(e){toast.error(getApiErrorMessage(e,language==='ar'?'تعذر تنفيذ الإجراء.':'Could not complete the action.'))}finally{setBusy(false)}};return <Modal open={open} onClose={onClose} size="md" title={`${t.statusTitle} — ${user.fullName}`}><div className="rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm leading-6 text-sky-900">{t.statusWarning}</div><div className="mt-5 rounded-xl border border-slate-200 p-4"><p className="font-black text-slate-900">{t.reset}</p><label className="mt-3 block text-sm font-bold text-slate-700">{t.password}<input type="password" className="field mt-2" value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="mt-2 text-xs text-slate-500">{t.passwordHelp}</p><Button className="mt-3" fullWidth={false} size="md" variant="outline" disabled={password.length<12} isLoading={busy} onClick={()=>act('password')} leftIcon={<LockKeyhole className="h-4 w-4"/>}>{t.reset}</Button></div><Button className="mt-5" fullWidth={false} size="md" variant={user.isActive?'danger':'primary'} isLoading={busy} onClick={()=>act('status')} leftIcon={user.isActive?<UserX className="h-4 w-4"/>:<UserCheck className="h-4 w-4"/>}>{user.isActive?t.suspend:t.activate}</Button></Modal> }

function CreateUserModal({open,refs,language,onClose,onCreated}:{open:boolean;refs:AdminReferenceData;language:'ar'|'en';onClose:()=>void;onCreated:(u:AdminUser)=>void}) { const t=copy[language],toast=useToast();const initial:CreateAdminUser={fullName:'',username:'',email:'',departmentId:refs.departments[0]?.id??'',temporaryPassword:'',roleIds:[]};const [form,setForm]=useState(initial);const [busy,setBusy]=useState(false);useEffect(()=>{if(open)setForm(initial)},[open]);const set=(key:keyof CreateAdminUser,value:CreateAdminUser[keyof CreateAdminUser])=>setForm(v=>({...v,[key]:value}));const submit=async()=>{setBusy(true);try{onCreated(await adminService.createUser(form))}catch(e){toast.error(getApiErrorMessage(e,language==='ar'?'تعذر إنشاء المستخدم.':'Could not create user.'))}finally{setBusy(false)}};return <Modal open={open} onClose={onClose} size="lg" title={t.createTitle} footer={<><Button fullWidth={false} size="md" variant="outline" onClick={onClose}>{t.cancel}</Button><Button fullWidth={false} size="md" isLoading={busy} disabled={!form.fullName||!form.username||!form.email||form.temporaryPassword.length<12} onClick={submit}>{t.create}</Button></>}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">{t.fullName}<input className="field mt-2" value={form.fullName} onChange={e=>set('fullName',e.target.value)}/></label><label className="text-sm font-bold text-slate-700">{t.username}<input className="field mt-2" dir="ltr" value={form.username} onChange={e=>set('username',e.target.value)}/></label><label className="text-sm font-bold text-slate-700">{t.email}<input className="field mt-2" dir="ltr" type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label className="text-sm font-bold text-slate-700">{t.department}<ProfessionalSelect className="field mt-2" value={form.departmentId} onChange={e=>set('departmentId',e.target.value)}>{refs.departments.map(d=><option key={d.id} value={d.id}>{language==='ar'?d.nameAr:d.nameEn}</option>)}</ProfessionalSelect></label><label className="text-sm font-bold text-slate-700 sm:col-span-2">{t.password}<input className="field mt-2" type="password" value={form.temporaryPassword} onChange={e=>set('temporaryPassword',e.target.value)}/><span className="mt-1 block text-xs font-normal text-slate-500">{t.passwordHelp}</span></label></div></Modal> }
