export function importText(arabic: boolean, en: string, ar: string): string {
  return arabic ? ar : en;
}

export const importCopy = {
  dropTitle: (ar: boolean) => importText(ar, 'Drop the Excel file here', 'اسحب ملف الإكسل هنا'),
  dropHelp: (ar: boolean) => importText(ar, 'or click to browse. The system recognizes columns automatically.', 'أو اضغط للاختيار. السيستم هيتعرّف على الأعمدة لوحده.'),
  formats: (ar: boolean) => importText(ar, 'XLSX • XLS • CSV — up to 50 MB', 'XLSX • XLS • CSV — حتى 50 ميجابايت'),
  dropActive: (ar: boolean) => importText(ar, 'Drop the file to start', 'أفلت الملف عشان نبدأ'),
  replaceFile: (ar: boolean) => importText(ar, 'Replace file', 'تبديل الملف'),
  removeFile: (ar: boolean) => importText(ar, 'Remove file', 'إزالة الملف'),
  sheetsTitle: (ar: boolean) => importText(ar, 'Workbook sheets', 'أوراق الملف'),
  sheetsHelp: (ar: boolean) => importText(ar, 'Choose one sheet or import all selected sheets together.', 'اختار شيت واحد أو كل الشيتات المحددة مع بعض.'),
  selectAllSheets: (ar: boolean) => importText(ar, 'Select all sheets', 'اختيار كل الشيتات'),
  selectBestSheet: (ar: boolean) => importText(ar, 'Best match only', 'الأفضل تطابقًا فقط'),
  sheetSkipped: (ar: boolean) => importText(ar, 'Instructions / reference — skipped by default', 'تعليمات / مرجع — متتخطي افتراضيًا'),
  columnsTitle: (ar: boolean) => importText(ar, 'Recognized automatically', 'اتعرف عليها تلقائيًا'),
  columnsHelp: (ar: boolean) => importText(ar, 'Manual mapping is only needed for unusual files.', 'التعيين اليدوي للحالات النادرة بس.'),
  advancedMapping: (ar: boolean) => importText(ar, 'Advanced mapping', 'تعيين يدوي متقدم'),
  hideAdvanced: (ar: boolean) => importText(ar, 'Hide advanced mapping', 'إخفاء التعيين اليدوي'),
  extrasTitle: (ar: boolean) => importText(ar, 'Extra columns in this file', 'أعمدة زيادة في الملف'),
  extrasHelp: (ar: boolean) => importText(ar, 'These are not standard system fields. Show the ones you want to keep with the imported records.', 'دي مش حقول أساسية في السيستم. فعّل اللي عايزه يظهر مع البيانات بعد الرفع.'),
  showExtra: (ar: boolean) => importText(ar, 'Show with records', 'اعرضها مع السجلات'),
  hideExtra: (ar: boolean) => importText(ar, 'Keep hidden', 'خليها مخفية'),
  showAllExtras: (ar: boolean) => importText(ar, 'Show all extra columns', 'إظهار كل الأعمدة الزيادة'),
  hideAllExtras: (ar: boolean) => importText(ar, 'Hide extra columns', 'إخفاء الأعمدة الزيادة'),
  noExtras: (ar: boolean) => importText(ar, 'No extra columns beyond the system fields.', 'مفيش أعمدة زيادة عن حقول السيستم.'),
  previewReady: (ar: boolean, count: number) => importText(ar, `${count} row(s) ready. Nothing is saved until you confirm.`, `${count} صف جاهز. مفيش حاجة هتتخزن قبل التأكيد.`),
  excludeSelected: (ar: boolean) => importText(ar, 'Remove selected rows', 'شيل الصفوف المحددة'),
  includeSelected: (ar: boolean) => importText(ar, 'Keep selected rows', 'رجّع الصفوف المحددة'),
  excludedBadge: (ar: boolean) => importText(ar, 'Removed from this import', 'اتشالت من الرفع ده'),
  confirmTitle: (ar: boolean) => importText(ar, 'Confirm import', 'تأكيد الرفع'),
  confirmMessage: (ar: boolean, count: number) => importText(ar, `Import ${count} reviewed row(s) into the system?`, `تأكيد رفع ${count} صف بعد المراجعة؟`),
  confirmAction: (ar: boolean, count: number) => importText(ar, `Confirm import (${count})`, `تأكيد الرفع (${count})`),
  editRow: (ar: boolean) => importText(ar, 'Edit', 'تعديل'),
  removeRow: (ar: boolean) => importText(ar, 'Remove', 'شيل'),
  restoreRow: (ar: boolean) => importText(ar, 'Restore', 'رجّع'),
  selectRow: (ar: boolean) => importText(ar, 'Select row', 'تحديد الصف'),
  extraFileFields: (ar: boolean) => importText(ar, 'Extra file fields', 'حقول إضافية من الملف'),
  extraFileFieldsHelp: (ar: boolean) => importText(ar, 'Values imported from columns that are not standard system fields.', 'قيم اترفعت من أعمدة مش موجودة أصلًا في السيستم.'),
} as const;
