import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { DateControl } from '../../components/forms/DateControl';
import { Eye, Plus, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Pagination } from '../../components/common/Pagination';
import { FinanceStatus, useFinanceText } from '../../features/finance/financeUi';
import { financeService } from '../../features/finance/services/financeService';
import type { CreateManualJournalInput, FinanceAccount, FinancePagedResult, JournalListItem, ManualJournalLineInput } from '../../features/finance/types/finance';
import { getApiErrorMessage } from '../../services/apiClient';

const today = () => new Date().toISOString().slice(0, 10);
const emptyLine = (): ManualJournalLineInput => ({ accountId: '', debit: 0, credit: 0, description: '' });

export function FinanceJournalsPage() {
  const f = useFinanceText(); const [params, setParams] = useSearchParams(); const page = Number(params.get('page') ?? 1); const status = params.get('status') ?? ''; const [data, setData] = useState<FinancePagedResult<JournalListItem>>(); const [accounts, setAccounts] = useState<FinanceAccount[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const load = () => { setError(''); Promise.all([financeService.journals(page, status), financeService.accounts()]).then(([journals, chart]) => { setData(journals); setAccounts(chart.filter(x => x.postingAllowed && !x.controlAccountType)); }).catch(e => setError(getApiErrorMessage(e, f.text('تعذر تحميل القيود', 'Could not load journals')))); }; useEffect(load, [page, status]);
  if (error && !data) return <ErrorState title={error} onRetry={load} />; if (!data) return <div className="grid min-h-[420px] place-items-center"><LoadingSpinner /></div>;
  return <div><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-mis-primary">GENERAL LEDGER</p><h1 className="mt-2 text-3xl font-bold text-mis-navy">{f.text('دفتر القيود اليومية', 'Journal Register')}</h1><p className="mt-2 text-sm text-slate-500">{f.text('كل قيد متوازن وله مصدر وحالة واعتمادات وأثر تدقيق.', 'Every entry is balanced and carries its source, state, approvals, and audit history.')}</p></div><button onClick={() => setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-mis-primary px-5 py-3 text-sm font-bold text-white shadow-sm"><Plus className="h-4 w-4" />{f.text('قيد يدوي جديد', 'New manual journal')}</button></header>
    <div className="mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-mis-border bg-white p-3">{['','DRAFT','PENDING_APPROVAL','APPROVED','POSTED','REVERSED'].map(x => <button key={x} onClick={() => setParams(x ? { status: x } : {})} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-semibold ${status === x ? 'bg-mis-pale text-mis-deep' : 'text-slate-500 hover:bg-slate-50'}`}>{x || f.text('الكل', 'All')}</button>)}</div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="mt-5 overflow-hidden rounded-2xl border border-mis-border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4 text-start">{f.text('رقم القيد', 'Journal no.')}</th><th className="px-5 py-4 text-start">{f.text('التاريخ', 'Posting date')}</th><th className="px-5 py-4 text-start">{f.text('البيان', 'Description')}</th><th className="px-5 py-4 text-start">{f.text('النوع', 'Type')}</th><th className="px-5 py-4 text-end">{f.text('مدين', 'Debit')}</th><th className="px-5 py-4 text-start">{f.text('الحالة', 'Status')}</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(row => <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-mono text-xs font-bold text-mis-primary">{row.journalNumber ?? 'DRAFT'}</td><td className="px-5 py-4 text-slate-600">{f.date(row.postingDate)}</td><td className="max-w-sm truncate px-5 py-4 font-semibold text-mis-navy">{row.description}</td><td className="px-5 py-4 text-slate-500">{row.entryType}</td><td className="px-5 py-4 text-end font-semibold" data-bidi="ltr">{f.money(row.totalDebit)}</td><td className="px-5 py-4"><FinanceStatus value={row.status} /></td><td className="px-5 py-4 text-end"><Link to={`/finance/journals/${row.id}`} className="inline-flex rounded-lg p-2 text-mis-primary hover:bg-mis-pale"><Eye className="h-4 w-4" /></Link></td></tr>)}</tbody></table></div><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={next => setParams({ ...(status ? { status } : {}), page: String(next) })} /></div>
    {open && <ManualJournalDialog accounts={accounts} close={() => setOpen(false)} created={() => { setOpen(false); load(); }} />}
  </div>;
}

function ManualJournalDialog({ accounts, close, created }: { accounts: FinanceAccount[]; close: () => void; created: () => void }) {
  const f = useFinanceText(); const [form, setForm] = useState<CreateManualJournalInput>({ transactionDate: today(), postingDate: today(), currencyCode: 'EGP', description: '', lines: [emptyLine(), emptyLine()] }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const debit = useMemo(() => form.lines.reduce((s,x) => s + Number(x.debit || 0), 0), [form.lines]); const credit = useMemo(() => form.lines.reduce((s,x) => s + Number(x.credit || 0), 0), [form.lines]);
  const updateLine = (index: number, patch: Partial<ManualJournalLineInput>) => setForm(current => ({ ...current, lines: current.lines.map((line, i) => i === index ? { ...line, ...patch } : line) })); const submit = async (e: FormEvent) => { e.preventDefault(); if (debit !== credit || debit <= 0) { setError(f.text('يجب أن يكون القيد متوازنًا وبقيمة موجبة.', 'Journal must be balanced with a positive amount.')); return; } setBusy(true); try { await financeService.createJournal(form); created(); } catch (err) { setError(getApiErrorMessage(err, f.text('تعذر إنشاء القيد', 'Could not create journal'))); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-mis-ink/55 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-6xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-center border-b border-mis-border bg-white px-6 py-5"><div><h2 className="text-xl font-bold text-mis-navy">{f.text('قيد يدوي جديد', 'New manual journal')}</h2><p className="mt-1 text-xs text-slate-500">{f.text('سيُحفظ كمسودة ثم يمر بالاعتماد والترحيل.', 'Saved as draft, then submitted, approved, and posted.')}</p></div><button type="button" onClick={close} className="ms-auto rounded-lg p-2 text-slate-500"><X /></button></header><div className="grid gap-4 p-6 sm:grid-cols-4"><label className="sm:col-span-2"><span className="mb-2 block text-sm font-semibold">{f.text('البيان', 'Description')}</span><input required maxLength={1000} className="field" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label><span className="mb-2 block text-sm font-semibold">{f.text('تاريخ العملية', 'Transaction date')}</span><DateControl required  className="field" value={form.transactionDate} onChange={e => setForm({ ...form, transactionDate: e.target.value })} /></label><label><span className="mb-2 block text-sm font-semibold">{f.text('تاريخ الترحيل', 'Posting date')}</span><DateControl required  className="field" value={form.postingDate} onChange={e => setForm({ ...form, postingDate: e.target.value })} /></label></div>
      <div className="overflow-x-auto border-y border-mis-border"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3 text-start">#</th><th className="px-4 py-3 text-start">{f.text('الحساب', 'Account')}</th><th className="px-4 py-3 text-start">{f.text('البيان', 'Description')}</th><th className="px-4 py-3 text-end">{f.text('مدين', 'Debit')}</th><th className="px-4 py-3 text-end">{f.text('دائن', 'Credit')}</th><th /></tr></thead><tbody className="divide-y divide-mis-border">{form.lines.map((line, index) => <tr key={index}><td className="px-4 py-3 text-slate-400">{index + 1}</td><td className="px-4 py-3"><ProfessionalSelect required className="field min-w-64" value={line.accountId} onChange={e => updateLine(index, { accountId: e.target.value })}><option value="">—</option>{accounts.map(x => <option key={x.id} value={x.id}>{x.code} · {f.ar ? x.nameArabic : x.nameEnglish}</option>)}</ProfessionalSelect></td><td className="px-4 py-3"><input required className="field min-w-52" value={line.description} onChange={e => updateLine(index, { description: e.target.value })} /></td><td className="px-4 py-3"><input min="0" step="0.01" type="number" className="field text-end" value={line.debit || ''} onChange={e => updateLine(index, { debit: Number(e.target.value), credit: Number(e.target.value) > 0 ? 0 : line.credit })} /></td><td className="px-4 py-3"><input min="0" step="0.01" type="number" className="field text-end" value={line.credit || ''} onChange={e => updateLine(index, { credit: Number(e.target.value), debit: Number(e.target.value) > 0 ? 0 : line.debit })} /></td><td className="px-4 py-3"><button type="button" disabled={form.lines.length <= 2} onClick={() => setForm({ ...form, lines: form.lines.filter((_,i) => i !== index) })} className="rounded-lg p-2 text-rose-600 disabled:opacity-30"><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table></div>
      <div className="flex flex-col gap-4 p-6 sm:flex-row sm:items-center"><button type="button" onClick={() => setForm({ ...form, lines: [...form.lines, emptyLine()] })} className="inline-flex items-center gap-2 rounded-xl border border-mis-border px-4 py-2.5 text-sm font-bold text-mis-primary"><Plus className="h-4 w-4" />{f.text('إضافة سطر', 'Add line')}</button>{error && <p className="text-sm text-rose-700">{error}</p>}<div className="ms-auto flex items-center gap-5 rounded-xl bg-slate-50 px-5 py-3 text-sm"><span>{f.text('مدين', 'Debit')}: <b data-bidi="ltr">{f.money(debit)}</b></span><span>{f.text('دائن', 'Credit')}: <b data-bidi="ltr">{f.money(credit)}</b></span><span className={`font-bold ${debit === credit && debit > 0 ? 'text-emerald-700' : 'text-rose-700'}`}>{debit === credit && debit > 0 ? f.text('متوازن', 'Balanced') : f.text('غير متوازن', 'Out of balance')}</span></div><button disabled={busy} className="rounded-xl bg-mis-primary px-6 py-3 text-sm font-bold text-white disabled:opacity-50">{f.text('حفظ المسودة', 'Save draft')}</button></div></form></div>;
}
