import { ArrowLeft, CheckCircle2, Send, ShieldCheck, Undo2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { FinanceStatus, useFinanceText } from '../../features/finance/financeUi';
import { financeService } from '../../features/finance/services/financeService';
import type { Journal } from '../../features/finance/types/finance';
import { getApiErrorMessage } from '../../services/apiClient';

export function FinanceJournalDetailsPage() {
  const { id = '' } = useParams(); const f = useFinanceText(); const [data, setData] = useState<Journal>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const load = () => { financeService.journal(id).then(setData).catch(e => setError(getApiErrorMessage(e, 'Could not load journal'))); }; useEffect(load, [id]);
  const act = async (action: 'submit'|'approve'|'post') => { setBusy(true); setError(''); try { setData(await financeService.journalAction(id, action)); } catch (e) { setError(getApiErrorMessage(e, 'Action failed')); } finally { setBusy(false); } }; const reverse = async () => { const reason = prompt(f.text('سبب العكس', 'Reversal reason')); if (!reason) return; setBusy(true); try { setData(await financeService.reverseJournal(id, reason)); } catch (e) { setError(getApiErrorMessage(e, 'Reversal failed')); } finally { setBusy(false); } };
  if (error && !data) return <ErrorState title={error} onRetry={load} />; if (!data) return <div className="grid min-h-[420px] place-items-center"><LoadingSpinner /></div>;
  return <div><Link to="/finance/journals" className="inline-flex items-center gap-2 text-sm font-bold text-mis-primary"><ArrowLeft className="h-4 w-4 rtl:rotate-180" />{f.text('العودة للقيود', 'Back to journals')}</Link><header className="mt-5 flex flex-col justify-between gap-4 rounded-2xl border border-mis-border bg-white p-6 shadow-sm lg:flex-row lg:items-start"><div><div className="flex items-center gap-3"><h1 className="font-mono text-2xl font-bold text-mis-navy">{data.journalNumber ?? 'DRAFT JOURNAL'}</h1><FinanceStatus value={data.status} /></div><p className="mt-3 text-slate-600">{data.description}</p><p className="mt-2 text-xs text-slate-400">{data.entryType} · {f.date(data.postingDate)} · {data.currencyCode}</p></div><div className="flex flex-wrap gap-2">{data.status === 'DRAFT' && <button disabled={busy} onClick={() => act('submit')} className="inline-flex items-center gap-2 rounded-xl bg-mis-primary px-4 py-2.5 text-sm font-bold text-white"><Send className="h-4 w-4" />Submit</button>}{data.status === 'PENDING_APPROVAL' && <button disabled={busy} onClick={() => act('approve')} className="inline-flex items-center gap-2 rounded-xl bg-amber-600 px-4 py-2.5 text-sm font-bold text-white"><CheckCircle2 className="h-4 w-4" />Approve</button>}{data.status === 'APPROVED' && <button disabled={busy} onClick={() => act('post')} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white"><ShieldCheck className="h-4 w-4" />Post</button>}{data.status === 'POSTED' && <button disabled={busy} onClick={reverse} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 px-4 py-2.5 text-sm font-bold text-rose-700"><Undo2 className="h-4 w-4" />Reverse</button>}</div></header>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="mt-6 overflow-hidden rounded-2xl border border-mis-border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4 text-start">#</th><th className="px-5 py-4 text-start">{f.text('الحساب', 'Account')}</th><th className="px-5 py-4 text-start">{f.text('البيان', 'Description')}</th><th className="px-5 py-4 text-end">{f.text('مدين', 'Debit')}</th><th className="px-5 py-4 text-end">{f.text('دائن', 'Credit')}</th></tr></thead><tbody className="divide-y divide-mis-border">{data.lines.map(line => <tr key={line.id}><td className="px-5 py-4 text-slate-400">{line.lineNumber}</td><td className="px-5 py-4"><p className="font-mono font-bold text-mis-primary">{line.accountCode}</p><p className="mt-1 text-xs text-slate-500">{f.ar ? line.accountNameArabic : line.accountNameEnglish}</p></td><td className="px-5 py-4 text-slate-600">{line.description}</td><td className="px-5 py-4 text-end font-semibold" data-bidi="ltr">{line.debit ? f.money(line.debit) : '—'}</td><td className="px-5 py-4 text-end font-semibold" data-bidi="ltr">{line.credit ? f.money(line.credit) : '—'}</td></tr>)}</tbody><tfoot className="bg-slate-50 font-bold text-mis-navy"><tr><td colSpan={3} className="px-5 py-4 text-end">{f.text('الإجمالي', 'Total')}</td><td className="px-5 py-4 text-end" data-bidi="ltr">{f.money(data.totalDebit)}</td><td className="px-5 py-4 text-end" data-bidi="ltr">{f.money(data.totalCredit)}</td></tr></tfoot></table></div></div>
    <section className="mt-6 grid gap-4 md:grid-cols-3">{[[f.text('أنشئ بواسطة','Created by'),data.createdBy,data.createdAt],[f.text('اعتمد بواسطة','Approved by'),data.approvedBy ?? '—',data.approvedAt],[f.text('رُحّل بواسطة','Posted by'),data.postedBy ?? '—',data.postedAt]].map(([label,user,at]) => <div key={label} className="rounded-2xl border border-mis-border bg-white p-5"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-2 font-semibold text-mis-navy">{user}</p><p className="mt-1 text-xs text-slate-400">{at ? new Date(at).toLocaleString(f.ar ? 'ar-EG' : 'en-GB') : '—'}</p></div>)}</section>
  </div>;
}
