import { CalendarPlus, LockKeyhole, RotateCcw } from 'lucide-react';
import { useEffect, useState } from 'react';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { FinanceStatus, useFinanceText } from '../../features/finance/financeUi';
import { financeService } from '../../features/finance/services/financeService';
import type { AccountingPeriod } from '../../features/finance/types/finance';
import { getApiErrorMessage } from '../../services/apiClient';

export function FinancePeriodsPage() {
  const f = useFinanceText(); const currentYear = new Date().getFullYear(); const [year, setYear] = useState(currentYear); const [rows, setRows] = useState<AccountingPeriod[]>(); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = () => { setError(''); financeService.periods(year).then(setRows).catch(e => setError(getApiErrorMessage(e, f.text('تعذر تحميل الفترات', 'Could not load periods')))); }; useEffect(load, [year]);
  const initialize = async () => { setBusy('init'); try { setRows(await financeService.initializeYear(year)); } catch (e) { setError(getApiErrorMessage(e, 'Could not initialize year')); } finally { setBusy(''); } };
  const act = async (row: AccountingPeriod, action: 'soft-close'|'close'|'reopen') => { const reason = window.prompt(f.text('اكتب سبب الإجراء ليُحفظ في سجل التدقيق', 'Enter the reason for the audit trail')); if (!reason) return; setBusy(row.id); try { await financeService.periodAction(row.id, action, reason); load(); } catch (e) { setError(getApiErrorMessage(e, 'Period action failed')); } finally { setBusy(''); } };
  if (error && !rows) return <ErrorState title={error} onRetry={load} />; if (!rows) return <div className="grid min-h-[420px] place-items-center"><LoadingSpinner /></div>;
  return <div><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-mis-primary">PERIOD CONTROL</p><h1 className="mt-2 text-3xl font-bold text-mis-navy">{f.text('الفترات والإقفال', 'Fiscal Periods & Closing')}</h1><p className="mt-2 text-sm text-slate-500">{f.text('الإقفال يمنع الترحيل من الخادم ولا يعتمد على الواجهة.', 'Period locks are enforced by the posting service, not only by the UI.')}</p></div><div className="flex gap-2"><input className="field w-28" type="number" min="2000" max="2200" value={year} onChange={e => setYear(Number(e.target.value))} /><button className="inline-flex items-center gap-2 rounded-xl bg-mis-primary px-4 py-3 text-sm font-bold text-white disabled:opacity-50" disabled={busy === 'init'} onClick={initialize}><CalendarPlus className="h-4 w-4" />{f.text('تهيئة السنة', 'Initialize year')}</button></div></header>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <div className="mt-6 overflow-hidden rounded-2xl border border-mis-border bg-white shadow-sm"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4 text-start">{f.text('الفترة', 'Period')}</th><th className="px-5 py-4 text-start">{f.text('من', 'From')}</th><th className="px-5 py-4 text-start">{f.text('إلى', 'To')}</th><th className="px-5 py-4 text-start">{f.text('الحالة', 'Status')}</th><th className="px-5 py-4 text-end">{f.text('إجراء', 'Action')}</th></tr></thead><tbody className="divide-y divide-mis-border">{rows.map(row => <tr key={row.id}><td className="px-5 py-4 font-bold text-mis-navy">{row.name}</td><td className="px-5 py-4 text-slate-600">{f.date(row.startDate)}</td><td className="px-5 py-4 text-slate-600">{f.date(row.endDate)}</td><td className="px-5 py-4"><FinanceStatus value={row.status} /></td><td className="px-5 py-4 text-end">{row.status === 'OPEN' ? <button disabled={busy === row.id} onClick={() => act(row,'soft-close')} className="rounded-lg border border-amber-200 px-3 py-2 text-xs font-bold text-amber-700"><LockKeyhole className="me-1 inline h-3.5 w-3.5" />Soft close</button> : row.status === 'SOFT_CLOSED' ? <button disabled={busy === row.id} onClick={() => act(row,'close')} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700">Close</button> : <button disabled={busy === row.id} onClick={() => act(row,'reopen')} className="rounded-lg border border-mis-border px-3 py-2 text-xs font-bold text-mis-primary"><RotateCcw className="me-1 inline h-3.5 w-3.5" />Reopen</button>}</td></tr>)}</tbody></table>{!rows.length && <div className="p-10 text-center text-sm text-slate-500">{f.text('لا توجد فترات. اضغط تهيئة السنة.', 'No periods. Initialize the fiscal year to begin.')}</div>}</div>
  </div>;
}
