import { coreHrTranslations } from './coreHrTranslations';

export const translations = {
  en: {
    socialInsurance: 'Social Insurance',
    excusesMissions: 'Excuses & Field Duties',
    language: 'Language', english: 'English', arabic: 'Arabic', dashboard: 'Dashboard', employees: 'Employees', delegations: 'Delegations', absences: 'Employee Absences', companyAbsences: 'Company Absences', employeeDocuments: 'Employee Documents', master: 'Master', logout: 'Logout', humanResources: 'Human Resources', hrDepartment: 'HR Department', collectionFirm: 'MIS Collection Firm',
    welcomeBack: 'Welcome Back', signInSubtitle: 'Sign in to your MIS account', username: 'Code / Email / Username', usernamePlaceholder: 'USR-12345678 or name@company.com', password: 'Password', passwordPlaceholder: 'Enter your password', rememberMe: 'Remember me', forgotPassword: 'Forgot Password?', signIn: 'Sign In', signingIn: 'Signing In', internalSystem: 'Internal Management System', secureTagline: 'Secure. Organized. Efficient.', collectionSystem: 'Collection Management System', invalidCredentials: 'Invalid login identifier or password.', usernameRequired: 'Code, email, or username is required.', passwordRequired: 'Password is required.',
    hrDashboard: 'HR Dashboard', dashboardSubtitle: 'Overview of your workforce and HR operations', totalEmployees: 'Total Employees', activeEmployees: 'Active Employees', absentToday: 'Absent Today', documentsAttention: 'Documents Requiring Attention', allEmployeeRecords: 'All employee records', noEmployeeRecords: 'No employee records yet', totalEmployeePercent: '{value}% of total employees', recordedToday: 'Recorded today', notAvailableYet: 'Not available yet', documentRecordsContext: '{count} document records · attention rules not available', totalDocumentsContext: '{count} total documents', employeeOverview: 'Employee Overview', noEmployeeData: 'No employee data yet', employeeDataHelp: 'Employees by department will appear here once employee records are available.', quickActions: 'Quick Actions', viewEmployeeDocuments: 'View Employee Documents', attendanceOverview: 'Attendance Overview', attendanceUnavailable: 'Attendance data is not available yet', attendanceHelp: 'Attendance information will appear here once the HR attendance module is implemented.', recentActivity: 'Recent Activity', noRecentActivity: 'No recent activity', noActivitySource: 'There is currently no activity data source for this dashboard.', noDocumentsAttention: 'No documents require attention', documentsAttentionHelp: 'Document attention rules have not been defined. Existing document records remain available in Employee Documents.', viewDocuments: 'View documents', dashboardUnavailable: 'Dashboard unavailable', tryAgain: 'Try again', loadDashboardError: 'Unable to load the HR dashboard.',
    employeesSubtitle: 'Manage employee records and employment status', addEmployee: 'Add Employee', editEmployee: 'Edit Employee', employeeId: 'Employee ID', employeeName: 'Employee Name', department: 'Department', status: 'Status', action: 'Action', searchEmployee: 'Search employee...', allDepartments: 'All departments', allStatuses: 'All statuses', active: 'Active', inactive: 'Inactive', noEmployeesFound: 'No employees found', addFirstEmployee: 'Start by adding the first employee.', adjustFilters: 'Try adjusting your search or filters.', selectDepartment: 'Select department', cancel: 'Cancel', saveChanges: 'Save Changes', saving: 'Saving...', edit: 'Edit', showing: 'Showing {from}–{to} of {total}', pageOf: 'Page {page} of {total}', employeeRequired: 'Employee ID, name, and department are required.', loadEmployeesError: 'Unable to load employees.', loadDepartmentsError: 'Unable to load departments.', saveEmployeeError: 'Unable to save employee.', loadEmployeeError: 'Unable to load employee.',
    absencesTitle: 'Employee Absences', absencesSubtitle: 'Track employee absences across the company', recordAbsence: 'Register Absence', importAbsenceFile: 'Import Absence File', date: 'Date', all: 'All', pending: 'Pending', excused: 'Excused', unexcused: 'Unexcused', actions: 'Actions', noAbsencesFound: 'No absences found', addFirstAbsence: 'Start by recording an employee absence.', editAbsence: 'Edit Absence', searchEmployeeLabel: 'Search employee', employeeIdOrName: 'Employee ID or name', employee: 'Employee', selectEmployee: 'Select employee', type: 'Type', absent: 'Absent', reason: 'Reason', notes: 'Notes', attendanceSource: 'Attendance Source', manual: 'Manual', absenceDetails: 'Absence Details', unknown: 'Unknown', view: 'View', delete: 'Delete', deleteAbsence: 'Delete Absence', deleteConfirmation: 'Are you sure you want to delete the absence record for {name} on {date}?', deleting: 'Deleting...', employeeDateRequired: 'Employee and date are required.', loadAbsencesError: 'Unable to load absences.', saveAbsenceError: 'Unable to save absence.', loadAbsenceError: 'Unable to load absence.', deleteAbsenceError: 'Unable to delete absence.',
    moduleComingSoon: 'Module coming soon', moduleComingHelp: 'This module is prepared and will be implemented in a later stage.', accessUnavailable: 'Access not available', accessHelp: 'Your account is not authorized for the requested department.', signOut: 'Sign out', idShort: 'ID', name: 'Name', previousPage: 'Previous page', nextPage: 'Next page',
    close: 'Close', yes: 'Yes', no: 'No', from: 'From', to: 'To', field: 'Field', code: 'Code', nameEnglish: 'English Name', nameArabic: 'Arabic Name', description: 'Description', address: 'Address', position: 'Position / Job Title', branch: 'Branch', employmentType: 'Employment Type', notAssigned: 'Not assigned', selectValue: 'Select a value', viewProfile: 'Profile', activate: 'Activate', deactivate: 'Deactivate',
    masterSubtitle: 'Manage the reference data used across Core HR', masterCategories: 'Master data categories', masterDepartments: 'Departments', masterPositions: 'Positions', masterBranches: 'Branches', masterEmploymentTypes: 'Employment Types', masterContractTypes: 'Contract Types', masterLeaveTypes: 'Leave Types', masterDocumentTypes: 'Document Types', masterDelegationTypes: 'Delegation Types', addMasterRecord: 'Add Record', editMasterRecord: 'Edit Record', masterRequiredFields: 'Code and English name are required.', masterEntitlementValidation: 'Annual entitlement must be between 0 and 366.', noDepartment: 'No department', defaultAnnualEntitlement: 'Default Annual Entitlement', requiresAttachment: 'Attachment required', requiresExpiryDate: 'Expiry date required', activeRecord: 'Active record', searchMasterData: 'Search code or name...', loadMasterDataError: 'Unable to load master data.', loadMasterRecordError: 'Unable to load the selected record.', saveMasterDataError: 'Unable to save master data.', masterCreatedSuccess: 'Master-data record created.', masterUpdatedSuccess: 'Master-data record updated.', masterActivatedSuccess: 'Record activated.', masterDeactivatedSuccess: 'Record deactivated.', changeMasterStatusError: 'Unable to change the record status.', masterDataUnavailable: 'Master data unavailable', noMasterDataFound: 'No records found', addFirstMasterRecord: 'Start by adding the first record in this category.', activateRecord: 'Activate Record', deactivateRecord: 'Deactivate Record', activateMasterConfirm: 'Activate {name}? The record will become available for future transactions.', deactivateMasterConfirm: 'Deactivate {name}? Existing historical data will remain unchanged.',
    employeeProfile: 'Employee Profile', employeeProfileTabs: 'Employee profile sections', backToEmployees: 'Back to Employees', profileOverview: 'Overview', profilePersonal: 'Personal & Contact', profileEmployment: 'Employment', profileContract: 'Contract', profileCompensation: 'Compensation', profileEmergency: 'Emergency Contact', profileAudit: 'Audit History', employeeProfileUnavailable: 'Employee profile unavailable', loadEmployeeProfileError: 'Unable to load the employee profile.', employeeSummary: 'Employee Summary', attendanceRecords: 'Attendance Records', leaveRequests: 'Leave Requests', reportingLine: 'Reporting Line', directManager: 'Direct Manager', directReports: 'Direct Reports', noDirectReports: 'This employee has no direct reports.',
    employeeStatus: 'Employee Status', employeeStatusActive: 'Active', employeeStatusInactive: 'Inactive', employeeStatusOnLeave: 'On Leave', employeeStatusSuspended: 'Suspended', employeeStatusTerminated: 'Terminated', changeEmployeeStatus: 'Change Status', confirmStatusChange: 'Confirm Status Change', statusReasonHelp: 'Optionally record the reason for this status change.', terminationDate: 'Termination Date', terminationReasonRequired: 'Termination date and reason are required.', terminationWarning: 'The effective termination date and reason will be retained in the employee history.', statusChangedSuccess: 'Employee status updated.', changeEmployeeStatusError: 'Unable to change employee status.',
    personalInformation: 'Personal Information', fullNameArabic: 'Full Name Arabic', fullNameEnglish: 'Full Name English', nationalId: 'National ID', dateOfBirth: 'Date of Birth', gender: 'Gender', maritalStatus: 'Marital Status', male: 'Male', female: 'Female', other: 'Other', single: 'Single', married: 'Married', divorced: 'Divorced', widowed: 'Widowed', nationalIdValidation: 'Egyptian national ID must contain exactly 14 digits.', personalSavedSuccess: 'Personal information saved.', savePersonalError: 'Unable to save personal information.',
    contactInformation: 'Contact Information', mobileNumber: 'Mobile Number', alternativeMobile: 'Alternative Mobile', email: 'Email', city: 'City', contactSavedSuccess: 'Contact information saved.', saveContactError: 'Unable to save contact information.',
    employmentInformation: 'Employment Information', employmentInformationHelp: 'Department, position, branch, employment type, manager, and hire date', hireDate: 'Hire Date', searchManager: 'Search for a manager', departmentRequired: 'Department is required.', employmentSavedSuccess: 'Employment information saved.', saveEmploymentError: 'Unable to save employment information.',
    contractInformation: 'Contract Information', contractInformationHelp: 'Current contract and probation dates', contractType: 'Contract Type', selectContractType: 'Select contract type', contractStatus: 'Contract Status', contractStartDate: 'Contract Start Date', contractEndDate: 'Contract End Date', probationStartDate: 'Probation Start Date', probationEndDate: 'Probation End Date', contractStatusDraft: 'Draft', contractStatusActive: 'Active', contractStatusExpired: 'Expired', contractStatusTerminated: 'Terminated', contractRequiredFields: 'Contract type and start date are required.', contractDateValidation: 'Contract end date cannot be before its start date.', probationDateValidation: 'Probation end date cannot be before its start date.', contractSavedSuccess: 'Contract information saved.', saveContractError: 'Unable to save contract information.',
    restrictedInformation: 'Restricted Information', compensationWarning: 'Salary and banking details are sensitive. Only authorized HR managers can access this section.', salaryInformation: 'Salary Information', basicSalary: 'Basic Salary', allowances: 'Allowances', totalSalary: 'Total Salary', effectiveFrom: 'Effective From', bankName: 'Bank Name', bankAccount: 'Bank Account', iban: 'IBAN', salaryValidation: 'Salary and allowances cannot be negative, and the effective date is required.', compensationSavedSuccess: 'Compensation information saved.', saveCompensationError: 'Unable to save compensation information.',
    emergencyContact: 'Emergency Contact', emergencyContactHelp: 'Primary contact to use in an emergency', contactName: 'Contact Name', relationship: 'Relationship', alternativeNumber: 'Alternative Number', emergencyRequiredFields: 'Contact name, relationship, and mobile number are required.', emergencySavedSuccess: 'Emergency contact saved.', saveEmergencyError: 'Unable to save emergency contact.',
    auditHistory: 'Audit History', auditHistoryHelp: 'Important changes recorded for this employee', searchAudit: 'Search employee history...', loadAuditError: 'Unable to load audit history.', auditUnavailable: 'Audit history unavailable', noAuditRecords: 'No audit records', noAuditHelp: 'Recorded changes for this employee will appear here.', changedBy: 'Changed by {user}', auditEmployeeCreated: 'Employee Created', auditEmployeeUpdated: 'Employee Updated', auditPersonalUpdated: 'Personal Information Updated', auditContactUpdated: 'Contact Information Updated', auditEmploymentUpdated: 'Employment Information Updated', auditContractUpdated: 'Contract Information Updated', auditCompensationUpdated: 'Compensation Information Updated', auditEmergencyUpdated: 'Emergency Contact Updated', auditStatusChanged: 'Employee Status Changed',
    ...coreHrTranslations.en,
  },
  ar: {
    socialInsurance: 'التأمينات الاجتماعية',
    excusesMissions: 'الأعذار والمأموريات',
    language: 'اللغة', english: 'الإنجليزية', arabic: 'العربية', dashboard: 'لوحة التحكم', employees: 'الموظفون', delegations: 'تفويضات', absences: 'غيابات الموظفين', companyAbsences: 'غيابات الشركة', employeeDocuments: 'أوراق الموظفين', master: 'البيانات الأساسية', logout: 'تسجيل الخروج', humanResources: 'الموارد البشرية', hrDepartment: 'قسم الموارد البشرية', collectionFirm: 'شركة MIS للتحصيل',
    welcomeBack: 'مرحباً بعودتك', signInSubtitle: 'سجّل الدخول إلى حساب MIS', username: 'الكود / البريد / اسم المستخدم', usernamePlaceholder: 'USR-12345678 أو البريد الإلكتروني', password: 'كلمة المرور', passwordPlaceholder: 'أدخل كلمة المرور', rememberMe: 'تذكرني', forgotPassword: 'نسيت كلمة المرور؟', signIn: 'تسجيل الدخول', signingIn: 'جارٍ تسجيل الدخول', internalSystem: 'نظام الإدارة الداخلي', secureTagline: 'آمن. منظم. فعّال.', collectionSystem: 'نظام إدارة التحصيل', invalidCredentials: 'بيانات الدخول أو كلمة المرور غير صحيحة.', usernameRequired: 'الكود أو البريد أو اسم المستخدم مطلوب.', passwordRequired: 'كلمة المرور مطلوبة.',
    hrDashboard: 'لوحة تحكم الموارد البشرية', dashboardSubtitle: 'نظرة عامة على القوى العاملة وعمليات الموارد البشرية', totalEmployees: 'إجمالي الموظفين', activeEmployees: 'الموظفون النشطون', absentToday: 'الغائبون اليوم', documentsAttention: 'مستندات تحتاج إلى متابعة', allEmployeeRecords: 'جميع سجلات الموظفين', noEmployeeRecords: 'لا توجد سجلات موظفين بعد', totalEmployeePercent: '{value}% من إجمالي الموظفين', recordedToday: 'المسجل اليوم', notAvailableYet: 'غير متاح بعد', documentRecordsContext: '{count} سجل مستند · قواعد المتابعة غير متاحة', totalDocumentsContext: '{count} إجمالي المستندات', employeeOverview: 'نظرة عامة على الموظفين', noEmployeeData: 'لا توجد بيانات موظفين بعد', employeeDataHelp: 'سيظهر توزيع الموظفين حسب القسم عند توفر سجلات الموظفين.', quickActions: 'إجراءات سريعة', viewEmployeeDocuments: 'عرض أوراق الموظفين', attendanceOverview: 'نظرة عامة على الحضور', attendanceUnavailable: 'بيانات الحضور غير متاحة بعد', attendanceHelp: 'ستظهر بيانات الحضور بعد تنفيذ وحدة حضور الموارد البشرية.', recentActivity: 'النشاط الأخير', noRecentActivity: 'لا يوجد نشاط حديث', noActivitySource: 'لا يوجد حالياً مصدر لبيانات النشاط.', noDocumentsAttention: 'لا توجد مستندات تحتاج إلى متابعة', documentsAttentionHelp: 'لم يتم تحديد قواعد متابعة المستندات بعد. السجلات الحالية متاحة في أوراق الموظفين.', viewDocuments: 'عرض المستندات', dashboardUnavailable: 'لوحة التحكم غير متاحة', tryAgain: 'إعادة المحاولة', loadDashboardError: 'تعذر تحميل لوحة تحكم الموارد البشرية.',
    employeesSubtitle: 'إدارة سجلات الموظفين وحالة العمل', addEmployee: 'إضافة موظف', editEmployee: 'تعديل موظف', employeeId: 'رقم الموظف', employeeName: 'اسم الموظف', department: 'القسم', status: 'الحالة', action: 'الإجراء', searchEmployee: 'ابحث عن موظف...', allDepartments: 'كل الأقسام', allStatuses: 'كل الحالات', active: 'نشط', inactive: 'غير نشط', noEmployeesFound: 'لم يتم العثور على موظفين', addFirstEmployee: 'ابدأ بإضافة أول موظف.', adjustFilters: 'حاول تعديل البحث أو عوامل التصفية.', selectDepartment: 'اختر القسم', cancel: 'إلغاء', saveChanges: 'حفظ التغييرات', saving: 'جارٍ الحفظ...', edit: 'تعديل', showing: 'عرض {from}–{to} من {total}', pageOf: 'صفحة {page} من {total}', employeeRequired: 'رقم الموظف والاسم والقسم مطلوبة.', loadEmployeesError: 'تعذر تحميل الموظفين.', loadDepartmentsError: 'تعذر تحميل الأقسام.', saveEmployeeError: 'تعذر حفظ الموظف.', loadEmployeeError: 'تعذر تحميل الموظف.',
    absencesTitle: 'غيابات الموظفين', absencesSubtitle: 'متابعة غياب الموظفين داخل الشركة', recordAbsence: 'تسجيل غياب', importAbsenceFile: 'استيراد ملف الغياب', date: 'التاريخ', all: 'الكل', pending: 'قيد المراجعة', excused: 'بعذر', unexcused: 'بدون عذر', actions: 'الإجراءات', noAbsencesFound: 'لا توجد حالات غياب', addFirstAbsence: 'ابدأ بتسجيل غياب موظف.', editAbsence: 'تعديل الغياب', searchEmployeeLabel: 'بحث عن موظف', employeeIdOrName: 'رقم الموظف أو الاسم', employee: 'الموظف', selectEmployee: 'اختر الموظف', type: 'النوع', absent: 'غائب', reason: 'السبب', notes: 'ملاحظات', attendanceSource: 'مصدر الحضور', manual: 'يدوي', absenceDetails: 'تفاصيل الغياب', unknown: 'غير معروف', view: 'عرض', delete: 'حذف', deleteAbsence: 'حذف الغياب', deleteConfirmation: 'هل أنت متأكد من حذف غياب {name} بتاريخ {date}؟', deleting: 'جارٍ الحذف...', employeeDateRequired: 'الموظف والتاريخ مطلوبان.', loadAbsencesError: 'تعذر تحميل الغيابات.', saveAbsenceError: 'تعذر حفظ الغياب.', loadAbsenceError: 'تعذر تحميل الغياب.', deleteAbsenceError: 'تعذر حذف الغياب.',
    moduleComingSoon: 'الوحدة قيد الإعداد', moduleComingHelp: 'تم تجهيز هذه الوحدة وسيتم تنفيذها في مرحلة لاحقة.', accessUnavailable: 'الوصول غير متاح', accessHelp: 'حسابك غير مصرح له بالوصول إلى القسم المطلوب.', signOut: 'تسجيل الخروج', idShort: 'الرقم', name: 'الاسم', previousPage: 'الصفحة السابقة', nextPage: 'الصفحة التالية',
    close: 'إغلاق', yes: 'نعم', no: 'لا', from: 'من', to: 'إلى', field: 'الحقل', code: 'الكود', nameEnglish: 'الاسم بالإنجليزية', nameArabic: 'الاسم بالعربية', description: 'الوصف', address: 'العنوان', position: 'المسمى الوظيفي', branch: 'الفرع', employmentType: 'نوع التوظيف', notAssigned: 'غير معيّن', selectValue: 'اختر قيمة', viewProfile: 'الملف الشخصي', activate: 'تفعيل', deactivate: 'إلغاء التفعيل',
    masterSubtitle: 'إدارة البيانات المرجعية المستخدمة في نظام الموارد البشرية', masterCategories: 'تصنيفات البيانات الأساسية', masterDepartments: 'الأقسام', masterPositions: 'المسميات الوظيفية', masterBranches: 'الفروع', masterEmploymentTypes: 'أنواع التوظيف', masterContractTypes: 'أنواع العقود', masterLeaveTypes: 'أنواع الإجازات', masterDocumentTypes: 'أنواع المستندات', masterDelegationTypes: 'أنواع التفويضات', addMasterRecord: 'إضافة سجل', editMasterRecord: 'تعديل السجل', masterRequiredFields: 'الكود والاسم بالإنجليزية مطلوبان.', masterEntitlementValidation: 'يجب أن يكون الرصيد السنوي بين 0 و366.', noDepartment: 'بدون قسم', defaultAnnualEntitlement: 'الرصيد السنوي الافتراضي', requiresAttachment: 'يتطلب مرفقًا', requiresExpiryDate: 'يتطلب تاريخ انتهاء', activeRecord: 'سجل نشط', searchMasterData: 'ابحث بالكود أو الاسم...', loadMasterDataError: 'تعذر تحميل البيانات الأساسية.', loadMasterRecordError: 'تعذر تحميل السجل المحدد.', saveMasterDataError: 'تعذر حفظ البيانات الأساسية.', masterCreatedSuccess: 'تم إنشاء سجل البيانات الأساسية.', masterUpdatedSuccess: 'تم تحديث سجل البيانات الأساسية.', masterActivatedSuccess: 'تم تفعيل السجل.', masterDeactivatedSuccess: 'تم إلغاء تفعيل السجل.', changeMasterStatusError: 'تعذر تغيير حالة السجل.', masterDataUnavailable: 'البيانات الأساسية غير متاحة', noMasterDataFound: 'لا توجد سجلات', addFirstMasterRecord: 'ابدأ بإضافة أول سجل في هذا التصنيف.', activateRecord: 'تفعيل السجل', deactivateRecord: 'إلغاء تفعيل السجل', activateMasterConfirm: 'هل تريد تفعيل {name}؟ سيصبح السجل متاحًا للمعاملات الجديدة.', deactivateMasterConfirm: 'هل تريد إلغاء تفعيل {name}؟ ستظل البيانات التاريخية محفوظة.',
    employeeProfile: 'ملف الموظف', employeeProfileTabs: 'أقسام ملف الموظف', backToEmployees: 'العودة إلى الموظفين', profileOverview: 'نظرة عامة', profilePersonal: 'البيانات الشخصية والتواصل', profileEmployment: 'العمل', profileContract: 'العقد', profileCompensation: 'الراتب', profileEmergency: 'جهة اتصال الطوارئ', profileAudit: 'سجل التعديلات', employeeProfileUnavailable: 'ملف الموظف غير متاح', loadEmployeeProfileError: 'تعذر تحميل ملف الموظف.', employeeSummary: 'ملخص الموظف', attendanceRecords: 'سجلات الحضور', leaveRequests: 'طلبات الإجازة', reportingLine: 'التسلسل الإداري', directManager: 'المدير المباشر', directReports: 'المرؤوسون المباشرون', noDirectReports: 'لا يوجد موظفون يتبعون لهذا الموظف مباشرة.',
    employeeStatus: 'حالة الموظف', employeeStatusActive: 'نشط', employeeStatusInactive: 'غير نشط', employeeStatusOnLeave: 'في إجازة', employeeStatusSuspended: 'موقوف', employeeStatusTerminated: 'منتهي الخدمة', changeEmployeeStatus: 'تغيير الحالة', confirmStatusChange: 'تأكيد تغيير الحالة', statusReasonHelp: 'يمكن تسجيل سبب تغيير الحالة اختياريًا.', terminationDate: 'تاريخ انتهاء الخدمة', terminationReasonRequired: 'تاريخ وسبب انتهاء الخدمة مطلوبان.', terminationWarning: 'سيتم الاحتفاظ بتاريخ وسبب انتهاء الخدمة في السجل التاريخي للموظف.', statusChangedSuccess: 'تم تحديث حالة الموظف.', changeEmployeeStatusError: 'تعذر تغيير حالة الموظف.',
    personalInformation: 'البيانات الشخصية', fullNameArabic: 'الاسم الكامل بالعربية', fullNameEnglish: 'الاسم الكامل بالإنجليزية', nationalId: 'الرقم القومي', dateOfBirth: 'تاريخ الميلاد', gender: 'النوع', maritalStatus: 'الحالة الاجتماعية', male: 'ذكر', female: 'أنثى', other: 'أخرى', single: 'أعزب', married: 'متزوج', divorced: 'مطلق', widowed: 'أرمل', nationalIdValidation: 'يجب أن يتكون الرقم القومي المصري من 14 رقمًا بالضبط.', personalSavedSuccess: 'تم حفظ البيانات الشخصية.', savePersonalError: 'تعذر حفظ البيانات الشخصية.',
    contactInformation: 'بيانات التواصل', mobileNumber: 'رقم الموبايل', alternativeMobile: 'رقم هاتف بديل', email: 'البريد الإلكتروني', city: 'المدينة', contactSavedSuccess: 'تم حفظ بيانات التواصل.', saveContactError: 'تعذر حفظ بيانات التواصل.',
    employmentInformation: 'بيانات العمل', employmentInformationHelp: 'القسم والمسمى والفرع ونوع التوظيف والمدير وتاريخ التعيين', hireDate: 'تاريخ التعيين', searchManager: 'ابحث عن مدير', departmentRequired: 'القسم مطلوب.', employmentSavedSuccess: 'تم حفظ بيانات العمل.', saveEmploymentError: 'تعذر حفظ بيانات العمل.',
    contractInformation: 'بيانات العقد', contractInformationHelp: 'العقد الحالي وتواريخ فترة الاختبار', contractType: 'نوع العقد', selectContractType: 'اختر نوع العقد', contractStatus: 'حالة العقد', contractStartDate: 'تاريخ بداية العقد', contractEndDate: 'تاريخ نهاية العقد', probationStartDate: 'بداية فترة الاختبار', probationEndDate: 'نهاية فترة الاختبار', contractStatusDraft: 'مسودة', contractStatusActive: 'نشط', contractStatusExpired: 'منتهي', contractStatusTerminated: 'تم إنهاؤه', contractRequiredFields: 'نوع العقد وتاريخ البداية مطلوبان.', contractDateValidation: 'لا يمكن أن يسبق تاريخ نهاية العقد تاريخ البداية.', probationDateValidation: 'لا يمكن أن تسبق نهاية فترة الاختبار بدايتها.', contractSavedSuccess: 'تم حفظ بيانات العقد.', saveContractError: 'تعذر حفظ بيانات العقد.',
    restrictedInformation: 'بيانات مقيدة', compensationWarning: 'بيانات الراتب والبنك حساسة ولا تظهر إلا لمدير الموارد البشرية المصرح له.', salaryInformation: 'بيانات الراتب', basicSalary: 'الراتب الأساسي', allowances: 'البدلات', totalSalary: 'إجمالي الراتب', effectiveFrom: 'ساري من', bankName: 'اسم البنك', bankAccount: 'الحساب البنكي', iban: 'رقم IBAN', salaryValidation: 'لا يمكن أن يكون الراتب أو البدلات بقيمة سالبة، وتاريخ السريان مطلوب.', compensationSavedSuccess: 'تم حفظ بيانات الراتب.', saveCompensationError: 'تعذر حفظ بيانات الراتب.',
    emergencyContact: 'جهة اتصال الطوارئ', emergencyContactHelp: 'جهة الاتصال الأساسية المستخدمة في حالات الطوارئ', contactName: 'اسم جهة الاتصال', relationship: 'صلة القرابة', alternativeNumber: 'رقم بديل', emergencyRequiredFields: 'اسم جهة الاتصال وصلة القرابة ورقم الهاتف مطلوبة.', emergencySavedSuccess: 'تم حفظ جهة اتصال الطوارئ.', saveEmergencyError: 'تعذر حفظ جهة اتصال الطوارئ.',
    auditHistory: 'سجل التعديلات', auditHistoryHelp: 'التغييرات المهمة المسجلة لهذا الموظف', searchAudit: 'ابحث في سجل الموظف...', loadAuditError: 'تعذر تحميل سجل التعديلات.', auditUnavailable: 'سجل التعديلات غير متاح', noAuditRecords: 'لا توجد تعديلات مسجلة', noAuditHelp: 'ستظهر هنا التغييرات المسجلة لهذا الموظف.', changedBy: 'تم التغيير بواسطة {user}', auditEmployeeCreated: 'تم إنشاء الموظف', auditEmployeeUpdated: 'تم تحديث الموظف', auditPersonalUpdated: 'تم تحديث البيانات الشخصية', auditContactUpdated: 'تم تحديث بيانات التواصل', auditEmploymentUpdated: 'تم تحديث بيانات العمل', auditContractUpdated: 'تم تحديث بيانات العقد', auditCompensationUpdated: 'تم تحديث بيانات الراتب', auditEmergencyUpdated: 'تم تحديث جهة اتصال الطوارئ', auditStatusChanged: 'تم تغيير حالة الموظف',
    ...coreHrTranslations.ar,
  }
} as const;

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;
