import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { DateControl } from '../../components/forms/DateControl';
import { Eye, Plus, RefreshCw, Search, SlidersHorizontal } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { Button } from '../../components/common/Button';
import { EmptyState } from '../../components/common/EmptyState';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { Pagination } from '../../components/common/Pagination';
import { StatusBadge } from '../../components/common/StatusBadge';
import { useToast } from '../../components/common/Toast';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { BankActivityCaseLookup, BankActivityDetails, BankActivityPage, BankActivitySummary, BankPortfolioCollector } from '../../features/collections/types/collections';
import { getApiErrorMessage } from '../../services/apiClient';
import type { BankWorkspaceContext } from './BankWorkspaceLayout';

export function BankCaseActivityCenterPage() {
  const { bank, organizationKind } = useOutletContext<BankWorkspaceContext>(); const workspaceBase = organizationKind === 'installment' ? '/installment-companies' : '/banks'; const { language, ct } = useCollectionsLocalization(); const toast = useToast();
  const [summary, setSummary] = useState<BankActivitySummary>(), [data, setData] = useState<BankActivityPage>(), [collectors, setCollectors] = useState<BankPortfolioCollector[]>([]);
  const [searchInput, setSearchInput] = useState(''), [search, setSearch] = useState(''), [type, setType] = useState(''), [outcome, setOutcome] = useState(''), [dateFilter, setDateFilter] = useState(''), [followUp, setFollowUp] = useState('ALL'), [collectorId, setCollectorId] = useState('');
  const [page, setPage] = useState(1), [pageSize, setPageSize] = useState(20), [reload, setReload] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [details, setDetails] = useState<BankActivityDetails>(), [detailsLoading, setDetailsLoading] = useState(false), [addOpen, setAddOpen] = useState(false), [saving, setSaving] = useState(false);
  useEffect(() => { const id=window.setTimeout(()=>{setSearch(searchInput.trim());setPage(1);},350); return()=>window.clearTimeout(id); },[searchInput]);
  useEffect(() => { let active=true; setLoading(true); setError(''); const query={page,pageSize,search,activityType:type,outcome,date:dateFilter,followUpState:followUp,collectorId}; void Promise.all([collectionsService.bankActivities(bank.id,query),collectionsService.bankActivitySummary(bank.id),collectionsService.bankActivityCollectors(bank.id)]).then(([d,s,c])=>{if(active){setData(d);setSummary(s);setCollectors(c);}}).catch(e=>{if(active)setError(getApiErrorMessage(e,ct('activityLoadError')));}).finally(()=>{if(active)setLoading(false);}); return()=>{active=false;}; },[bank.id,collectorId,ct,dateFilter,followUp,outcome,page,pageSize,reload,search,type]);
  const dateTime=(v?:string)=>v?new Intl.DateTimeFormat(language==='ar'?'ar-EG':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
  const money=(v:number)=>new Intl.NumberFormat(language==='ar'?'ar-EG':'en-EG',{style:'currency',currency:'EGP',maximumFractionDigits:0}).format(v);
  const clear=()=>{setSearchInput('');setSearch('');setType('');setOutcome('');setDateFilter('');setCollectorId('');setFollowUp('ALL');setPage(1);};
  async function openDetails(id:string){setDetailsLoading(true);try{setDetails(await collectionsService.bankActivity(bank.id,id));}catch(e){toast.error(getApiErrorMessage(e,ct('activityLoadError')));}finally{setDetailsLoading(false);}}
  const emptyTitle=search||type||outcome||dateFilter||collectorId?ct('noMatchingActivities'):followUp==='TODAY'?ct('noFollowUpsToday'):followUp==='OVERDUE'?ct('noOverdueFollowUps'):ct('noActivityFound');
  return <div>
    <header className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-2xl font-bold text-mis-navy">{ct('caseActivityCenter')}</h2><p className="mt-2 text-sm text-slate-500">{ct('caseActivityCenterDescription')}</p></div><div className="flex gap-2">{data?.access.canCreate&&<Button fullWidth={false} leftIcon={<Plus className="h-4 w-4"/>} onClick={()=>setAddOpen(true)} size="sm">{ct('addActivity')}</Button>}<Button fullWidth={false} leftIcon={<RefreshCw className="h-4 w-4"/>} onClick={()=>setReload(v=>v+1)} size="sm" variant="outline">{ct('refresh')}</Button></div></header>
    <section className="mb-4 grid grid-cols-2 divide-x divide-mis-border rounded-2xl border border-mis-border bg-white p-4 shadow-sm rtl:divide-x-reverse md:grid-cols-4">{[[ct('activitiesToday'),summary?.activitiesToday],[ct('followUpsToday'),summary?.followUpsToday],[ct('overdueFollowUps'),summary?.overdueFollowUps],[ct('casesContactedToday'),summary?.casesContactedToday]].map(([label,value])=><div className="px-4 py-2" key={String(label)}><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-mis-navy">{value??'—'}</p></div>)}</section>
    <div className="mb-4 flex gap-2 border-b border-mis-border">{[['ALL','allActivity'],['TODAY','followUpsToday'],['OVERDUE','overdue']].map(([value,label])=><button key={value} onClick={()=>{setFollowUp(value);setPage(1);}} className={`px-4 py-3 text-sm font-bold ${followUp===value?'border-b-2 border-mis-primary text-mis-primary':'text-slate-500'}`}>{ct(label)}</button>)}</div>
    <section className="mb-4 grid gap-3 rounded-2xl border border-mis-border bg-white p-4 sm:grid-cols-2 xl:grid-cols-[minmax(230px,1fr)_160px_180px_160px_170px_170px_auto]">
      <label className="relative"><Search className="absolute top-3.5 h-4 w-4 text-slate-400" style={{insetInlineStart:'.85rem'}}/><input className="field h-11 py-2 ps-10 leading-normal" placeholder={ct('searchActivities')} value={searchInput} onChange={e=>setSearchInput(e.target.value)}/></label>
      <ProfessionalSelect className="field h-11 py-2 leading-normal" value={type} onChange={e=>{setType(e.target.value);setPage(1);}}><option value="">{ct('allActivityTypes')}</option>{data?.access.filterActivityTypes.map(x=><option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect>
      <ProfessionalSelect className="field h-11 py-2 leading-normal" value={outcome} onChange={e=>{setOutcome(e.target.value);setPage(1);}}><option value="">{ct('allOutcomes')}</option>{data?.access.callOutcomes.map(x=><option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect>
      <DateControl aria-label={ct('activityDate')} className="field h-11 py-2 leading-normal"  value={dateFilter} onChange={e=>{setDateFilter(e.target.value);setPage(1);}}/>
      <ProfessionalSelect className="field h-11 py-2 leading-normal" value={followUp} onChange={e=>{setFollowUp(e.target.value);setPage(1);}}><option value="ALL">{ct('allFollowUps')}</option><option value="TODAY">{ct('dueToday')}</option><option value="UPCOMING">{ct('upcoming')}</option><option value="OVERDUE">{ct('overdue')}</option><option value="NONE">{ct('noFollowUp')}</option></ProfessionalSelect>
      {data?.access.isManager?<ProfessionalSelect className="field h-11 py-2 leading-normal" value={collectorId} onChange={e=>{setCollectorId(e.target.value);setPage(1);}}><option value="">{ct('allCollectors')}</option>{collectors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect>:<span/>}
      <Button fullWidth={false} leftIcon={<SlidersHorizontal className="h-4 w-4"/>} onClick={clear} size="sm" variant="ghost">{ct('clearFilters')}</Button>
    </section>
    {error?<ErrorState title={error} onRetry={()=>setReload(v=>v+1)}/>:loading&&!data?<div className="flex min-h-64 items-center justify-center"><LoadingSpinner/></div>:data?.items.length===0?<EmptyState className="rounded-2xl border border-mis-border bg-white" title={emptyTitle}/>:data?<section className="overflow-hidden rounded-2xl border border-mis-border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><Th>{ct('caseId')}</Th><Th>{ct('customerName')}</Th><Th>{ct('activityType')}</Th><Th>{ct('outcome')}</Th><Th>{ct('lastActivity')}</Th><Th>{ct('portfolioNextFollowUp')}</Th>{data.access.isManager&&<Th>{ct('performedBy')}</Th>}<Th>{ct('actions')}</Th></tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(x=><tr className="cursor-pointer hover:bg-slate-50" key={x.id} onClick={()=>void openDetails(x.id)}><Td bidi>{x.caseNumber}</Td><Td><strong className="text-mis-navy">{x.customerName}</strong></Td><Td><StatusBadge tone="info">{ct(x.activityType)}</StatusBadge></Td><Td>{x.outcome?ct(x.outcome):'—'}</Td><Td>{dateTime(x.activityAt)}</Td><Td>{dateTime(x.nextFollowUpAt)}</Td>{data.access.isManager&&<Td>{x.performedBy}</Td>}<Td><Button fullWidth={false} leftIcon={<Eye className="h-4 w-4"/>} onClick={e=>{e.stopPropagation();void openDetails(x.id);}} size="sm" variant="ghost">{ct('view')}</Button></Td></tr>)}</tbody></table></div><div className="flex flex-col gap-3 border-t border-mis-border px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><ProfessionalSelect className="field h-9 w-20 py-1" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}}>{[20,50,100].map(x=><option key={x}>{x}</option>)}</ProfessionalSelect><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage}/></div></section>:null}
    <Modal open={Boolean(details)||detailsLoading} onClose={()=>setDetails(undefined)} size="xl" title={details?`${details.customerName} · ${details.caseNumber}`:ct('loading')}>
      {detailsLoading&&!details?<div className="flex min-h-48 items-center justify-center"><LoadingSpinner/></div>:details?<div className="space-y-6"><section className="grid gap-4 rounded-xl bg-slate-50 p-4 sm:grid-cols-3"><Info label={ct('caseId')} value={details.caseNumber}/><Info label={ct('mobile')} value={details.mobile}/><Info label={ct('outstandingAmount')} value={money(details.outstandingAmount)}/><Info label={ct('status')} value={ct(details.caseStatus)}/><Info label={ct('assignedTo')} value={details.assignedCollectorName}/><Info label={ct('bank')} value={details.bankName}/></section><section className="grid gap-4 sm:grid-cols-3"><Info label={ct('activityDateTime')} value={dateTime(details.activityAt)}/><Info label={ct('activityType')} value={ct(details.activityType)}/><Info label={ct('outcome')} value={details.outcome?ct(details.outcome):undefined}/><Info label={ct('performedBy')} value={details.performedBy}/><Info label={ct('portfolioNextFollowUp')} value={dateTime(details.nextFollowUpAt)}/><Info label={ct('notes')} value={details.notes}/></section><section><h3 className="mb-4 font-bold text-mis-primary">{ct('activityTimeline')}</h3>{details.timeline.length?<div className="space-y-3">{details.timeline.map(x=><div className="border-s-2 border-mis-sky ps-4" key={x.id}><div className="flex flex-wrap items-center gap-2"><strong>{ct(x.activityType)}</strong>{x.outcome&&<StatusBadge tone="neutral">{ct(x.outcome)}</StatusBadge>}<time className="text-xs text-slate-500">{dateTime(x.activityAt)}</time></div>{x.notes&&<p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{x.notes}</p>}<p className="mt-1 text-xs text-slate-500">{x.performedBy}{x.nextFollowUpAt?` · ${ct('portfolioNextFollowUp')}: ${dateTime(x.nextFollowUpAt)}`:''}</p></div>)}</div>:<p className="text-sm text-slate-500">{ct('noActivity')}</p>}</section></div>:null}
      {details ? <div className="mt-5 flex justify-end"><Link className="inline-flex items-center rounded-xl bg-mis-primary px-4 py-2.5 text-sm font-bold text-white" to={`${workspaceBase}/${bank.id}/visits?create=1&caseId=${details.caseId}&caseSearch=${encodeURIComponent(details.caseNumber)}`}>{ct('createVisit')}</Link></div> : null}
    </Modal>
    <AddActivityModal bankId={bank.id} access={data?.access} open={addOpen} onClose={()=>setAddOpen(false)} onSaved={created=>{setAddOpen(false);setDetails(created);setReload(v=>v+1);toast.success(ct('activitySaved'));}} saving={saving} setSaving={setSaving} money={money} ct={ct}/>
  </div>;
}

function AddActivityModal({bankId,access,open,onClose,onSaved,saving,setSaving,money,ct}:{bankId:string;access?:BankActivityPage['access'];open:boolean;onClose:()=>void;onSaved:(x:BankActivityDetails)=>void;saving:boolean;setSaving:(x:boolean)=>void;money:(x:number)=>string;ct:(x:string)=>string}){
  const toast=useToast(); const [caseSearch,setCaseSearch]=useState(''),[cases,setCases]=useState<BankActivityCaseLookup[]>([]),[caseId,setCaseId]=useState(''),[type,setType]=useState('CALL'),[outcome,setOutcome]=useState(''),[notes,setNotes]=useState(''),[next,setNext]=useState('');
  useEffect(()=>{if(!open)return;const id=window.setTimeout(()=>void collectionsService.bankActivityCases(bankId,caseSearch).then(setCases).catch(()=>setCases([])),250);return()=>window.clearTimeout(id);},[bankId,caseSearch,open]);
  useEffect(()=>{if(open){setCaseSearch('');setCaseId('');setType('CALL');setOutcome('');setNotes('');setNext('');}},[open]); const chosen=cases.find(x=>x.id===caseId);
  async function submit(e:FormEvent){e.preventDefault();if(!caseId)return;setSaving(true);try{const value={caseId,activityType:type,outcome:type==='CALL'?outcome||undefined:outcome||undefined,notes:notes.trim()||undefined,nextFollowUpAt:next?new Date(next).toISOString():undefined};onSaved(await collectionsService.createBankActivity(bankId,value));}catch(err){toast.error(getApiErrorMessage(err,ct('activitySaveError')));}finally{setSaving(false);}}
  return <Modal open={open} onClose={()=>!saving&&onClose()} size="lg" title={ct('addActivity')} footer={<><Button disabled={saving} fullWidth={false} onClick={onClose} variant="outline">{ct('cancel')}</Button><Button disabled={!caseId||type==='CALL'&&!outcome} form="bank-activity-form" fullWidth={false} isLoading={saving} type="submit">{ct('saveActivity')}</Button></>}><form id="bank-activity-form" className="space-y-4" onSubmit={submit}><label className="block text-sm font-semibold">{ct('searchPortfolioCases')}<input className="field mt-2" value={caseSearch} onChange={e=>setCaseSearch(e.target.value)}/></label><label className="block text-sm font-semibold">{ct('caseId')}<ProfessionalSelect className="field mt-2" required value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">{ct('selectCase')}</option>{cases.map(x=><option key={x.id} value={x.id}>{x.caseNumber} — {x.customerName}</option>)}</ProfessionalSelect></label>{chosen&&<div className="grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-3"><Info label={ct('customerName')} value={chosen.customerName}/><Info label={ct('mobile')} value={chosen.mobile}/><Info label={ct('outstandingAmount')} value={money(chosen.outstandingAmount)}/><Info label={ct('status')} value={ct(chosen.status)}/><Info label={ct('assignedTo')} value={chosen.assignedCollectorName}/></div>}<div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">{ct('activityType')}<ProfessionalSelect className="field mt-2" value={type} onChange={e=>{setType(e.target.value);setOutcome('');}}>{access?.activityTypes.map(x=><option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></label><label className="block text-sm font-semibold">{ct('outcome')}<ProfessionalSelect className="field mt-2" required={type==='CALL'} value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">—</option>{access?.callOutcomes.map(x=><option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></label></div><label className="block text-sm font-semibold">{ct('notes')}<textarea className="field mt-2" maxLength={4000} rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="block text-sm font-semibold">{ct('portfolioNextFollowUp')}<DateControl className="field mt-2" mode="datetime" value={next} onChange={e=>setNext(e.target.value)}/></label></form></Modal>;
}
function Th({children}:{children:React.ReactNode}){return <th className="px-4 py-3 text-start font-bold">{children}</th>;} function Td({children,bidi}:{children:React.ReactNode;bidi?:boolean}){return <td className="px-4 py-3 text-slate-600" data-bidi={bidi?'ltr':undefined}>{children}</td>;} function Info({label,value}:{label:string;value?:React.ReactNode}){return <div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 break-words font-semibold text-mis-navy">{value||'—'}</p></div>;}
