import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { Eye, RefreshCw, Search, SlidersHorizontal, Sparkles, UserMinus, UserRoundCheck } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { Button } from '../../components/common/Button';
import { EmptyState } from '../../components/common/EmptyState';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { Pagination } from '../../components/common/Pagination';
import { StatusBadge } from '../../components/common/StatusBadge';
import { useToast } from '../../components/common/Toast';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { AutoDistributionPreview, BankPortfolioCaseDetails, CaseDistributionPage, CaseDistributionSummary, DistributionCollector, DistributionImport, DistributionPreview } from '../../features/collections/types/collections';
import { getApiErrorMessage } from '../../services/apiClient';
import type { BankWorkspaceContext } from './BankWorkspaceLayout';

type Action = 'assign' | 'reassign' | 'unassign';

export function BankCaseDistributionPage() {
  const { bank } = useOutletContext<BankWorkspaceContext>(); const { language, ct } = useCollectionsLocalization(); const toast = useToast();
  const [assigned, setAssigned] = useState(false), [summary, setSummary] = useState<CaseDistributionSummary>(), [data, setData] = useState<CaseDistributionPage>();
  const [collectors, setCollectors] = useState<DistributionCollector[]>([]), [imports, setImports] = useState<DistributionImport[]>([]);
  const [searchInput, setSearchInput] = useState(''), [search, setSearch] = useState(''), [status, setStatus] = useState(''), [collectorId, setCollectorId] = useState(''), [importId, setImportId] = useState(''), [sortBy, setSortBy] = useState('');
  const [page, setPage] = useState(1), [pageSize, setPageSize] = useState(20), [selected, setSelected] = useState<string[]>([]), [reload, setReload] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [dialog, setDialog] = useState<Action>(), [targetCollector, setTargetCollector] = useState(''), [reason, setReason] = useState('Distribution assignment'), [preview, setPreview] = useState<DistributionPreview>(), [saving, setSaving] = useState(false);
  const [autoOpen, setAutoOpen] = useState(false), [autoCollectors, setAutoCollectors] = useState<string[]>([]), [method, setMethod] = useState('EQUAL_COUNT'), [autoPreview, setAutoPreview] = useState<AutoDistributionPreview>();
  const [details, setDetails] = useState<BankPortfolioCaseDetails>();
  useEffect(() => { const id = window.setTimeout(() => { setSearch(searchInput.trim()); setPage(1); }, 350); return () => window.clearTimeout(id); }, [searchInput]);
  useEffect(() => { let active = true; setLoading(true); setError(''); const query = { page, pageSize, search, status, collectorId: assigned ? collectorId : undefined, importId, sortBy };
    void Promise.all([collectionsService.distributionSummary(bank.id), collectionsService.distributionCases(bank.id, assigned, query), collectionsService.distributionCollectors(bank.id), collectionsService.distributionImports(bank.id)])
      .then(([s, d, c, i]) => { if (active) { setSummary(s); setData(d); setCollectors(c); setImports(i); setSelected(current => current.filter(id => d.items.some(x => x.id === id))); } }).catch(e => { if (active) setError(getApiErrorMessage(e, ct('distributionLoadError'))); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [assigned, bank.id, collectorId, ct, importId, page, pageSize, reload, search, sortBy, status]);
  const money = (v: number) => new Intl.NumberFormat(language === 'ar' ? 'ar-EG' : 'en-EG', { style: 'currency', currency: 'EGP', maximumFractionDigits: 0 }).format(v);
  const date = (v?: string) => v ? new Intl.DateTimeFormat(language === 'ar' ? 'ar-EG' : 'en-GB', { dateStyle: 'medium' }).format(new Date(v)) : '—';
  const allPage = Boolean(data?.items.length) && data!.items.every(x => selected.includes(x.id));
  const chosenCollector = collectors.find(x => x.id === targetCollector);
  const clear = () => { setSearchInput(''); setSearch(''); setStatus(''); setCollectorId(''); setImportId(''); setSortBy(''); setPage(1); };
  const start = (action: Action, ids = selected) => { setSelected(ids); setDialog(action); setTargetCollector(''); setReason(action === 'unassign' ? 'Return to unassigned queue' : 'Distribution assignment'); setPreview(undefined); };
  async function nextAction() { if (!dialog || reason.trim().length < 2 || (dialog !== 'unassign' && !targetCollector)) return; const value = { caseIds: selected, collectorId: dialog === 'unassign' ? undefined : targetCollector, reason: reason.trim() }; setSaving(true); try { if (!preview) setPreview(await collectionsService.previewDistribution(bank.id, dialog, value)); else { const result = await collectionsService.applyDistribution(bank.id, dialog, value); toast.success(dialog === 'unassign' ? ct('unassignmentCompleted') : `${result.caseCount} ${ct('assignmentCompletedTo')} ${result.collectorName}`); setDialog(undefined); setPreview(undefined); setSelected([]); setReload(v => v + 1); } } catch (e) { toast.error(getApiErrorMessage(e, ct('distributionActionError'))); } finally { setSaving(false); } }
  async function nextAuto() { if (!autoCollectors.length || reason.trim().length < 2) return; const value = { caseIds: selected, collectorIds: autoCollectors, method, reason: reason.trim() }; setSaving(true); try { if (!autoPreview) setAutoPreview(await collectionsService.previewAutoDistribution(bank.id, value)); else { await collectionsService.confirmAutoDistribution(bank.id, value); toast.success(ct('autoDistributionCompleted')); setAutoOpen(false); setAutoPreview(undefined); setSelected([]); setReload(v => v + 1); } } catch (e) { toast.error(getApiErrorMessage(e, ct('distributionActionError'))); } finally { setSaving(false); } }
  return <div>
    <header className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-2xl font-bold text-mis-navy">{ct('caseDistribution')}</h2><p className="mt-2 text-sm text-slate-500">{ct('caseDistributionDescription')}</p></div><Button fullWidth={false} leftIcon={<RefreshCw className="h-4 w-4" />} onClick={() => setReload(v => v + 1)} size="sm" variant="outline">{ct('refresh')}</Button></header>
    <section className="mb-4 grid grid-cols-2 divide-x divide-mis-border rounded-2xl border border-mis-border bg-white p-4 shadow-sm rtl:divide-x-reverse md:grid-cols-4">{[[ct('totalCases'), summary?.totalCases], [ct('unassignedCases'), summary?.unassignedCases], [ct('assignedCases'), summary?.assignedCases], [ct('collectorsLabel'), summary?.collectors]].map(([label,value]) => <div className="px-4 py-2" key={String(label)}><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-mis-navy">{value ?? '—'}</p></div>)}</section>
    <div className="mb-4 flex gap-2 border-b border-mis-border"><button className={`px-4 py-3 text-sm font-bold ${!assigned ? 'border-b-2 border-mis-primary text-mis-primary' : 'text-slate-500'}`} onClick={() => { setAssigned(false); setSelected([]); setPage(1); }}>{ct('unassignedCases')} ({summary?.unassignedCases ?? 0})</button><button className={`px-4 py-3 text-sm font-bold ${assigned ? 'border-b-2 border-mis-primary text-mis-primary' : 'text-slate-500'}`} onClick={() => { setAssigned(true); setSelected([]); setPage(1); }}>{ct('assignedCases')} ({summary?.assignedCases ?? 0})</button></div>
    <section className="mb-4 grid gap-3 rounded-2xl border border-mis-border bg-white p-4 sm:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_170px_200px_180px_170px_auto]">
      <label className="relative"><Search className="absolute top-3.5 h-4 w-4 text-slate-400" style={{ insetInlineStart: '.85rem' }} /><input className="field h-11 py-2 ps-10 leading-normal" placeholder={ct('searchPortfolioCases')} value={searchInput} onChange={e => setSearchInput(e.target.value)} /></label>
      <ProfessionalSelect className="field h-11 py-2 leading-normal" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">{ct('allPortfolioStatuses')}</option>{['ACTIVE','ON_HOLD','SETTLED','CLOSED','LEGAL','WRITE_OFF'].map(x => <option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect>
      {assigned ? <ProfessionalSelect className="field h-11 py-2 leading-normal" value={collectorId} onChange={e => { setCollectorId(e.target.value); setPage(1); }}><option value="">{ct('allCollectors')}</option>{collectors.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect> : <span />}
      <ProfessionalSelect className="field h-11 py-2 leading-normal" value={importId} onChange={e => { setImportId(e.target.value); setPage(1); }}><option value="">{ct('allPortfolios')}</option>{imports.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect>
      <ProfessionalSelect className="field h-11 py-2 leading-normal" value={sortBy} onChange={e => setSortBy(e.target.value)}><option value="">{ct('sortBy')}</option><option value="customer">{ct('customerName')}</option><option value="outstanding">{ct('outstandingAmount')}</option><option value="status">{ct('status')}</option>{assigned && <option value="assigned">{ct('assignedDate')}</option>}</ProfessionalSelect>
      <Button fullWidth={false} leftIcon={<SlidersHorizontal className="h-4 w-4" />} onClick={clear} size="sm" variant="ghost">{ct('clearFilters')}</Button>
    </section>
    {selected.length ? <div className="sticky top-3 z-10 mb-4 flex flex-wrap items-center gap-3 rounded-xl border border-mis-sky bg-mis-pale px-4 py-3 shadow-sm"><strong className="text-sm text-mis-navy">{selected.length} {ct('casesSelected')}</strong><Button fullWidth={false} leftIcon={<UserRoundCheck className="h-4 w-4" />} onClick={() => start(assigned ? 'reassign' : 'assign')} size="sm">{ct(assigned ? 'reassign' : 'assignToCollector')}</Button>{!assigned && <Button fullWidth={false} leftIcon={<Sparkles className="h-4 w-4" />} onClick={() => { setAutoOpen(true); setAutoCollectors([]); setAutoPreview(undefined); setReason('Automatic distribution'); }} size="sm" variant="outline">{ct('autoDistribute')}</Button>}{assigned && <Button fullWidth={false} leftIcon={<UserMinus className="h-4 w-4" />} onClick={() => start('unassign')} size="sm" variant="danger">{ct('unassign')}</Button>}<Button fullWidth={false} onClick={() => setSelected([])} size="sm" variant="ghost">{ct('clearSelection')}</Button></div> : null}
    {error ? <ErrorState title={error} onRetry={() => setReload(v => v + 1)} /> : loading && !data ? <div className="flex min-h-64 items-center justify-center"><LoadingSpinner /></div> : data?.items.length === 0 ? <EmptyState className="rounded-2xl border border-mis-border bg-white" title={search || status || collectorId || importId ? ct('noFilteredCases') : ct(assigned ? 'noAssignedDistributionCases' : 'allCasesAssigned')} /> : data ? <section className="overflow-hidden rounded-2xl border border-mis-border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><Th><input aria-label={ct('selectCurrentPage')} checked={allPage} onChange={e => setSelected(e.target.checked ? data.items.map(x => x.id) : [])} type="checkbox" /></Th><Th>{ct('caseId')}</Th><Th>{ct('customerName')}</Th><Th>{ct('mobile')}</Th><Th>{ct('outstandingAmount')}</Th>{assigned && <Th>{ct('assignedTo')}</Th>}<Th>{ct('status')}</Th><Th>{assigned ? ct('assignedDate') : ct('importPortfolioLabel')}</Th><Th>{ct('actions')}</Th></tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(x => <tr key={x.id} className="hover:bg-slate-50"><Td><input checked={selected.includes(x.id)} onChange={e => setSelected(v => e.target.checked ? [...new Set([...v,x.id])] : v.filter(id => id !== x.id))} type="checkbox" /></Td><Td><button className="font-bold text-mis-primary hover:underline" onClick={() => void collectionsService.bankPortfolioCase(bank.id,x.id).then(setDetails)}>{x.caseNumber}</button></Td><Td><button className="font-semibold text-mis-navy hover:text-mis-primary" onClick={() => void collectionsService.bankPortfolioCase(bank.id,x.id).then(setDetails)}>{x.customerName}</button></Td><Td bidi>{x.mobile || '—'}</Td><Td bidi>{money(x.outstandingAmount)}</Td>{assigned && <Td>{x.collectorName}</Td>}<Td><StatusBadge tone="info">{ct(x.status)}</StatusBadge></Td><Td>{assigned ? date(x.assignedAt) : x.importName || '—'}</Td><Td><Button fullWidth={false} leftIcon={<Eye className="h-4 w-4" />} onClick={() => void collectionsService.bankPortfolioCase(bank.id,x.id).then(setDetails)} size="sm" variant="ghost">{ct('openPortfolioCase')}</Button></Td></tr>)}</tbody></table></div><div className="flex flex-col gap-3 border-t border-mis-border px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><ProfessionalSelect className="field h-9 w-20 py-1" value={pageSize} onChange={e => { setPageSize(Number(e.target.value)); setPage(1); }}>{[20,50,100].map(x => <option key={x}>{x}</option>)}</ProfessionalSelect><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage} /></div></section> : null}
    <Modal open={Boolean(dialog)} onClose={() => !saving && setDialog(undefined)} size="md" title={ct(dialog === 'unassign' ? 'confirmUnassignment' : dialog === 'reassign' ? 'confirmReassignment' : 'assignCases')} footer={<><Button disabled={saving} fullWidth={false} onClick={() => preview ? setPreview(undefined) : setDialog(undefined)} variant="outline">{ct(preview ? 'back' : 'cancel')}</Button><Button disabled={dialog !== 'unassign' && !targetCollector} fullWidth={false} isLoading={saving} onClick={() => void nextAction()} variant={dialog === 'unassign' ? 'danger' : 'primary'}>{ct(preview ? dialog === 'unassign' ? 'unassign' : dialog === 'reassign' ? 'confirmReassignment' : 'confirmPortfolioAssignment' : 'review')}</Button></>}>
      {preview ? <PreviewBlock preview={preview} money={money} ct={ct} /> : <div className="space-y-4"><p className="text-sm text-slate-600">{selected.length} {ct('casesSelected')}</p>{dialog !== 'unassign' && <><label className="block text-sm font-semibold">{ct('collector')}<ProfessionalSelect className="field mt-2" value={targetCollector} onChange={e => setTargetCollector(e.target.value)}><option value="">{ct('selectPortfolioCollector')}</option>{collectors.map(x => <option key={x.id} value={x.id}>{x.name} — {x.assignedCases}</option>)}</ProfessionalSelect></label>{chosenCollector && <Workload collector={chosenCollector} money={money} ct={ct} />}</>}<label className="block text-sm font-semibold">{ct('assignmentReasonLabel')}<textarea className="field mt-2" maxLength={500} rows={3} value={reason} onChange={e => setReason(e.target.value)} /></label></div>}
    </Modal>
    <Modal open={autoOpen} onClose={() => !saving && setAutoOpen(false)} size="lg" title={ct(autoPreview ? 'distributionPreview' : 'autoDistribute')} footer={<><Button disabled={saving} fullWidth={false} onClick={() => autoPreview ? setAutoPreview(undefined) : setAutoOpen(false)} variant="outline">{ct(autoPreview ? 'back' : 'cancel')}</Button><Button disabled={!autoCollectors.length} fullWidth={false} isLoading={saving} onClick={() => void nextAuto()}>{ct(autoPreview ? 'confirmDistribution' : 'review')}</Button></>}>
      {autoPreview ? <div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><Th>{ct('collector')}</Th><Th>{ct('casesCount')}</Th><Th>{ct('totalOutstanding')}</Th></tr></thead><tbody>{autoPreview.collectors.map(x => <tr key={x.collectorId}><Td>{x.collectorName}</Td><Td>{x.caseCount}</Td><Td bidi>{money(x.outstandingAmount)}</Td></tr>)}</tbody></table></div><p className="mt-4 font-bold">{ct('totalCases')}: {autoPreview.totalCases} · {money(autoPreview.totalOutstanding)}</p></div> : <div className="space-y-4"><label className="block text-sm font-semibold">{ct('distributionMethod')}<ProfessionalSelect className="field mt-2" value={method} onChange={e => setMethod(e.target.value)}><option value="EQUAL_COUNT">{ct('equalByCaseCount')}</option><option value="BALANCED_AMOUNT">{ct('balancedByOutstanding')}</option></ProfessionalSelect></label><fieldset><legend className="mb-2 text-sm font-semibold">{ct('collectorsLabel')}</legend><div className="grid gap-2 sm:grid-cols-2">{collectors.map(x => <label className="flex items-center gap-3 rounded-xl border border-mis-border p-3" key={x.id}><input type="checkbox" checked={autoCollectors.includes(x.id)} onChange={e => setAutoCollectors(v => e.target.checked ? [...v,x.id] : v.filter(id => id !== x.id))} /><span><strong className="block text-sm">{x.name}</strong><small className="text-slate-500">{x.assignedCases} · {money(x.totalOutstanding)}</small></span></label>)}</div></fieldset><label className="block text-sm font-semibold">{ct('assignmentReasonLabel')}<textarea className="field mt-2" maxLength={500} rows={2} value={reason} onChange={e => setReason(e.target.value)} /></label></div>}
    </Modal>
    <Modal open={Boolean(details)} onClose={() => setDetails(undefined)} size="lg" title={details?.customerName || ct('openPortfolioCase')}>{details && <div className="grid gap-4 sm:grid-cols-2"><Info label={ct('caseId')} value={details.caseNumber} /><Info label={ct('status')} value={ct(details.status)} /><Info label={ct('mobile')} value={details.mobile} /><Info label={ct('outstandingAmount')} value={money(details.outstandingAmount)} /><Info label={ct('assignedTo')} value={details.assignedCollectorName} /><Info label={ct('importedFrom')} value={details.importedFrom} /></div>}</Modal>
  </div>;
}

function PreviewBlock({ preview, money, ct }: { preview: DistributionPreview; money: (v:number)=>string; ct:(k:string)=>string }) { return <div className="space-y-4"><Info label={ct('casesCount')} value={String(preview.caseCount)} /><Info label={ct('totalOutstanding')} value={money(preview.totalOutstanding)} />{preview.collectorName && <Info label={ct('collector')} value={preview.collectorName} />}{preview.previousCollectors.length > 0 && <Info label={ct('fromCollectors')} value={preview.previousCollectors.join(', ')} />}</div>; }
function Workload({ collector, money, ct }: { collector: DistributionCollector; money:(v:number)=>string; ct:(k:string)=>string }) { return <div className="grid grid-cols-2 rounded-xl bg-slate-50 p-3 text-sm"><Info label={ct('assignedCases')} value={String(collector.assignedCases)} /><Info label={ct('totalOutstanding')} value={money(collector.totalOutstanding)} /></div>; }
function Info({ label, value }: { label:string; value?:string }) { return <div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 font-semibold text-mis-navy">{value || '—'}</p></div>; }
function Th({ children }: { children: React.ReactNode }) { return <th className="px-4 py-3 text-start font-bold">{children}</th>; }
function Td({ children, bidi }: { children: React.ReactNode; bidi?:boolean }) { return <td className="px-4 py-3 text-slate-600" data-bidi={bidi ? 'ltr' : undefined}>{children}</td>; }
