import { ProfessionalSelect } from '../../components/forms/ProfessionalSelect';
import { DateControl } from '../../components/forms/DateControl';
import { Eye, Plus, RefreshCw, Search, SlidersHorizontal } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useOutletContext, useSearchParams } from 'react-router-dom';
import { Button } from '../../components/common/Button';
import { EmptyState } from '../../components/common/EmptyState';
import { ErrorState } from '../../components/common/ErrorState';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { Pagination } from '../../components/common/Pagination';
import { StatusBadge } from '../../components/common/StatusBadge';
import { useToast } from '../../components/common/Toast';
import { CreateVisitModal } from '../../features/collections/components/CreateVisitModal';
import { useCollectionsLocalization } from '../../features/collections/localization/collectionsTranslations';
import { collectionsService } from '../../features/collections/services/collectionsService';
import type { BankPortfolioCollector, BankVisitDetails, BankVisitPage, BankVisitSummary } from '../../features/collections/types/collections';
import { getApiErrorMessage } from '../../services/apiClient';
import type { BankWorkspaceContext } from './BankWorkspaceLayout';

const results=['CUSTOMER_MET','CUSTOMER_NOT_AVAILABLE','ADDRESS_NOT_FOUND','WRONG_ADDRESS','REFUSED_CONTACT','PROMISE_TO_PAY_DISCUSSED','FOLLOW_UP_REQUIRED','OTHER'];
export function BankVisitsManagementPage(){const{bank}=useOutletContext<BankWorkspaceContext>();const{language,ct}=useCollectionsLocalization();const toast=useToast();const[params,setParams]=useSearchParams();const[data,setData]=useState<BankVisitPage>(),[summary,setSummary]=useState<BankVisitSummary>(),[collectors,setCollectors]=useState<BankPortfolioCollector[]>([]),[view,setView]=useState('TODAY'),[searchInput,setSearchInput]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[visitDate,setVisitDate]=useState(''),[result,setResult]=useState(''),[collectorId,setCollectorId]=useState(''),[sortBy,setSortBy]=useState('date'),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[reload,setReload]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[details,setDetails]=useState<BankVisitDetails>(),[createOpen,setCreateOpen]=useState(params.get('create')==='1'),[action,setAction]=useState<'complete'|'reschedule'|'reassign'|'cancel'|'missed'|'start'>(),[saving,setSaving]=useState(false);
useEffect(()=>{const id=setTimeout(()=>{setSearch(searchInput.trim());setPage(1);},350);return()=>clearTimeout(id);},[searchInput]);useEffect(()=>{let active=true;setLoading(true);setError('');void Promise.all([collectionsService.bankVisits(bank.id,{page,pageSize,view,search,status,visitDate,result,collectorId,sortBy}),collectionsService.bankVisitSummary(bank.id),collectionsService.bankVisitCollectors(bank.id)]).then(([d,s,c])=>{if(active){setData(d);setSummary(s);setCollectors(c);}}).catch(e=>active&&setError(getApiErrorMessage(e,ct('visitLoadError')))).finally(()=>active&&setLoading(false));return()=>{active=false;};},[bank.id,collectorId,ct,page,pageSize,reload,result,search,sortBy,status,view,visitDate]);
const dt=(v?:string)=>v?new Intl.DateTimeFormat(language==='ar'?'ar-EG':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';const clear=()=>{setSearchInput('');setSearch('');setStatus('');setVisitDate('');setResult('');setCollectorId('');setSortBy('date');setPage(1);};const open=async(id:string)=>{try{setDetails(await collectionsService.bankVisit(bank.id,id));}catch(e){toast.error(getApiErrorMessage(e,ct('visitLoadError')));}};const refreshed=(x:BankVisitDetails)=>{setDetails(x);setAction(undefined);setReload(v=>v+1);};
async function perform(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!details||!action||saving)return;const form=new FormData(e.currentTarget);setSaving(true);try{let x:BankVisitDetails;if(action==='complete')x=await collectionsService.completeBankVisit(bank.id,details.id,{result:String(form.get('result')),notes:String(form.get('notes')||'')||undefined,nextFollowUpAt:form.get('nextFollowUpAt')?new Date(String(form.get('nextFollowUpAt'))).toISOString():undefined});else if(action==='reschedule')x=await collectionsService.rescheduleBankVisit(bank.id,details.id,new Date(String(form.get('scheduledAt'))).toISOString());else if(action==='reassign')x=await collectionsService.reassignBankVisit(bank.id,details.id,String(form.get('collectorId')));else if(action==='cancel')x=await collectionsService.cancelBankVisit(bank.id,details.id,String(form.get('notes')||'')||undefined);else x=await collectionsService.changeBankVisitStatus(bank.id,details.id,action==='missed'?'MISSED':'IN_PROGRESS',String(form.get('notes')||'')||undefined);refreshed(x);toast.success(ct('visitUpdated'));}catch(err){toast.error(getApiErrorMessage(err,ct('visitSaveError')));}finally{setSaving(false);}}
const empty=view==='TODAY'?ct('noVisitsToday'):view==='UPCOMING'?ct('noUpcomingVisits'):view==='OVERDUE'?ct('noOverdueVisits'):view==='COMPLETED'?ct('noCompletedVisits'):ct('noMatchingVisits');return <div><header className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-2xl font-bold text-mis-navy">{ct('visitsManagement')}</h2><p className="mt-2 text-sm text-slate-500">{ct('visitsManagementDescription')}</p></div><div className="flex gap-2">{data?.access.canCreate&&<Button fullWidth={false} leftIcon={<Plus className="h-4 w-4"/>} onClick={()=>setCreateOpen(true)} size="sm">{ct('createVisit')}</Button>}<Button fullWidth={false} leftIcon={<RefreshCw className="h-4 w-4"/>} onClick={()=>setReload(v=>v+1)} size="sm" variant="outline">{ct('refresh')}</Button></div></header>
<section className="mb-4 grid grid-cols-2 divide-x divide-mis-border rounded-2xl border border-mis-border bg-white p-4 shadow-sm rtl:divide-x-reverse md:grid-cols-4">{[[ct('visitsToday'),summary?.visitsToday],[ct('upcomingVisits'),summary?.upcomingVisits],[ct('overdueVisits'),summary?.overdueVisits],[ct('completedToday'),summary?.completedToday]].map(([l,v])=><div className="px-4 py-2" key={String(l)}><p className="text-xs font-semibold text-slate-500">{l}</p><p className="mt-1 text-xl font-bold text-mis-navy">{v??'—'}</p></div>)}</section><div className="mb-4 flex gap-1 overflow-x-auto border-b border-mis-border">{[['TODAY','today'],['UPCOMING','upcoming'],['OVERDUE','overdue'],['COMPLETED','completed'],['ALL','allVisits']].map(([v,l])=><button key={v} onClick={()=>{setView(v);setPage(1);}} className={`shrink-0 px-4 py-3 text-sm font-bold ${view===v?'border-b-2 border-mis-primary text-mis-primary':'text-slate-500'}`}>{ct(l)}</button>)}</div>
<section className="mb-4 grid gap-3 rounded-2xl border border-mis-border bg-white p-4 sm:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_150px_150px_190px_180px_150px_auto]"><label className="relative"><Search className="absolute top-3.5 h-4 w-4 text-slate-400" style={{insetInlineStart:'.85rem'}}/><input className="field h-11 py-2 ps-10" placeholder={ct('searchVisits')} value={searchInput} onChange={e=>setSearchInput(e.target.value)}/></label><ProfessionalSelect className="field h-11 py-2" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">{ct('allStatuses')}</option>{['SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','MISSED'].map(x=><option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect><DateControl aria-label={ct('visitDate')} className="field h-11 py-2"  value={visitDate} onChange={e=>{setVisitDate(e.target.value);setPage(1);}}/><ProfessionalSelect className="field h-11 py-2" value={result} onChange={e=>{setResult(e.target.value);setPage(1);}}><option value="">{ct('allVisitResults')}</option>{results.map(x=><option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect>{data?.access.isManager?<ProfessionalSelect className="field h-11 py-2" value={collectorId} onChange={e=>{setCollectorId(e.target.value);setPage(1);}}><option value="">{ct('allCollectors')}</option>{collectors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect>:<span/>}<ProfessionalSelect className="field h-11 py-2" value={sortBy} onChange={e=>setSortBy(e.target.value)}><option value="date">{ct('visitDate')}</option><option value="customer">{ct('customerName')}</option><option value="status">{ct('status')}</option><option value="updated">{ct('updatedAt')}</option></ProfessionalSelect><Button fullWidth={false} leftIcon={<SlidersHorizontal className="h-4 w-4"/>} onClick={clear} size="sm" variant="ghost">{ct('clearFilters')}</Button></section>
{error?<ErrorState title={error} onRetry={()=>setReload(v=>v+1)}/>:loading&&!data?<div className="flex min-h-64 items-center justify-center"><LoadingSpinner/></div>:data?.items.length===0?<EmptyState className="rounded-2xl border border-mis-border bg-white" title={empty}/>:data?<section className="overflow-hidden rounded-2xl border border-mis-border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><Th>{ct('caseId')}</Th><Th>{ct('customerName')}</Th><Th>{ct('visitDate')}</Th><Th>{ct('visitTime')}</Th>{data.access.isManager&&<Th>{ct('collector')}</Th>}<Th>{ct('status')}</Th><Th>{ct('visitResult')}</Th><Th>{ct('actions')}</Th></tr></thead><tbody className="divide-y divide-mis-border">{data.items.map(x=><tr className="cursor-pointer hover:bg-slate-50" key={x.id} onClick={()=>void open(x.id)}><Td bidi>{x.caseNumber}</Td><Td><strong className="text-mis-navy">{x.customerName}</strong></Td><Td>{new Intl.DateTimeFormat(language==='ar'?'ar-EG':'en-GB',{dateStyle:'medium'}).format(new Date(x.scheduledAt))}</Td><Td bidi>{new Intl.DateTimeFormat(language==='ar'?'ar-EG':'en-GB',{timeStyle:'short'}).format(new Date(x.scheduledAt))}</Td>{data.access.isManager&&<Td>{x.collectorName}</Td>}<Td><StatusBadge tone={x.status==='COMPLETED'?'success':x.status==='CANCELLED'?'neutral':x.status==='MISSED'?'danger':'info'}>{ct(x.status)}</StatusBadge></Td><Td>{x.result?ct(x.result):'—'}</Td><Td><Button fullWidth={false} leftIcon={<Eye className="h-4 w-4"/>} size="sm" variant="ghost">{ct('view')}</Button></Td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-mis-border p-4"><ProfessionalSelect className="field h-9 w-20 py-1" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}}>{[20,50,100].map(x=><option key={x}>{x}</option>)}</ProfessionalSelect><Pagination page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} totalPages={data.totalPages} onPageChange={setPage}/></div></section>:null}
<CreateVisitModal access={data?.access} bankId={bank.id} initialCaseId={params.get('caseId')??undefined} initialSearch={params.get('caseSearch')??undefined} open={createOpen} onClose={()=>{setCreateOpen(false);setParams({});}} onSaved={x=>{setCreateOpen(false);setParams({});setDetails(x);setReload(v=>v+1);toast.success(ct('visitCreated'));}}/><Modal open={Boolean(details)} onClose={()=>setDetails(undefined)} size="xl" title={details?`${details.customerName} · ${details.caseNumber}`:ct('visitDetails')}>{details&&<div className="space-y-5"><div className="grid gap-4 rounded-xl bg-slate-50 p-4 sm:grid-cols-3"><Info label={ct('customerName')} value={details.customerName}/><Info label={ct('caseId')} value={details.caseNumber}/><Info label={ct('bank')} value={details.bankName}/><Info label={ct('visitAddress')} value={details.address}/><Info label={ct('visitDateTime')} value={dt(details.scheduledAt)}/><Info label={ct('assignedCollector')} value={details.collectorName}/><Info label={ct('status')} value={ct(details.status)}/><Info label={ct('visitResult')} value={details.result?ct(details.result):undefined}/><Info label={ct('visitPurpose')} value={details.purpose}/><Info label={ct('notes')} value={details.notes}/><Info label={ct('createdBy')} value={details.createdBy}/><Info label={ct('createdAt')} value={dt(details.createdAt)}/><Info label={ct('updatedAt')} value={dt(details.updatedAt)}/></div><div className="flex flex-wrap gap-2"><Link className="inline-flex items-center rounded-xl border border-mis-border px-4 py-2 text-sm font-bold text-mis-primary" to={`/collections/cases/${details.caseId}`}>{ct('openCase')}</Link>{!['COMPLETED','CANCELLED','MISSED'].includes(details.status)&&<><Button fullWidth={false} onClick={()=>setAction('complete')} size="sm">{ct('completeVisit')}</Button>{details.status!=='IN_PROGRESS'&&<Button fullWidth={false} onClick={()=>setAction('start')} size="sm" variant="secondary">{ct('startVisit')}</Button>}{details.access.isManager&&<><Button fullWidth={false} onClick={()=>setAction('reschedule')} size="sm" variant="outline">{ct('rescheduleVisit')}</Button><Button fullWidth={false} onClick={()=>setAction('reassign')} size="sm" variant="outline">{ct('reassignVisit')}</Button><Button fullWidth={false} onClick={()=>setAction('missed')} size="sm" variant="outline">{ct('markMissed')}</Button><Button fullWidth={false} onClick={()=>setAction('cancel')} size="sm" variant="danger">{ct('cancelVisit')}</Button></>}</>}</div></div>}</Modal><ActionModal action={action} collectors={collectors} details={details} saving={saving} ct={ct} onClose={()=>setAction(undefined)} onSubmit={perform}/></div>}

function ActionModal({action,collectors,details,saving,ct,onClose,onSubmit}:{action?:string;collectors:BankPortfolioCollector[];details?:BankVisitDetails;saving:boolean;ct:(x:string)=>string;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){const title=action==='complete'?'completeVisit':action==='reschedule'?'rescheduleVisit':action==='reassign'?'reassignVisit':action==='cancel'?'cancelVisit':action==='missed'?'markMissed':'startVisit';return <Modal open={Boolean(action&&details)} onClose={()=>!saving&&onClose()} size="sm" title={ct(title)} footer={<><Button disabled={saving} fullWidth={false} onClick={onClose} variant="outline">{ct('cancel')}</Button><Button form="visit-action-form" fullWidth={false} isLoading={saving} type="submit" variant={action==='cancel'?'danger':'primary'}>{ct('confirm')}</Button></>}><form className="space-y-4" id="visit-action-form" onSubmit={onSubmit}>{action==='complete'&&<><label className="block text-sm font-semibold">{ct('visitResult')}<ProfessionalSelect className="field mt-2" name="result" required>{results.map(x=><option key={x} value={x}>{ct(x)}</option>)}</ProfessionalSelect></label><label className="block text-sm font-semibold">{ct('notes')}<textarea className="field mt-2" maxLength={3000} name="notes" rows={3}/></label><label className="block text-sm font-semibold">{ct('nextFollowUp')}<DateControl className="field mt-2" name="nextFollowUpAt" mode="datetime"/></label></>}{action==='reschedule'&&<label className="block text-sm font-semibold">{ct('visitDateTime')}<DateControl className="field mt-2" name="scheduledAt" required mode="datetime"/></label>}{action==='reassign'&&<label className="block text-sm font-semibold">{ct('assignedCollector')}<ProfessionalSelect className="field mt-2" name="collectorId" required><option value="">{ct('selectCollector')}</option>{collectors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</ProfessionalSelect></label>}{['cancel','missed'].includes(action??'')&&<label className="block text-sm font-semibold">{ct('notes')}<textarea className="field mt-2" maxLength={3000} name="notes" rows={3}/></label>}<p className="text-sm text-slate-500">{ct('confirmVisitAction')}</p></form></Modal>}
function Th({children}:{children:React.ReactNode}){return <th className="px-4 py-3 text-start font-bold">{children}</th>}function Td({children,bidi}:{children:React.ReactNode;bidi?:boolean}){return <td className="px-4 py-3 text-slate-600" data-bidi={bidi?'ltr':undefined}>{children}</td>}function Info({label,value}:{label:string;value?:React.ReactNode}){return <div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 break-words font-semibold text-mis-navy">{value||'—'}</p></div>}
